# SPDX-License-Identifier: AGPL-3.0-only
"""Torque-free rigid-body reference trajectories from Basilisk 2.9.1 (ISC).

Oracle: a Basilisk `spacecraft.Spacecraft` hub with a general (non-diagonal) inertia, no gravity
body and no effectors, integrated by Basilisk's `svIntegratorRKF78` (relative tolerance 1e-12,
absolute tolerance 1e-14) at a 1 s task step and recorded every 100 s for 1e4 s.

Basilisk's attitude state is the MRP set sigma_BN. Each sample is written as the Euler parameters
of [BN] (Basilisk `RigidBodyKinematics.MRP2EP`, scalar first, sign chosen with beta0 >= 0) and the
body rates omega_BN_B. The initial [BN] is written in full so the consumer can check its own
quaternion convention against it.

Reproduce:
  source ~/Code/kshana-oracles/env.sh
  $ORACLE_PY gen_attitude_dynamics_basilisk_oracle.py > attitude_dynamics_basilisk_oracle.txt
"""

import numpy as np
from Basilisk import __version__ as BSK_VERSION
from Basilisk.simulation import spacecraft, svIntegrators
from Basilisk.utilities import RigidBodyKinematics as rbk
from Basilisk.utilities import SimulationBaseClass, macros

SPAN_S = 1.0e4
SAMPLE_S = 100.0
TASK_S = 1.0

CASES = [
    (
        "A",
        [[12.0, 0.8, -0.5], [0.8, 9.0, 0.3], [-0.5, 0.3, 6.0]],
        [0.03, -0.02, 0.05],
        [1.0, 2.0, 3.0],
        0.7,
    ),
    (
        "B",
        [[250.0, -12.0, 8.0], [-12.0, 180.0, -5.0], [8.0, -5.0, 120.0]],
        [-0.01, 0.04, 0.02],
        [-2.0, 1.0, 0.5],
        2.1,
    ),
]


def active_rotation(axis, angle):
    """The matrix that rotates a vector by `angle` about unit `axis` (Rodrigues)."""
    e = np.asarray(axis, dtype=float)
    e /= np.linalg.norm(e)
    k = np.array([[0.0, -e[2], e[1]], [e[2], 0.0, -e[0]], [-e[1], e[0], 0.0]])
    return np.eye(3) + np.sin(angle) * k + (1.0 - np.cos(angle)) * (k @ k)


def run(inertia, omega0, axis, angle):
    sim = SimulationBaseClass.SimBaseClass()
    proc = sim.CreateNewProcess("p")
    proc.addTask(sim.CreateNewTask("t", macros.sec2nano(TASK_S)))
    sc = spacecraft.Spacecraft()
    sc.ModelTag = "sc"
    sc.hub.mHub = 100.0
    sc.hub.IHubPntBc_B = inertia
    nb = active_rotation(axis, angle)  # body -> inertial
    bn = nb.T
    sigma0 = np.array(rbk.C2MRP(bn)).ravel()
    sc.hub.sigma_BNInit = [[sigma0[0]], [sigma0[1]], [sigma0[2]]]
    sc.hub.omega_BN_BInit = [[omega0[0]], [omega0[1]], [omega0[2]]]
    sc.hub.r_CN_NInit = [[7.0e6], [0.0], [0.0]]
    sc.hub.v_CN_NInit = [[0.0], [0.0], [0.0]]
    integ = svIntegrators.svIntegratorRKF78(sc)
    integ.relTol = 1e-12
    integ.absTol = 1e-14
    sc.setIntegrator(integ)
    sim.AddModelToTask("t", sc)
    rec = sc.scStateOutMsg.recorder(macros.sec2nano(SAMPLE_S))
    sim.AddModelToTask("t", rec)
    sim.InitializeSimulation()
    sim.ConfigureStopTime(macros.sec2nano(SPAN_S))
    sim.ExecuteSimulation()
    return bn, rec.times() * macros.NANO2SEC, rec.sigma_BN, rec.omega_BN_B


def main():
    print(f"# Torque-free rigid body from Basilisk {BSK_VERSION} spacecraft hub (ISC), svIntegratorRKF78")
    print("# rel tol 1e-12, abs tol 1e-14, task step 1 s, sampled every 100 s to 1e4 s.")
    print("# Generated by gen_attitude_dynamics_basilisk_oracle.py; see its docstring and NOTICE.md.")
    print("# CASE id | I row-major (9) | omega0 (3) | axis (3) | angle_rad")
    print("# BN0 id | [BN] at t=0 row-major (9)")
    print("# S id | t_s | beta0 beta1 beta2 beta3 (EP of [BN]) | wx wy wz (rad/s, body)")
    for name, inertia, omega0, axis, angle in CASES:
        bn, t, sig, om = run(inertia, omega0, axis, angle)
        flat = " ".join(f"{v:.17e}" for row in inertia for v in row)
        print(f"CASE {name} | {flat} | {' '.join(f'{v:.17e}' for v in omega0)} | "
              f"{' '.join(f'{v:.17e}' for v in axis)} | {angle:.17e}")
        print(f"BN0 {name} | {' '.join(f'{v:.17e}' for v in bn.ravel())}")
        for k in range(len(t)):
            b = np.array(rbk.MRP2EP(np.asarray(sig[k]))).ravel()
            if b[0] < 0:
                b = -b
            print(f"S {name} | {t[k]:.6f} | {' '.join(f'{v:.17e}' for v in b)} | "
                  f"{' '.join(f'{v:.17e}' for v in om[k])}")


if __name__ == "__main__":
    main()
