#!/usr/bin/env python3
"""Fixture generator for tests/bplane_gmat_oracle.rs.

1. Builds a grid of 192 hyperbolic Earth-centred states from elements and prints each one
   once (17 significant digits) to states.txt.
2. Writes bplane_grid.script (one spacecraft per state, one statement per line) for the
   General Mission Analysis Tool (GMAT) R2026a and runs it headless:
       source ~/Code/kshana-oracles/env.sh
       python3 tests/fixtures/bplane_gmat_oracle/make_fixture.py
3. Copies GMAT's report to gmat_bplane_report.txt.
"""
import math
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MU = 398600.4415  # km^3/s^2, set explicitly as Earth.Mu in the script
V_INF = [0.5, 2.0, 5.0, 12.0]  # km/s
R_P = [6578.0, 12000.0, 45000.0]  # km
ORIENT = [  # inclination, RAAN, argument of periapsis (deg)
    (28.5, 40.0, 75.0),
    (97.8, 300.0, 210.0),
    (5.0, 123.0, 330.0),
    (151.0, 220.0, 15.0),
]
NU_FRAC = [-0.9, -0.5, 0.0, 0.4]  # fraction of the asymptotic true anomaly


def rot(i, raan, argp):
    ci, si = math.cos(i), math.sin(i)
    co, so = math.cos(raan), math.sin(raan)
    cw, sw = math.cos(argp), math.sin(argp)
    p = (co * cw - so * sw * ci, so * cw + co * sw * ci, sw * si)
    q = (-co * sw - so * cw * ci, -so * sw + co * cw * ci, cw * si)
    return p, q


def state(v_inf, r_p, i, raan, argp, frac):
    a = -MU / v_inf**2
    e = 1.0 + r_p * v_inf**2 / MU
    slr = a * (1.0 - e * e)
    nu_inf = math.acos(-1.0 / e)
    nu = frac * nu_inf
    r = slr / (1.0 + e * math.cos(nu))
    vs = math.sqrt(MU / slr)
    p, q = rot(math.radians(i), math.radians(raan), math.radians(argp))
    rp = (r * math.cos(nu), r * math.sin(nu))
    vp = (-vs * math.sin(nu), vs * (e + math.cos(nu)))
    pos = [rp[0] * p[k] + rp[1] * q[k] for k in range(3)]
    vel = [vp[0] * p[k] + vp[1] * q[k] for k in range(3)]
    return pos + vel


def main():
    rows = []
    for v in V_INF:
        for rp in R_P:
            for (i, o, w) in ORIENT:
                for f in NU_FRAC:
                    rows.append(["%.17g" % x for x in state(v, rp, i, o, w, f)])
    with open(os.path.join(HERE, "states.txt"), "w") as fh:
        fh.write("# id X Y Z (km) VX VY VZ (km/s), EarthMJ2000Eq, generated by make_fixture.py\n")
        for k, r in enumerate(rows, 1):
            fh.write("%d %s\n" % (k, " ".join(r)))

    work = os.path.join(HERE, "_gmat_run")
    os.makedirs(work, exist_ok=True)
    report = os.path.join(work, "report.txt")
    lines = ["Earth.Mu = 398600.4415;"]
    for k, r in enumerate(rows, 1):
        lines.append("Create Spacecraft sc%d;" % k)
        lines.append("sc%d.CoordinateSystem = EarthMJ2000Eq;" % k)
        lines.append("sc%d.DisplayStateType = Cartesian;" % k)
        for name, val in zip(["X", "Y", "Z", "VX", "VY", "VZ"], r):
            lines.append("sc%d.%s = %s;" % (k, name, val))
    lines.append("Create Variable id;")
    lines.append("Create ReportFile rf;")
    lines.append("rf.Filename = '%s';" % report)
    lines.append("rf.Precision = 16;")
    lines.append("rf.WriteHeaders = false;")
    lines.append("rf.LeftJustify = On;")
    lines.append("rf.ZeroFill = Off;")
    lines.append("rf.ColumnWidth = 26;")
    lines.append("BeginMissionSequence;")
    for k in range(1, len(rows) + 1):
        lines.append("id = %d;" % k)
        params = " ".join(
            "sc%d.EarthMJ2000Eq.%s" % (k, p)
            for p in ["BdotT", "BdotR", "BVectorMag", "IncomingRHA", "IncomingDHA",
                      "OutgoingRHA", "OutgoingDHA"])
        lines.append("Report rf id %s;" % params)
    script = os.path.join(HERE, "bplane_grid.script")
    with open(script, "w") as fh:
        fh.write("% Generated by make_fixture.py: GMAT B-plane oracle grid (one statement per line)\n")
        fh.write("\n".join(lines) + "\n")
    gmat = os.environ.get("KSHANA_GMAT")
    if not gmat:
        sys.exit("source ~/Code/kshana-oracles/env.sh first (KSHANA_GMAT)")
    if os.path.exists(report):
        os.remove(report)
    out = subprocess.run([gmat, "--run", script, "--exit"], cwd=os.path.dirname(gmat),
                         capture_output=True, text=True)
    with open(os.path.join(work, "gmat_console.log"), "w") as fh:
        fh.write(out.stdout + out.stderr)
    if not os.path.exists(report):
        sys.exit("GMAT wrote no report; see _gmat_run/gmat_console.log")
    with open(report) as src, open(os.path.join(HERE, "gmat_bplane_report.txt"), "w") as dst:
        dst.write("# GMAT R2026a GmatConsole report for bplane_grid.script: id BdotT BdotR BVectorMag (km) "
                  "IncomingRHA IncomingDHA OutgoingRHA OutgoingDHA (deg), EarthMJ2000Eq\n")
        dst.write(src.read())
    shutil.rmtree(work)


if __name__ == "__main__":
    main()
