#!/usr/bin/env python3
"""Write src/lunar_afs/params.rs: the L1C pilot (L1CP) Weil and insertion indices of
IS-GPS-800J (Navstar GPS Space Segment / User Segment L1C Interface, 1 August 2022), Table 3.2-2
(PRNs 1-63) and Table 6.3-1 (PRNs 64-210). IS-GPS-800 is a US Government interface
specification. LSIS V1.0 Appendix D uses "the same construction as described for the L1C Q
channel" (its footnote 6) and its Tables D-2 to D-6 carry the same 210 (w, p) pairs; this
script reads them from IS-GPS-800J.

Usage: extract_isgps800_l1cp.py IS-GPS-800J.txt OUT.rs
  IS-GPS-800J.txt: `pdftotext -layout` of
  https://www.gps.gov/sites/default/files/2025-07/IS-GPS-800J.pdf
  (SHA-256 c4aad71058a0eba1ba90672e9511566d2d124b49801cfaa42a51c21241815d0a)
"""
import re
import sys

row = re.compile(
    r"^\s*(\d+)\*?\s+(\d+)\s+(\d+)\s+([0-7]{8})\s+([0-7]{8})\s+(\d+)\s+(\d+)\s+([0-7]{8})\s+([0-7]{8})"
)
got, prev = {}, None
for line in open(sys.argv[1], encoding="utf-8"):
    m = row.match(line)
    if not m:
        continue
    prn = int(m.group(1))
    if prev == 37 and prn == 3:  # IS-GPS-800J Table 3.2-2 prints PRN 38 as "3"
        prn = 38
    got.setdefault(prn, (int(m.group(2)), int(m.group(3))))
    prev = prn
assert sorted(k for k in got if 1 <= k <= 210) == list(range(1, 211)), "PRNs 1-210 expected"
rows = "\n".join(f"    ({got[p][0]}, {got[p][1]}), // PRN {p}" for p in range(1, 211))
open(sys.argv[2], "w").write(
    "// SPDX-License-Identifier: AGPL-3.0-only\n"
    "//! L1C pilot (L1CP) Weil index `w` and insertion index `p` for PRNs 1-210, from IS-GPS-800J\n"
    "//! (US Government interface specification, 1 August 2022) Table 3.2-2 and Table 6.3-1.\n"
    "//! LSIS V1.0 builds its AFS-Q primary codes with the same construction and the same\n"
    "//! assignments. Generated by `xval/lunar-afs/extract_isgps800_l1cp.py`; do not edit by hand.\n\n"
    "/// `(w, p)` of PRNs 1 to 210, index `prn - 1`.\n"
    "#[rustfmt::skip]\n"
    f"pub const L1CP_WEIL_INSERTION: [(u16, u16); 210] = [\n{rows}\n];\n"
)
print("wrote", sys.argv[2])
