# SPDX-License-Identifier: AGPL-3.0-only
"""Gravity-gradient torque reference values from Basilisk 2.9.1 (ISC).

Oracle: Basilisk `GravityGradientEffector` attached to a `spacecraft.Spacecraft` hub, with a
point-mass Earth whose mu is set to 3.986004418e14 m^3/s^2 (the value Kshana uses). The torque is
the effector's own `computeForceTorque` evaluated at the hub state set here (no propagation), read
back through its `gravityGradientOutMsg`.

For each altitude and inertia tensor this writes:
  PEAK  the torque magnitude with the body-frame direction to the spacecraft position placed at
        45 deg between the minimum- and maximum-inertia principal axes;
  BOUND the largest torque magnitude over 2000 random attitudes.
The principal moments and axes come from numpy `eigh`; dI = I_max - I_min is the input Kshana takes.

Reproduce:
  source ~/Code/kshana-oracles/env.sh
  $ORACLE_PY gen_attitude_gg_torque_basilisk_oracle.py > attitude_gg_torque_basilisk_oracle.txt
"""

import numpy as np
from Basilisk import __version__ as BSK_VERSION
from Basilisk.simulation import GravityGradientEffector, spacecraft
from Basilisk.utilities import RigidBodyKinematics as rbk
from Basilisk.utilities import SimulationBaseClass, macros, simIncludeGravBody

MU = 3.986004418e14
R_EQ = 6378137.0
ALTS_KM = [300.0, 400.0, 600.0, 800.0, 1200.0]
N_RANDOM = 2000
SEED = 20261001


def random_rotation(rng):
    q = rng.normal(size=4)
    q /= np.linalg.norm(q)
    return np.array(rbk.EP2C(q))


def tensors(rng):
    out = [
        ("diag_10_20_30", np.diag([10.0, 20.0, 30.0])),
        ("diag_100_100_160", np.diag([100.0, 100.0, 160.0])),
        ("diag_850_1200_400", np.diag([850.0, 1200.0, 400.0])),
    ]
    for k in range(5):
        moments = rng.uniform(5.0, 2000.0, size=3)
        rot = random_rotation(rng)
        out.append((f"general_{k}", rot @ np.diag(moments) @ rot.T))
    return out


def dcm_with_first_column(d):
    """A proper rotation [BN] whose first column is d (so [BN] x_N = d)."""
    d = d / np.linalg.norm(d)
    helper = np.array([0.0, 0.0, 1.0]) if abs(d[2]) < 0.9 else np.array([1.0, 0.0, 0.0])
    b = np.cross(d, helper)
    b /= np.linalg.norm(b)
    c = np.cross(d, b)
    return np.column_stack([d, b, c])


class GgSim:
    def __init__(self, inertia, r):
        self.sim = SimulationBaseClass.SimBaseClass()
        proc = self.sim.CreateNewProcess("p")
        proc.addTask(self.sim.CreateNewTask("t", macros.sec2nano(1.0)))
        self.sc = spacecraft.Spacecraft()
        self.sc.ModelTag = "sc"
        self.sc.hub.mHub = 100.0
        self.sc.hub.IHubPntBc_B = inertia.tolist()
        grav = simIncludeGravBody.gravBodyFactory()
        earth = grav.createEarth()
        earth.isCentralBody = True
        earth.mu = MU
        grav.addBodiesTo(self.sc)
        self.gg = GravityGradientEffector.GravityGradientEffector()
        self.gg.ModelTag = "gg"
        self.gg.addPlanetName(earth.planetName)
        self.sc.addDynamicEffector(self.gg)
        self.sim.AddModelToTask("t", self.sc)
        self.sim.AddModelToTask("t", self.gg)
        self.sc.hub.r_CN_NInit = [r, 0.0, 0.0]
        self.sc.hub.v_CN_NInit = [0.0, 0.0, 0.0]
        self.sc.hub.sigma_BNInit = [0.0, 0.0, 0.0]
        self.sc.hub.omega_BN_BInit = [0.0, 0.0, 0.0]
        self.sim.InitializeSimulation()
        self.sigma = self.sc.dynManager.getStateObject(self.sc.hub.nameOfHubSigma)

    def torque(self, bn):
        s = np.array(rbk.C2MRP(np.asarray(bn))).ravel()
        self.sigma.setState([[s[0]], [s[1]], [s[2]]])
        self.gg.computeForceTorque(0.0, 0.0)
        self.gg.WriteOutputMessages(0)
        return np.array(self.gg.gravityGradientOutMsg.read().gravityGradientTorque_B)


def main():
    rng = np.random.default_rng(SEED)
    tens = tensors(rng)
    print(f"# Gravity-gradient torque from Basilisk {BSK_VERSION} GravityGradientEffector (ISC).")
    print("# Generated by gen_attitude_gg_torque_basilisk_oracle.py; see its docstring and NOTICE.md.")
    print(f"# mu = {MU:.10e} m^3/s^2, r = {R_EQ:.1f} m + altitude, random attitudes per case = {N_RANDOM}, seed {SEED}.")
    print("# TENSOR id | Ixx Iyy Izz Ixy Ixz Iyz (kg m^2)")
    print("# CASE id | altitude_km | dI_kg_m2 | peak_torque_Nm | bound_max_torque_Nm")
    for name, inertia in tens:
        i = inertia
        print(f"TENSOR {name} | {i[0,0]:.17e} {i[1,1]:.17e} {i[2,2]:.17e} {i[0,1]:.17e} {i[0,2]:.17e} {i[1,2]:.17e}")
    for alt in ALTS_KM:
        r = R_EQ + alt * 1e3
        for name, inertia in tens:
            w, v = np.linalg.eigh(inertia)
            d_inertia = w[-1] - w[0]
            d45 = (v[:, 0] + v[:, -1]) / np.sqrt(2.0)
            sim = GgSim(inertia, r)
            peak = np.linalg.norm(sim.torque(dcm_with_first_column(d45)))
            bound = 0.0
            for _ in range(N_RANDOM):
                bound = max(bound, np.linalg.norm(sim.torque(random_rotation(rng))))
            print(f"CASE {name} | {alt:.1f} | {d_inertia:.17e} | {peak:.17e} | {bound:.17e}")


if __name__ == "__main__":
    main()
