#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""SPICE reference for tests/lunar_vlbi_spice_oracle.rs (calls no Kshana code).

For 25 hourly reception epochs from 2024-01-01T00:00 UTC and the DSN stations DSS-14
(Goldstone), DSS-43 (Canberra) and DSS-63 (Madrid), writes the converged Newtonian light time
from a beacon fixed at (1737.4, 0, 0) km in MOON_PA_DE440 to the station, as the NAIF SPICE
Toolkit solves it:

    spkcpt(trgpos, 'MOON', 'MOON_PA_DE440', et, 'J2000', 'OBSERVER', 'CN', 'DSS-nn')

plus the partials of that light time with respect to the beacon's body-fixed position and the
station's ITRF93 position, each a five-point central difference (h = 500 km) of SPICE light
times. Beacon offsets go into `trgpos`; station offsets go through

    spkcpo(BEACON, et, 'J2000', 'OBSERVER', 'CN', obspos, 'EARTH', 'ITRF93')

with the beacon written here as a constant-position SPK type 8 object relative to MOON in
MOON_PA_DE440 (a scratch file deleted afterwards). The script aborts if the two routes differ by
more than 1e-12 s at zero offset.

Output: spice_light_times.csv beside this script, one row per (epoch, station):
    hour,et_s,station,x_m,y_m,z_m,lt_s,dlt_dbx,dlt_dby,dlt_dbz,dlt_dsx,dlt_dsy,dlt_dsz
station 0 = DSS-14, 1 = DSS-43, 2 = DSS-63; x,y,z the station's ITRF93 position at et
(spkpos, 'NONE', relative to EARTH); dlt_db* in s/m along the MOON_PA_DE440 axes; dlt_ds* in
s/m along ITRF93.

With `--epochs j2000` (round 2 amendment 3) the 25 epochs run hourly from 2000-01-01T06:00 to
2000-01-02T06:00 UTC instead, where SPICE's double ET resolves the emission epoch, and the
output is spice_light_times_j2000.csv.

    source "$KSHANA_ORACLES/env.sh"
    $ORACLE_PY tests/fixtures/lunar_vlbi_spice_oracle/generate_lunar_vlbi_spice_oracle.py
    $ORACLE_PY tests/fixtures/lunar_vlbi_spice_oracle/generate_lunar_vlbi_spice_oracle.py --epochs j2000
"""

import hashlib
import os
import pathlib
import sys
import tempfile

import spiceypy as sp

HERE = pathlib.Path(__file__).resolve().parent
NAIF = pathlib.Path(os.environ["KSHANA_ORACLES"]) / "data" / "naif"
KERNELS = [
    "naif0012.tls",
    "de440s.bsp",
    "moon_pa_de440_200625.bpc",
    "moon_de440_250416.tf",
    "earth_latest_high_prec.bpc",
    "earthstns_itrf93_260814.bsp",
]
STATIONS = ["DSS-14", "DSS-43", "DSS-63"]
BEACON_KM = [1737.4, 0.0, 0.0]
BEACON_ID = 301900
H_KM = 500.0
STENCIL = [(-2.0, 1.0), (-1.0, -8.0), (1.0, 8.0), (2.0, -1.0)]


J2000_SET = sys.argv[1:] == ["--epochs", "j2000"]
OUTPUT = "spice_light_times_j2000.csv" if J2000_SET else "spice_light_times.csv"


def utc(hour):
    if J2000_SET:
        h = hour + 6
        return "2000-01-%02dT%02d:00:00" % (1 + h // 24, h % 24)
    return "2024-01-02T00:00:00" if hour == 24 else "2024-01-01T%02d:00:00" % hour


def lt_beacon_offset(et, station, off_km):
    pos = [BEACON_KM[i] + off_km[i] for i in range(3)]
    _, lt = sp.spkcpt(pos, "MOON", "MOON_PA_DE440", et, "J2000", "OBSERVER", "CN", station)
    return lt


def lt_station_offset(et, obspos_km):
    _, lt = sp.spkcpo(str(BEACON_ID), et, "J2000", "OBSERVER", "CN", obspos_km, "EARTH", "ITRF93")
    return lt


def five_point(f):
    out = []
    for axis in range(3):
        acc = 0.0
        for k, w in STENCIL:
            e = [0.0, 0.0, 0.0]
            e[axis] = k * H_KM
            acc += w * f(e)
        # light time in s per km of offset -> s per m
        out.append(acc / (12.0 * H_KM) / 1e3)
    return out


def main():
    for k in KERNELS:
        sp.furnsh(str(NAIF / k))
    ets = [sp.utc2et(utc(h)) for h in range(25)]
    tmp = tempfile.mkdtemp()
    spk = os.path.join(tmp, "beacon.bsp")
    handle = sp.spkopn(spk, "beacon", 0)
    t0, t1 = ets[0] - 86400.0, ets[-1] + 86400.0
    states = [BEACON_KM + [0.0, 0.0, 0.0], BEACON_KM + [0.0, 0.0, 0.0]]
    sp.spkw08(handle, BEACON_ID, 301, "MOON_PA_DE440", t0, t1, "beacon", 1, 2, states, t0,
              t1 - t0)
    sp.spkcls(handle)
    sp.furnsh(spk)

    lines = [
        "# SPICE reference for tests/lunar_vlbi_spice_oracle.rs (generated by %s)"
        % pathlib.Path(__file__).name,
        "# SPICE Toolkit %s through spiceypy %s; light times: spkcpt/spkcpo abcorr CN"
        % (sp.tkvrsn("TOOLKIT"), sp.__version__),
    ]
    for k in KERNELS:
        lines.append("# kernel %s sha256 %s"
                     % (k, hashlib.sha256((NAIF / k).read_bytes()).hexdigest()))
    if J2000_SET:
        lines.append("# epochs: 25 hourly from %s UTC" % utc(0))
    lines.append("# beacon (1737.4, 0, 0) km in MOON_PA_DE440; stations 0 DSS-14, 1 DSS-43, "
                 "2 DSS-63; partials: five-point central difference, h = %.0f km" % H_KM)
    lines.append("hour,et_s,station,x_m,y_m,z_m,lt_s,dlt_dbx,dlt_dby,dlt_dbz,dlt_dsx,dlt_dsy,"
                 "dlt_dsz")
    worst_route = 0.0
    for hour, et in enumerate(ets):
        for si, st in enumerate(STATIONS):
            s_km, _ = sp.spkpos(st, et, "ITRF93", "NONE", "EARTH")
            s_km = [float(x) for x in s_km]
            lt = lt_beacon_offset(et, st, [0.0, 0.0, 0.0])
            lt_po = lt_station_offset(et, s_km)
            worst_route = max(worst_route, abs(lt - lt_po))
            if abs(lt - lt_po) > 1e-12:
                raise SystemExit("spkcpt and spkcpo disagree by %.3e s" % abs(lt - lt_po))
            db = five_point(lambda e: lt_beacon_offset(et, st, e))
            ds = five_point(lambda e: lt_station_offset(
                et, [s_km[i] + e[i] for i in range(3)]))
            vals = [x * 1e3 for x in s_km] + [lt] + db + ds
            lines.append("%d,%s,%d,%s" % (hour, repr(et), si,
                                          ",".join("%.17e" % v for v in vals)))
    lines.insert(len(KERNELS) + (4 if J2000_SET else 3),
                 "# spkcpt vs spkcpo light time at zero offset: worst %.3e s" % worst_route)
    (HERE / OUTPUT).write_text("\n".join(lines) + "\n")
    os.remove(spk)
    os.rmdir(tmp)
    print("wrote %d rows; spkcpt/spkcpo worst %.3e s" % (len(ets) * 3, worst_route))


if __name__ == "__main__":
    main()
