// SPDX-License-Identifier: AGPL-3.0-only
//
// EoCoverageOrekitDriver: Orekit 12.2 (Apache-2.0) as the oracle for the EO (Earth observation)
// payload footprint and coverage geometry row. The comparison and its tolerances are pre-registered
// in tests/eo_payload_coverage_orekit_oracle.rs; this program only computes oracle values on the
// pre-registered grid and prints them. No Kshana code is involved.
//
// Sphere geometry: OneAxisEllipsoid(R_e, f = 0); limb, ray intersections, a nadir-pointing
// CircularFieldOfView footprint, and the Keplerian period. J2 dynamics: Brouwer-Lyddane mean to
// osculating conversion, then a NumericalPropagator with NewtonianAttraction and
// J2OnlyPerturbation and a NodeDetector over >= 15 ascending nodes. WGS-84 limb: OneAxisEllipsoid
// WGS-84 pointOnLimb (geodesic distances are added by geodesic_wgs84.py with GeographicLib).
//
// Compile and run (writes the Orekit part of the fixture to stdout):
//   source ~/Code/kshana-oracles/env.sh
//   javac -cp "$OREKIT_CP" -d /path/to/scratch EoCoverageOrekitDriver.java
//   java -cp "/path/to/scratch:$OREKIT_CP" EoCoverageOrekitDriver > orekit_part.txt

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.hipparchus.geometry.euclidean.threed.Line;
import org.hipparchus.geometry.euclidean.threed.Rotation;
import org.hipparchus.geometry.euclidean.threed.Vector3D;
import org.hipparchus.ode.events.Action;
import org.hipparchus.ode.nonstiff.DormandPrince853Integrator;
import org.orekit.attitudes.FrameAlignedProvider;
import org.orekit.bodies.GeodeticPoint;
import org.orekit.bodies.OneAxisEllipsoid;
import org.orekit.data.DataContext;
import org.orekit.data.DirectoryCrawler;
import org.orekit.forces.gravity.J2OnlyPerturbation;
import org.orekit.forces.gravity.NewtonianAttraction;
import org.orekit.frames.Frame;
import org.orekit.frames.FramesFactory;
import org.orekit.frames.Transform;
import org.orekit.geometry.fov.CircularFieldOfView;
import org.orekit.orbits.CartesianOrbit;
import org.orekit.orbits.KeplerianOrbit;
import org.orekit.orbits.OrbitType;
import org.orekit.orbits.PositionAngleType;
import org.orekit.propagation.PropagationType;
import org.orekit.propagation.SpacecraftState;
import org.orekit.propagation.analytical.BrouwerLyddanePropagator;
import org.orekit.propagation.events.NodeDetector;
import org.orekit.propagation.numerical.NumericalPropagator;
import org.orekit.time.AbsoluteDate;
import org.orekit.time.TimeScalesFactory;

public class EoCoverageOrekitDriver {
    // Kshana's constants (orbit::MU_EARTH, orbit::R_EARTH_EQUATORIAL_M, forces::J2,
    // forces::EARTH_ROTATION_RATE), the pre-registered inputs of the comparison.
    static final double MU = 3.986004418e14;
    static final double RE = 6378137.0;
    static final double J2 = 1.08262668e-3;
    static final double OMEGA_E = 7.2921151467e-5;
    static final double WGS84_F = 1.0 / 298.257223563;

    static final double[] ALTS_KM = {400, 550, 700, 850, 1000, 1200, 1500};
    static final double[] INCS_DEG = {1, 30, 51.6, 70, 90, 98};
    static final double[] HALF_FOVS_DEG = {7.5, 25, 40, 50};
    static final double[] IFOVS_URAD = {10, 14, 50};
    static final double[] SLEWS_DEG = {30, 89};

    static Frame frame;
    static AbsoluteDate t0;

    /** Intersection of the ray from p along dir with the body, as a Cartesian point. */
    static Vector3D hit(OneAxisEllipsoid body, Vector3D p, Vector3D dir) {
        Line line = new Line(p, p.add(dir.scalarMultiply(1.0e6)), 1.0e-12);
        GeodeticPoint gp = body.getIntersectionPoint(line, p, frame, t0);
        if (gp == null) {
            throw new IllegalStateException("ray misses the body");
        }
        return body.transform(gp);
    }

    /** Ray from the satellite on +X at nadir angle eta (rad), in the X-Y plane. */
    static Vector3D ray(double eta) {
        return new Vector3D(-Math.cos(eta), Math.sin(eta), 0.0);
    }

    public static void main(String[] args) {
        String data = System.getenv("OREKIT_DATA");
        DataContext.getDefault().getDataProvidersManager().addProvider(new DirectoryCrawler(new File(data)));
        Locale.setDefault(Locale.ROOT);
        frame = FramesFactory.getEME2000();
        t0 = new AbsoluteDate(2026, 1, 1, 0, 0, 0.0, TimeScalesFactory.getUTC());

        System.out.println("# EO coverage oracle values, Orekit 12.2 (Apache-2.0). Generated by EoCoverageOrekitDriver.java.");
        System.out.printf("# mu %.10e  R_e %.1f  J2 %.10e  omega_E %.13e%n", MU, RE, J2, OMEGA_E);
        System.out.println("# SPHERE h_km | angular_radius_rad | keplerian_period_s");
        System.out.println("# SWATH h_km | half_fov_deg | swath_intersection_m | swath_footprint_mean_m | footprint_min_m | footprint_max_m | footprint_points");
        System.out.println("# GSD h_km | ifov_urad | gsd_m");
        System.out.println("# ACCESS h_km | slew_deg | ground_range_m | method");
        System.out.println("# NODE h_km | i_deg | nodal_period_s | node_spacing_m | n_nodes");
        System.out.println("# WGS h_km | sub_lat_deg | side | limb_angle_deg | geocentric_subpoint_lat lon (deg) | limb_point_lat lon (deg)");

        OneAxisEllipsoid sphere = new OneAxisEllipsoid(RE, 0.0, frame);
        for (double hKm : ALTS_KM) {
            double h = hKm * 1e3;
            Vector3D p = new Vector3D(RE + h, 0.0, 0.0);
            // Angular radius from the limb point in the X-Y plane.
            Vector3D limb = sphere.pointOnLimb(p, new Vector3D(0.0, 1.0e8, 0.0));
            double rho = Vector3D.angle(p.negate(), limb.subtract(p));
            KeplerianOrbit circ = new KeplerianOrbit(RE + h, 0.0, 0.0, 0.0, 0.0, 0.0, PositionAngleType.MEAN, frame, t0, MU);
            System.out.printf("SPHERE %.1f | %.17e | %.17e%n", hKm, rho, circ.getKeplerianPeriod());

            for (double fov : HALF_FOVS_DEG) {
                double eta = Math.toRadians(fov);
                Vector3D q = hit(sphere, p, ray(eta));
                double swath = 2.0 * RE * Vector3D.angle(p, q);
                // Footprint of a nadir-pointing circular field of view (boresight +Z of the FOV frame).
                CircularFieldOfView cfov = new CircularFieldOfView(Vector3D.PLUS_K, eta, 0.0);
                Transform rot = new Transform(t0, new Rotation(Vector3D.PLUS_K, Vector3D.MINUS_I));
                Transform tr = new Transform(t0, p);
                Transform fovToBody = new Transform(t0, rot, tr);
                Vector3D chkO = fovToBody.transformPosition(Vector3D.ZERO);
                Vector3D chkB = fovToBody.transformVector(Vector3D.PLUS_K);
                if (chkO.distance(p) > 1e-6 || chkB.distance(Vector3D.MINUS_I) > 1e-12) {
                    throw new IllegalStateException("fovToBody transform convention check failed: " + chkO + " " + chkB);
                }
                List<List<GeodeticPoint>> fp = cfov.getFootprint(fovToBody, sphere, Math.toRadians(1.0));
                double sum = 0.0, mn = Double.MAX_VALUE, mx = 0.0;
                int count = 0;
                for (List<GeodeticPoint> loop : fp) {
                    for (GeodeticPoint gp : loop) {
                        double arc = 2.0 * RE * Vector3D.angle(p, sphere.transform(gp));
                        sum += arc;
                        mn = Math.min(mn, arc);
                        mx = Math.max(mx, arc);
                        count++;
                    }
                }
                System.out.printf("SWATH %.1f | %.1f | %.17e | %.17e | %.17e | %.17e | %d%n", hKm, fov, swath, sum / count, mn, mx, count);
            }
            for (double ifov : IFOVS_URAD) {
                double half = 0.5 * ifov * 1e-6;
                Vector3D a = hit(sphere, p, ray(half));
                Vector3D b = hit(sphere, p, ray(-half));
                System.out.printf("GSD %.1f | %.1f | %.17e%n", hKm, ifov, RE * Vector3D.angle(a, b));
            }
            for (double slew : SLEWS_DEG) {
                double eta = Math.toRadians(slew);
                if (eta < rho) {
                    Vector3D q = hit(sphere, p, ray(eta));
                    System.out.printf("ACCESS %.1f | %.1f | %.17e | intersection%n", hKm, slew, RE * Vector3D.angle(p, q));
                } else {
                    System.out.printf("ACCESS %.1f | %.1f | %.17e | limb%n", hKm, slew, RE * Vector3D.angle(p, limb));
                }
            }
        }

        // J2 dynamics: node spacing and nodal period.
        for (double hKm : ALTS_KM) {
            for (double iDeg : INCS_DEG) {
                double a = RE + hKm * 1e3;
                KeplerianOrbit mean = new KeplerianOrbit(a, 1.0e-3, Math.toRadians(iDeg), 0.0, 0.0,
                        Math.toRadians(-30.0), PositionAngleType.MEAN, frame, t0, MU);
                BrouwerLyddanePropagator bl = new BrouwerLyddanePropagator(mean, new FrameAlignedProvider(frame),
                        1000.0, RE, MU, -J2, 0.0, 0.0, 0.0, PropagationType.MEAN, 0.0);
                SpacecraftState osc = bl.propagate(t0);
                CartesianOrbit start = new CartesianOrbit(osc.getPVCoordinates(frame), frame, t0, MU);
                double[][] tol = NumericalPropagator.tolerances(1e-6, start, OrbitType.CARTESIAN);
                DormandPrince853Integrator integ = new DormandPrince853Integrator(1e-3, 300.0, tol[0], tol[1]);
                NumericalPropagator np = new NumericalPropagator(integ);
                np.setOrbitType(OrbitType.CARTESIAN);
                np.addForceModel(new NewtonianAttraction(MU));
                np.addForceModel(new J2OnlyPerturbation(MU, RE, J2, frame));
                np.setInitialState(new SpacecraftState(start));
                final List<double[]> nodes = new ArrayList<>();
                NodeDetector nd = new NodeDetector(start, frame).withHandler((s, d, inc) -> {
                    Vector3D r = s.getPVCoordinates(frame).getPosition();
                    Vector3D v = s.getPVCoordinates(frame).getVelocity();
                    if (v.getZ() > 0.0) {
                        nodes.add(new double[] {s.getDate().durationFrom(t0), Math.atan2(r.getY(), r.getX())});
                    }
                    return Action.CONTINUE;
                });
                np.addEventDetector(nd);
                double period = 2.0 * Math.PI * Math.sqrt(a * a * a / MU);
                np.propagate(t0.shiftedBy(15.6 * period));
                int m = nodes.size();
                if (m < 15) {
                    throw new IllegalStateException("only " + m + " ascending nodes at h " + hKm + " i " + iDeg);
                }
                double[] lam = new double[m];
                double prev = 0.0;
                for (int k = 0; k < m; k++) {
                    double l = nodes.get(k)[1] - OMEGA_E * nodes.get(k)[0];
                    if (k > 0) {
                        while (l - prev > Math.PI) l -= 2.0 * Math.PI;
                        while (l - prev < -Math.PI) l += 2.0 * Math.PI;
                    }
                    lam[k] = l;
                    prev = l;
                }
                double sk = 0, st = 0, sl = 0, skk = 0, skt = 0, skl = 0;
                for (int k = 0; k < m; k++) {
                    sk += k; skk += (double) k * k;
                    st += nodes.get(k)[0]; sl += lam[k];
                    skt += k * nodes.get(k)[0]; skl += k * lam[k];
                }
                double den = m * skk - sk * sk;
                double slopeT = (m * skt - sk * st) / den;
                double slopeL = (m * skl - sk * sl) / den;
                System.out.printf("NODE %.1f | %.1f | %.17e | %.17e | %d%n", hKm, iDeg, slopeT, RE * Math.abs(slopeL), m);
            }
        }

        // WGS-84 limb.
        OneAxisEllipsoid wgs = new OneAxisEllipsoid(RE, WGS84_F, frame);
        for (double hKm : ALTS_KM) {
            Object[][] geoms = {
                {0.0, "north", new Vector3D(0, 0, 1e9)},
                {0.0, "east", new Vector3D(0, 1e9, 0)},
                {45.0, "north", new Vector3D(0, 0, 1e9)},
                {45.0, "south", new Vector3D(0, 0, -1e9)},
                {90.0, "lon0", new Vector3D(1e9, 0, 0)},
            };
            for (Object[] g : geoms) {
                double lat = (Double) g[0];
                Vector3D p = wgs.transform(new GeodeticPoint(Math.toRadians(lat), 0.0, hKm * 1e3));
                Vector3D limb = wgs.pointOnLimb(p, (Vector3D) g[2]);
                double ang = Math.toDegrees(Vector3D.angle(p.negate(), limb.subtract(p)));
                GeodeticPoint sub = wgs.getIntersectionPoint(new Line(p, Vector3D.ZERO, 1e-12), p, frame, t0);
                GeodeticPoint lp = wgs.transform(limb, frame, t0);
                System.out.printf("WGS %.1f | %.1f | %s | %.17e | %.15f %.15f | %.15f %.15f%n", hKm, lat, g[1], ang,
                        Math.toDegrees(sub.getLatitude()), Math.toDegrees(sub.getLongitude()),
                        Math.toDegrees(lp.getLatitude()), Math.toDegrees(lp.getLongitude()));
            }
        }
    }
}
