// SPDX-License-Identifier: AGPL-3.0-only
//! Oracle for a NEW matrix row, "Lag-1 autocorrelation power-law noise identification"
//! (`allan::lag1_noise_id`, package D9 of the dominance roadmap).
//!
//! PRE-REGISTRATION (written 2026-10-02, committed and pushed before the oracle was installed
//! or run and before the fixture was generated; engine commit 52a931b2).
//!
//! QUANTITY. For a phase or fractional-frequency record and an averaging factor `af`: the
//! identified integer power-law exponent `alpha_int` (+2 white phase modulation down to -2
//! random-walk frequency modulation), the unrounded `alpha`, the number of differences `d`
//! and `rho = r1/(1+r1)`, by the lag-1 autocorrelation method of W. J. Riley and C. A.
//! Greenhall, "Power law noise identification using the lag 1 autocorrelation", Proc. 18th
//! European Frequency and Time Forum, 2004 (NIST SP 1065 §5.2), with `dmin = 0`, `dmax = 2`.
//!
//! INPUTS. Ten synthetic phase records of 2048 samples at tau0 = 1 s, generated by
//! `tests/fixtures/clock_library_lag1_noise_id_allantools/generate.py` with the Kasdin
//! power-law generator of allantools (`allantools.noise_kasdin.Noise`, qd = 1e-20) for phase
//! power-spectral exponents b = 0, -1, -2, -3, -4 (white phase, flicker phase, white FM,
//! flicker FM, random-walk FM; alpha = b + 2) with numpy seeds 1 and 2, committed in
//! `records.txt`. Cases: every record as PHASE data at af = 1, 2, 4, 8, 16, 32, 64, and its
//! first difference (fractional frequency) as FREQUENCY data at the same factors; every case
//! has at least 30 decimated samples (the oracle refuses fewer).
//!
//! ORACLE (Library). allantools 2024.6 (A. Wallin and contributors, LGPL-3.0-or-later, run as a
//! separate program by the generator), `allantools.autocorr_noise_id(x, af, data_type,
//! dmin=0, dmax=2)`, an independent implementation of the same published algorithm; its
//! outputs are written to `oracle.txt` by the generator. The quantity is uniquely defined by
//! the algorithm and its stated conventions (quadratic detrend of decimated phase, linear
//! detrend of group-averaged frequency, half-to-even rounding), which both sides follow.
//!
//! TOLERANCE (fixed now). `alpha_int` and `d` identical in every case; `|alpha - alpha_ref| <=
//! 1e-9` and `|rho - rho_ref| <= 1e-9` (absolute; alpha lies in [-6, 2]). Source of the bound:
//! both sides evaluate the same deterministic double-precision expressions; they differ only in
//! the least-squares solver of the detrend (numpy `polyfit` by SVD, singular value
//! decomposition, against Kshana's normal equations on a centred, scaled index), whose
//! round-off on these record lengths is expected below 1e-12; 1e-9 leaves three orders of
//! margin and is still far below the 0.5 that would change an identification.
//!
//! VERDICT: not yet run.

use kshana::allan::{lag1_noise_id, Lag1DataType};

const DIR: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/clock_library_lag1_noise_id_allantools"
);
const TOL: f64 = 1e-9;

fn records() -> Vec<(String, Vec<f64>)> {
    let text = std::fs::read_to_string(format!("{DIR}/records.txt")).expect("records.txt");
    let mut out: Vec<(String, Vec<f64>)> = Vec::new();
    for l in text
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
    {
        if let Some(name) = l.strip_prefix('@') {
            out.push((name.trim().to_string(), Vec::new()));
        } else {
            out.last_mut()
                .expect("record header")
                .1
                .push(l.trim().parse().expect("sample"));
        }
    }
    out
}

struct Case {
    record: String,
    dtype: Lag1DataType,
    af: usize,
    alpha_int: i32,
    alpha: f64,
    d: usize,
    rho: f64,
}

fn oracle() -> Vec<Case> {
    let text = std::fs::read_to_string(format!("{DIR}/oracle.txt")).expect("oracle.txt");
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| {
            let f: Vec<&str> = l.split_whitespace().collect();
            Case {
                record: f[0].to_string(),
                dtype: if f[1] == "phase" {
                    Lag1DataType::Phase
                } else {
                    Lag1DataType::Frequency
                },
                af: f[2].parse().unwrap(),
                alpha_int: f[3].parse().unwrap(),
                alpha: f[4].parse().unwrap(),
                d: f[5].parse().unwrap(),
                rho: f[6].parse().unwrap(),
            }
        })
        .collect()
}

#[test]
#[ignore = "pre-registered; not yet run"]
fn lag1_noise_id_matches_allantools() {
    let recs = records();
    let cases = oracle();
    assert_eq!(recs.len(), 10);
    assert_eq!(cases.len(), 140);
    let (mut worst_a, mut worst_r) = (0.0f64, 0.0f64);
    let mut mismatches = Vec::new();
    for c in &cases {
        let x = &recs.iter().find(|r| r.0 == c.record).expect("record").1;
        let data: Vec<f64> = match c.dtype {
            Lag1DataType::Phase => x.clone(),
            Lag1DataType::Frequency => x.windows(2).map(|w| w[1] - w[0]).collect(),
        };
        let got = lag1_noise_id(&data, c.af, c.dtype, 0, 2).expect("identification");
        worst_a = worst_a.max((got.alpha - c.alpha).abs());
        worst_r = worst_r.max((got.rho - c.rho).abs());
        if got.alpha_int != c.alpha_int
            || got.d != c.d
            || (got.alpha - c.alpha).abs() > TOL
            || (got.rho - c.rho).abs() > TOL
        {
            mismatches.push(format!(
                "{} {:?} af={}: kshana ({}, {:.12}, {}, {:.12}) allantools ({}, {:.12}, {}, {:.12})",
                c.record, c.dtype, c.af, got.alpha_int, got.alpha, got.d, got.rho, c.alpha_int,
                c.alpha, c.d, c.rho
            ));
        }
    }
    println!(
        "lag-1 noise id: {} cases, worst |d alpha| {worst_a:.3e}, worst |d rho| {worst_r:.3e}",
        cases.len()
    );
    assert!(mismatches.is_empty(), "{mismatches:#?}");
}
