// SPDX-License-Identifier: AGPL-3.0-only
//! Signal matrix: scene → acquire → track, end to end, for every signal the scene generator
//! supports (`iq::signals`, the eleven names `kshana iq scene --signal` accepts).
//!
//! For each signal one satellite is generated by [`kshana::iq::scene`] (range profile,
//! thermal noise, no navigation data, nominal C/N0 45 dB-Hz), acquired by
//! [`kshana::iq::acq::acquire`] with the engine's default hand-off search (Amendment v3: the
//! auto coherent length and `default_step_hz`; the bars below were fixed for one coherent
//! period) and tracked over the whole scene by [`kshana::iq::track::replay`] with the default
//! loop design (the built-in design: FLL-assisted 2nd-order 15 Hz Costas PLL, carrier-aided
//! 1st-order 2 Hz early-minus-late power DLL, 0.5-chip spacing, 1-period integration, with
//! the PLL and FLL bandwidths clamped to `Bn·T <= 0.1` above a 4 ms update). Only the number of C/N0 windows is
//! reduced (10 instead of 50, each the default 20 periods) so that the estimate settles
//! inside these short scenes.
//!
//! **Sample rates** are about 2.4× the chip rate (4.9× for the BOC signals) and are not
//! commensurate with it (W1's finding on PR #45: a commensurate rate makes the code phase
//! revisit the same sample offsets), while still holding a whole number of samples per
//! primary code period, which `iq::acq` needs.
//!
//! **Replicas.** Signals with a secondary (overlay) code (GPS L5-I/Q, Galileo E1-C and
//! E5a-I/Q) are acquired and tracked with the primary-only replica
//! ([`SignalCode::primary_only`]): the secondary chips then appear as sign flips of the
//! prompt from one primary period to the next, which the Costas PLL and the
//! decision-directed FLL tolerate. The secondary code itself is checked from those flips
//! (bar T6). GPS L2C is acquired and tracked on its CM component alone: a 20 ms replica
//! of the time-multiplexed chip stream with the CL slots zeroed, built from the public
//! `gps::l2c_cm` code. CM carries half the L2C power, so the expected C/N0 on the CM
//! replica is 45 − 3.01 dB.
//!
//! The full-tiered-period acquisition that `kshana iq track --signal …` performs for these
//! signals is a separate question (gap-analysis D4) and is not exercised here.
//!
//! # Pre-registered bars (fixed before the first run, 2026-10-07)
//!
//! Let `T` be the primary (or CM) period, `Δs = chip_rate / fs` one sample in chips, and the
//! scoring window the second half of the tracking epochs (never earlier than 0.3 s).
//!
//! * **A1** acquired: statistic above the threshold at a grid false-alarm probability of
//!   1e-3 (as pre-registered: one coherent period, no non-coherent sums, Doppler search
//!   ±2 kHz at a step of `2/(3T)`; the harness now searches as in Amendment v3 below, with the
//!   bars unchanged).
//! * **A2** Doppler: `|f̂ − f| ≤ step/2 + 1 Hz`.
//! * **A3** code phase (modulo the replica length): `|φ̂ − φ| ≤ Δs` (one sample).
//! * **T1** carrier lock: over the scoring window the mean per-epoch phase lock indicator
//!   `cos 2φ = (I² − Q²)/(I² + Q²)` is at least 0.8, and at least 95 % of epochs have
//!   `cos 2φ ≥ 0.5` (|phase error modulo π| below 30°).
//! * **T2** code tracking: RMS of the replica code phase minus the truth code phase over the
//!   scoring window at most 0.1 chip.
//! * **T3** frequency: mean tracked Doppler over the scoring window within 2 Hz of the truth.
//! * **T4** C/N0: the moments (M2M4) estimate on the engine's prompts over the scoring window
//!   (Pauluzzi & Beaulieu, IEEE Trans. Commun. 48(10), 2000; insensitive to sign flips)
//!   within ±1.5 dB of the expected value (45 dB-Hz; 41.99 dB-Hz on the L2 CM replica).
//! * **T5** for replicas without a secondary code: the engine's own NWPR estimate at the last
//!   epoch within the same ±1.5 dB band. (With the primary-only replica of a tiered code an
//!   NWPR window straddles secondary-chip flips, so the engine's estimate is not defined
//!   there; T4 covers those signals.)
//! * **T6** for tiered codes: over the scoring window, the signs of the prompt's in-phase
//!   part agree with the secondary code, at the best cyclic shift and up to the Costas
//!   180° ambiguity, on at least 99 % of primary periods.
//!
//! A signal that fails a bar is a finding: it is reported with its numbers, kept out of the
//! default test set with `#[ignore = "FINDING …"]`, and the bar is not changed.
//!
//! # Amendment v2 (2026-10-07, after run 1; harness only, bars unchanged)
//!
//! Run 1 used one coherent acquisition period for every signal and an NWPR window of
//! 5 periods × 10 windows. Two of its misses came from that harness, not from the engine:
//! * Galileo E5a-I was not acquired (statistic 27.8 against threshold 38.0): with the
//!   primary-only replica, the single 1 ms block straddled a secondary-code (NH20) sign
//!   flip at this code phase. **(a)** Tiered codes are now acquired with 4 non-coherent
//!   1-period blocks (`AcqConfig::noncoherent = 4`), so that flips straddle at most some
//!   of them.
//! * The 5-period NWPR window missed T5 on BeiDou B1I (46.57 dB-Hz, +1.57) and B1C
//!   (41.77 dB-Hz, −3.2; 10 ms prompts at high per-prompt SNR) while the M2M4 estimate was
//!   in band (44.64, 43.62). **(b)** T5 now uses the engine's default window of 20 periods
//!   (10 windows), and scenes are lengthened so that it settles (Galileo E1 1.5 s, BeiDou
//!   B1C 2.5 s, GPS L2C 4.5 s).
//!
//! The engine findings are kept as ignored tests, with their run-2 numbers: **D8** (default
//! acquisition step against the decision-directed FLL pull-in: Galileo E1-B and E1-C),
//! **D9** (GPS L2C CM at 20 ms integration with the default loop) and **D10** (BeiDou B1C
//! below nominal C/N0). The fix for each must un-ignore its test. `galileo_e1b_on_grid_doppler`
//! is the D8 control: the same E1-B scene with a zero acquisition residual passes every bar
//! (run 1 with a 1.0 s scene measured it 43.42 dB-Hz; run 2 with 1.5 s, 44.41 dB-Hz).

//! # Amendment v3 (2026-10-08, after run 2; harness only, bars unchanged)
//!
//! D8 and D9 changed the engine's defaults (the acquisition step, and the loop bandwidths
//! above a 4 ms update), and the matrix now acquires and tracks the way the engine does by
//! default. No bar changed; every bar A1–A3 and T1–T6 is as pre-registered above.
//!
//! * **Search.** The coherent length is `auto_coherent_periods` of the FULL code period (4
//!   periods for the 1 ms codes, 1 for 4 ms and longer) and the Doppler step is
//!   `acq::default_step_hz` for the one-period loop update the track runs at, instead of the
//!   one-period `2/(3T)` step of v1 and v2.
//! * **Replicas.** Tiered codes whose full period is at most 25 ms (GPS L5-I/Q and Galileo
//!   E5a-I, 20 ms) are acquired with their FULL tiered replica, one coherent block and no
//!   non-coherent sums, as `iq track` does; the code phase is taken modulo the primary length
//!   for the tracker, which still runs on the primary-only replica.
//! * **Exception (D12).** The 100 ms tiered codes (Galileo E1-C and E5a-Q) keep the
//!   primary-only replica with the four non-coherent blocks of v2 (a): the default search on a
//!   100 ms full period keeps the whole Doppler × code-phase grid, about 2.4 GB for E1-C and
//!   12 GB for E5a-Q at 25 MS/s, plus minutes of FFT time.
//! * **Loops.** `Design::builtin_default().loop_config_for(period)` (the D9 clamp), with the
//!   harness's 10 C/N0 windows, instead of `LoopConfig::default()`.
//! * `gps_l2c` (T5) and `beidou_b1c` stay ignored findings with the causes in their `ignore`
//!   texts (D10: an estimator limit under PLL jitter, and BOC band-limiting at 5 MS/s).

use kshana::iq::acq::{acquire, auto_coherent_periods, default_step_hz, AcqConfig};
use kshana::iq::scene::{
    NavData, RangeProfile, SatGeometry, Scene, SceneConfig, SceneSatellite, TruthRecord,
};
use kshana::iq::signals::{beidou, galileo, glonass, gps, Modulation, SignalCode};
use kshana::iq::track::design::Design;
use kshana::iq::track::{replay, ChannelInit, EpochOutput};
use kshana::iq::{Cf64, SampleSpec, SpreadingCode, VecSink, VecSource, C_M_PER_S};
use std::sync::Arc;

const CN0_DBHZ: f64 = 45.0;
const DOPPLER_HZ: f64 = 1250.0;
const SEED: u64 = 35;

/// One row of the matrix.
struct Case {
    /// The `--signal` name.
    signal: &'static str,
    /// The code the scene transmits.
    tx: SignalCode,
    /// The replica the receiver acquires and tracks.
    rx: SignalCode,
    /// Secondary code the primary-only replica leaves on the prompts (empty: none).
    secondary: Vec<i8>,
    /// Complex sample rate (Hz).
    fs_hz: f64,
    /// Scene length (s).
    duration_s: f64,
    /// Expected C/N0 on the replica (dB-Hz).
    expected_cn0_dbhz: f64,
    /// Injected Doppler (Hz).
    doppler_hz: f64,
}

/// A tiered code's primary-only replica, with the secondary chips it leaves on the prompts.
fn tiered(signal: &'static str, tx: SignalCode, fs_hz: f64, duration_s: f64) -> Case {
    let secondary = tx.secondary().to_vec();
    assert!(secondary.len() > 1, "{signal} has no secondary code");
    Case {
        signal,
        rx: tx.primary_only(),
        tx,
        secondary,
        fs_hz,
        duration_s,
        expected_cn0_dbhz: CN0_DBHZ,
        doppler_hz: DOPPLER_HZ,
    }
}

/// A code without a secondary code, tracked as transmitted.
fn plain(signal: &'static str, tx: SignalCode, fs_hz: f64, duration_s: f64) -> Case {
    assert_eq!(tx.secondary().len(), 1, "{signal} has a secondary code");
    Case {
        signal,
        rx: tx.clone(),
        tx,
        secondary: Vec::new(),
        fs_hz,
        duration_s,
        expected_cn0_dbhz: CN0_DBHZ,
        doppler_hz: DOPPLER_HZ,
    }
}

/// GPS L2C: the receiver uses the CM code alone, on the 1.023 Mchip/s multiplex grid with the
/// CL slots zeroed (one CM period, 20 ms).
fn l2c_cm_case(prn: u16) -> Case {
    let tx = gps::l2c(prn).unwrap();
    let cm = gps::l2c_cm(prn).unwrap();
    let mut chips = Vec::with_capacity(2 * cm.len_chips());
    for k in 0..cm.len_chips() as i64 {
        chips.push(cm.chip(k) as i8);
        chips.push(0);
    }
    // The multiplex carries CM in the even slots (tests/iq_signals.rs pins the layout).
    for k in [0i64, 1, 5_000, 10_229] {
        assert_eq!(tx.chip(2 * k), cm.chip(k));
    }
    let rx = SignalCode::new(
        format!("GPS L2 CM PRN {prn} (CL slots zeroed)"),
        tx.chip_rate_hz(),
        tx.carrier_hz(),
        chips,
        Vec::new(),
        Modulation::Bpsk,
    );
    Case {
        signal: "gps-l2c",
        tx,
        rx,
        secondary: Vec::new(),
        fs_hz: 2.5e6,
        duration_s: 4.5,
        expected_cn0_dbhz: CN0_DBHZ - 10.0 * 2f64.log10(),
        doppler_hz: DOPPLER_HZ,
    }
}

/// What one run measured.
struct Outcome {
    acquired: bool,
    statistic: f64,
    threshold: f64,
    doppler_err_hz: f64,
    doppler_step_hz: f64,
    code_err_chips: f64,
    sample_chips: f64,
    pli_mean: f64,
    pli_frac_ok: f64,
    code_rms_chips: f64,
    doppler_mean_err_hz: f64,
    cn0_m2m4_dbhz: f64,
    cn0_nwpr_dbhz: Option<f64>,
    secondary_agreement: Option<f64>,
    scored_epochs: usize,
}

impl std::fmt::Display for Outcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "acq {} (stat {:.1} / thr {:.1}), dDoppler {:+.1} Hz (step {:.1}), dcode {:+.3} chip \
             (1 sample {:.3}); over {} epochs: PLI mean {:.3}, >=0.5 on {:.1} %, code RMS {:.4} \
             chip, Doppler {:+.2} Hz, C/N0 M2M4 {:.2} dB-Hz, NWPR {}, secondary {}",
            self.acquired,
            self.statistic,
            self.threshold,
            self.doppler_err_hz,
            self.doppler_step_hz,
            self.code_err_chips,
            self.sample_chips,
            self.scored_epochs,
            self.pli_mean,
            100.0 * self.pli_frac_ok,
            self.code_rms_chips,
            self.doppler_mean_err_hz,
            self.cn0_m2m4_dbhz,
            self.cn0_nwpr_dbhz
                .map_or("n/a".into(), |c| format!("{c:.2} dB-Hz")),
            self.secondary_agreement
                .map_or("n/a".into(), |a| format!("{:.2} %", 100.0 * a)),
        )
    }
}

/// Signed difference `a − b` wrapped into `(−len/2, len/2]`.
fn wrap_diff(a: f64, b: f64, len: f64) -> f64 {
    let d = (a - b).rem_euclid(len);
    if d > len / 2.0 {
        d - len
    } else {
        d
    }
}

/// Truth code phase (chips of the transmitted code) at stream time `t_s`, from the nearest
/// truth record carried forward at the Doppler-scaled chip rate.
fn truth_phase(truth: &[TruthRecord], code: &SignalCode, t_s: f64) -> f64 {
    let r = truth
        .iter()
        .min_by(|a, b| (a.t_s - t_s).abs().total_cmp(&(b.t_s - t_s).abs()))
        .unwrap();
    let rate = code.chip_rate_hz() * (1.0 + r.doppler_hz / code.carrier_hz());
    r.code_phase_chips + rate * (t_s - r.t_s)
}

/// The M2M4 C/N0 (dB-Hz) of complex prompts of integration `t_s`.
fn m2m4_cn0_dbhz(prompts: &[Cf64], t_s: f64) -> f64 {
    let n = prompts.len() as f64;
    let m2 = prompts
        .iter()
        .map(|p| p.re * p.re + p.im * p.im)
        .sum::<f64>()
        / n;
    let m4 = prompts
        .iter()
        .map(|p| (p.re * p.re + p.im * p.im).powi(2))
        .sum::<f64>()
        / n;
    let ps = (2.0 * m2 * m2 - m4).max(0.0).sqrt();
    let pn = m2 - ps;
    10.0 * (ps / pn / t_s).log10()
}

/// Best agreement of the prompt signs with the secondary code over every cyclic shift, up to
/// a global sign.
fn secondary_agreement(epochs: &[EpochOutput], secondary: &[i8]) -> f64 {
    let n = secondary.len();
    let signs: Vec<i8> = epochs
        .iter()
        .map(|e| if e.prompt.re >= 0.0 { 1 } else { -1 })
        .collect();
    (0..n)
        .map(|shift| {
            let same = signs
                .iter()
                .enumerate()
                .filter(|(k, &s)| s == secondary[(k + shift) % n])
                .count() as f64
                / signs.len() as f64;
            same.max(1.0 - same)
        })
        .fold(0.0, f64::max)
}

fn run(case: &Case) -> Outcome {
    let spec = SampleSpec {
        fs_hz: case.fs_hz,
        center_hz: case.tx.carrier_hz(),
        if_hz: 0.0,
    };
    let mut cfg = SceneConfig::new(spec, case.duration_s);
    cfg.seed = SEED;
    cfg.threads = 2;
    let mut scene = Scene::new(cfg).unwrap();
    let lambda = C_M_PER_S / case.tx.carrier_hz();
    scene.add_satellite(SceneSatellite {
        id: 1,
        code: Box::new(case.tx.clone()),
        geometry: SatGeometry::Profile(RangeProfile {
            range_m: 2.1e7,
            range_rate_mps: -case.doppler_hz * lambda,
            range_accel_mps2: 0.0,
            elevation_deg: 45.0,
            azimuth_deg: 0.0,
        }),
        cn0_dbhz: Some(CN0_DBHZ),
        nav: NavData::None,
    });
    let mut sink = VecSink::default();
    let mut truth: Vec<TruthRecord> = Vec::new();
    scene.generate(&mut sink, &mut truth).unwrap();
    let samples = sink.samples;

    // The engine's default hand-off search. A code with a secondary code is acquired with
    // its FULL tiered replica (what `iq track` and the loop designs do), one coherent block of
    // `auto_coherent_periods` of the full period; a plain code is acquired as transmitted.
    // The step is `default_step_hz` for the one-period loop update the track below runs at
    // (the primary period for a tiered code, which the loops track primary-only).
    // Exception: the 100 ms tiered codes (Galileo E1-C, E5a-Q) keep the primary-only replica.
    // The default search on a 100 ms full period keeps the whole Doppler x code-phase grid,
    // about 2.4 GB for E1-C and 12 GB for E5a-Q at 25 MS/s (601 bins), minutes of FFT time and
    // more memory than the test machine has (defect D12, with W1b's grid work).
    let period = case.rx.period_s();
    let tiered = !case.secondary.is_empty();
    let full_replica = tiered && case.tx.period_s() <= 0.025;
    let acq_code: &SignalCode = if full_replica { &case.tx } else { &case.rx };
    let n_coh = auto_coherent_periods(case.tx.period_s());
    let step = default_step_hz(acq_code.period_s(), n_coh, period);
    let acq_cfg = AcqConfig {
        coherent_periods: n_coh,
        // Amendment v2 (a): a primary-only replica of a tiered code sums 4 blocks so a
        // secondary flip cannot sink them all; the full replica contains the secondary code.
        noncoherent: if tiered && !full_replica { 4 } else { 1 },
        doppler_max_hz: 2000.0,
        doppler_step_hz: step,
        pfa: 1e-3,
    };
    let grid = acquire(&samples, &spec, acq_code, &acq_cfg).unwrap();
    let mut r = grid.result.clone();
    let rx_len = case.rx.len_chips() as f64;
    // The tracker's replica is the primary code: the full-code phase modulo its length.
    r.code_phase_chips = r.code_phase_chips.rem_euclid(rx_len);
    let t0 = truth.iter().find(|t| t.t_s == 0.0).unwrap();
    let doppler_err_hz = r.doppler_hz - t0.doppler_hz;
    let code_err_chips = wrap_diff(r.code_phase_chips, t0.code_phase_chips, rx_len);

    // Tracking over the whole scene.
    let rx: Arc<dyn SpreadingCode + Send + Sync> = Arc::new(case.rx.clone());
    let init = ChannelInit::from_acquisition(rx, &r, &spec, 0, None);
    // The engine's default design for this signal (bandwidths clamped to Bn·T <= 0.1 above
    // a 4 ms loop update, D9), with the harness's 10 C/N0 windows.
    let mut loop_cfg = Design::builtin_default().loop_config_for(period);
    loop_cfg.label = case.signal.into();
    loop_cfg.cn0_windows = 10;
    let mut src = VecSource::new(spec, samples);
    let out = replay(&mut src, &[init], &[loop_cfg], None).unwrap();
    let epochs = &out[0].channels[0];

    let first = (epochs.len() / 2).max(
        epochs
            .iter()
            .position(|e| e.sample_index as f64 / case.fs_hz >= 0.3)
            .unwrap_or(epochs.len()),
    );
    let scored = &epochs[first..];
    let n = scored.len() as f64;
    let pli: Vec<f64> = scored
        .iter()
        .map(|e| {
            let (i2, q2) = (e.prompt.re.powi(2), e.prompt.im.powi(2));
            (i2 - q2) / (i2 + q2)
        })
        .collect();
    let code_rms_chips = (scored
        .iter()
        .map(|e| {
            let t = e.sample_index as f64 / case.fs_hz;
            wrap_diff(e.code_phase_chips, truth_phase(&truth, &case.tx, t), rx_len).powi(2)
        })
        .sum::<f64>()
        / n)
        .sqrt();
    let prompts: Vec<Cf64> = scored.iter().map(|e| e.prompt).collect();
    Outcome {
        acquired: r.acquired,
        statistic: r.statistic,
        threshold: r.threshold,
        doppler_err_hz,
        doppler_step_hz: step,
        code_err_chips,
        sample_chips: case.rx.chip_rate_hz() / case.fs_hz,
        pli_mean: pli.iter().sum::<f64>() / n,
        pli_frac_ok: pli.iter().filter(|&&p| p >= 0.5).count() as f64 / n,
        code_rms_chips,
        doppler_mean_err_hz: scored.iter().map(|e| e.doppler_hz).sum::<f64>() / n - t0.doppler_hz,
        cn0_m2m4_dbhz: m2m4_cn0_dbhz(&prompts, scored[0].t_coh_s),
        cn0_nwpr_dbhz: scored.last().and_then(|e| e.cn0_nwpr_dbhz),
        secondary_agreement: (!case.secondary.is_empty())
            .then(|| secondary_agreement(scored, &case.secondary)),
        scored_epochs: scored.len(),
    }
}

/// Run `case` and check every pre-registered bar, failing with every number on a miss.
fn check(case: Case) -> Outcome {
    check_except(case, &[])
}

/// As [`check`], leaving the bars named in `skip` out. Only the D9 test uses it, for the
/// bar (T5) the L2C finding keeps open in `gps_l2c`; no other case skips a bar.
fn check_except(case: Case, skip: &[&str]) -> Outcome {
    let o = run(&case);
    let msg = format!("{} ({}): {o}", case.signal, case.rx.name());
    eprintln!("{msg}");
    let band = |c: f64| (c - case.expected_cn0_dbhz).abs() <= 1.5;
    let mut fails = Vec::new();
    if !o.acquired {
        fails.push("A1");
    }
    if o.doppler_err_hz.abs() > o.doppler_step_hz / 2.0 + 1.0 {
        fails.push("A2");
    }
    if o.code_err_chips.abs() > o.sample_chips {
        fails.push("A3");
    }
    if o.pli_mean < 0.8 || o.pli_frac_ok < 0.95 {
        fails.push("T1");
    }
    if o.code_rms_chips > 0.1 {
        fails.push("T2");
    }
    if o.doppler_mean_err_hz.abs() > 2.0 {
        fails.push("T3");
    }
    if !band(o.cn0_m2m4_dbhz) {
        fails.push("T4");
    }
    if case.secondary.is_empty() && !o.cn0_nwpr_dbhz.is_some_and(band) {
        fails.push("T5");
    }
    if o.secondary_agreement.is_some_and(|a| a < 0.99) {
        fails.push("T6");
    }
    fails.retain(|f| !skip.contains(f));
    assert!(fails.is_empty(), "bars {fails:?} missed: {msg}");
    o
}

#[test]
fn gps_l1ca() {
    check(plain("gps-l1ca", gps::l1ca(3).unwrap(), 2.5e6, 1.0));
}

#[test]
fn gps_l5i() {
    check(tiered("gps-l5i", gps::l5_i5(3).unwrap(), 25e6, 0.6));
}

#[test]
fn gps_l5q() {
    check(tiered("gps-l5q", gps::l5_q5(3).unwrap(), 25e6, 0.6));
}

/// D9 (fixed): at the 20 ms CM period the default design's bandwidths are clamped to
/// Bn·T <= 0.1 (5 Hz PLL and FLL). Pre-registered bars for the fix: acquires and holds
/// phase lock (A1-A3, T1), mean PLI >= 0.9, code RMS (T2), Doppler (T3) and the M2M4 C/N0 (T4)
/// over the scored window, which starts after 2 s of a 4.5 s scene. T5 (NWPR) is not part of
/// this test: see `gps_l2c`.
#[test]
fn gps_l2c_holds_lock_with_the_default_design() {
    let o = check_except(l2c_cm_case(3), &["T5"]);
    assert!(o.pli_mean >= 0.9, "D9 bar: PLI mean {} < 0.9", o.pli_mean);
}

/// The full matrix row for GPS L2C. With D9 fixed it holds lock but misses T5.
#[test]
#[ignore = "FINDING D10 family (found while fixing D9): GPS L2C CM at T = 20 ms holds lock with \
            the default design (PLI 0.996, Doppler error 0.00 Hz, M2M4 42.71 dB-Hz) but the NWPR \
            C/N0 reads 40.23 dB-Hz against 41.99 (-1.76 dB, T5 band +-1.5); NWPR reads low at \
            high per-prompt C/N0*T, as on BeiDou B1C at 10 ms"]
fn gps_l2c() {
    check(l2c_cm_case(3));
}

/// D8 (fixed): the default acquisition step is capped at 0.2 / T_track (50 Hz here), so the
/// hand-off residual, even when the neighbouring bin wins (50 Hz), is inside the FLL's
/// 62.5 Hz pull-in.
#[test]
fn galileo_e1b() {
    check(plain("galileo-e1b", galileo::e1b(3).unwrap(), 5e6, 1.5));
}

#[test]
fn galileo_e1c() {
    check(tiered("galileo-e1c", galileo::e1c(3).unwrap(), 5e6, 1.5));
}

#[test]
fn galileo_e5a_i() {
    check(tiered(
        "galileo-e5a-i",
        galileo::e5a_i(3).unwrap(),
        25e6,
        0.6,
    ));
}

#[test]
fn galileo_e5a_q() {
    check(tiered(
        "galileo-e5a-q",
        galileo::e5a_q(3).unwrap(),
        25e6,
        0.6,
    ));
}

#[test]
fn beidou_b1i() {
    check(plain("beidou-b1i", beidou::b1i(3).unwrap(), 5e6, 1.0));
}

#[test]
#[ignore = "FINDING D10: BeiDou B1C (BOC(1,1), 10 ms) measures below nominal: engine NWPR \
            42.55 dB-Hz (T5, -2.45 dB), M2M4 43.68 dB-Hz (-1.32 dB, in band); lock, code \
            and Doppler bars pass"]
fn beidou_b1c() {
    check(plain("beidou-b1c", beidou::b1c_data(3).unwrap(), 5e6, 2.5));
}

#[test]
fn glonass_l1of() {
    check(plain(
        "glonass-l1of",
        glonass::l1of(-3).unwrap(),
        1.25e6,
        1.0,
    ));
}

/// Control for D8: Galileo E1-B with the Doppler on the acquisition grid (zero residual, so
/// the D8 false lock cannot occur).
#[test]
fn galileo_e1b_on_grid_doppler() {
    let mut case = plain("galileo-e1b", galileo::e1b(3).unwrap(), 5e6, 1.5);
    case.doppler_hz = 4000.0 / 3.0; // 8 bins of 2/(3 · 4 ms)
    check(case);
}
