// SPDX-License-Identifier: AGPL-3.0-only
//! Signal matrix: scene → acquire → track, end to end, for every signal the scene generator
//! supports (`iq::signals`, the eleven names `kshana iq scene --signal` accepts).
//!
//! For each signal one satellite is generated by [`kshana::iq::scene`] (range profile,
//! thermal noise, no navigation data, nominal C/N0 45 dB-Hz), acquired by
//! [`kshana::iq::acq::acquire`] over the first code period and tracked over the whole scene
//! by [`kshana::iq::track::replay`] with the default loop design ([`LoopConfig::default`]:
//! FLL-assisted 2nd-order 15 Hz Costas PLL, carrier-aided 1st-order 2 Hz early-minus-late
//! power DLL, 0.5-chip spacing, 1-period integration). Only the C/N0 estimator's window
//! (5 periods × 10 windows) is shortened so that it settles inside these short scenes.
//!
//! **Sample rates** are about 2.4× the chip rate (4.9× for the BOC signals) and are not
//! commensurate with it (W1's finding on PR #45: a commensurate rate makes the code phase
//! revisit the same sample offsets), while still holding a whole number of samples per
//! primary code period, which `iq::acq` needs.
//!
//! **Replicas.** Signals with a secondary (overlay) code (GPS L5-I/Q, Galileo E1-C and
//! E5a-I/Q) are acquired and tracked with the primary-only replica
//! ([`SignalCode::primary_only`]): the secondary chips then appear as sign flips of the
//! prompt from one primary period to the next, which the Costas PLL and the
//! decision-directed FLL tolerate. The secondary code itself is checked from those flips
//! (bar T6). GPS L2C is acquired and tracked on its CM component alone: a 20 ms replica
//! of the time-multiplexed chip stream with the CL slots zeroed, built from the public
//! `gps::l2c_cm` code. CM carries half the L2C power, so the expected C/N0 on the CM
//! replica is 45 − 3.01 dB.
//!
//! The full-tiered-period acquisition that `kshana iq track --signal …` performs for these
//! signals is a separate question (gap-analysis D4) and is not exercised here.
//!
//! # Pre-registered bars (fixed before the first run, 2026-10-07)
//!
//! Let `T` be the primary (or CM) period, `Δs = chip_rate / fs` one sample in chips, and the
//! scoring window the second half of the tracking epochs (never earlier than 0.3 s).
//!
//! * **A1** acquired: statistic above the threshold at a grid false-alarm probability of
//!   1e-3 (one coherent period, no non-coherent sums, Doppler search ±2 kHz at a step of
//!   `2/(3T)`).
//! * **A2** Doppler: `|f̂ − f| ≤ step/2 + 1 Hz`.
//! * **A3** code phase (modulo the replica length): `|φ̂ − φ| ≤ Δs` (one sample).
//! * **T1** carrier lock: over the scoring window the mean per-epoch phase lock indicator
//!   `cos 2φ = (I² − Q²)/(I² + Q²)` is at least 0.8, and at least 95 % of epochs have
//!   `cos 2φ ≥ 0.5` (|phase error modulo π| below 30°).
//! * **T2** code tracking: RMS of the replica code phase minus the truth code phase over the
//!   scoring window at most 0.1 chip.
//! * **T3** frequency: mean tracked Doppler over the scoring window within 2 Hz of the truth.
//! * **T4** C/N0: the moments (M2M4) estimate on the engine's prompts over the scoring window
//!   (Pauluzzi & Beaulieu, IEEE Trans. Commun. 48(10), 2000; insensitive to sign flips)
//!   within ±1.5 dB of the expected value (45 dB-Hz; 41.99 dB-Hz on the L2 CM replica).
//! * **T5** for replicas without a secondary code: the engine's own NWPR estimate at the last
//!   epoch within the same ±1.5 dB band. (With the primary-only replica of a tiered code an
//!   NWPR window straddles secondary-chip flips, so the engine's estimate is not defined
//!   there; T4 covers those signals.)
//! * **T6** for tiered codes: over the scoring window, the signs of the prompt's in-phase
//!   part agree with the secondary code, at the best cyclic shift and up to the Costas
//!   180° ambiguity, on at least 99 % of primary periods.
//!
//! A signal that fails a bar is a finding: it is reported with its numbers, kept out of the
//! default test set with `#[ignore = "FINDING …"]`, and the bar is not changed.

use kshana::iq::acq::{acquire, AcqConfig};
use kshana::iq::scene::{
    NavData, RangeProfile, SatGeometry, Scene, SceneConfig, SceneSatellite, TruthRecord,
};
use kshana::iq::signals::{beidou, galileo, glonass, gps, Modulation, SignalCode};
use kshana::iq::track::{replay, ChannelInit, EpochOutput, LoopConfig};
use kshana::iq::{Cf64, SampleSpec, SpreadingCode, VecSink, VecSource, C_M_PER_S};
use std::sync::Arc;

const CN0_DBHZ: f64 = 45.0;
const DOPPLER_HZ: f64 = 1250.0;
const SEED: u64 = 35;

/// One row of the matrix.
struct Case {
    /// The `--signal` name.
    signal: &'static str,
    /// The code the scene transmits.
    tx: SignalCode,
    /// The replica the receiver acquires and tracks.
    rx: SignalCode,
    /// Secondary code the primary-only replica leaves on the prompts (empty: none).
    secondary: Vec<i8>,
    /// Complex sample rate (Hz).
    fs_hz: f64,
    /// Scene length (s).
    duration_s: f64,
    /// Expected C/N0 on the replica (dB-Hz).
    expected_cn0_dbhz: f64,
}

/// A tiered code's primary-only replica, with the secondary chips it leaves on the prompts.
fn tiered(signal: &'static str, tx: SignalCode, fs_hz: f64, duration_s: f64) -> Case {
    let secondary = tx.secondary().to_vec();
    assert!(secondary.len() > 1, "{signal} has no secondary code");
    Case {
        signal,
        rx: tx.primary_only(),
        tx,
        secondary,
        fs_hz,
        duration_s,
        expected_cn0_dbhz: CN0_DBHZ,
    }
}

/// A code without a secondary code, tracked as transmitted.
fn plain(signal: &'static str, tx: SignalCode, fs_hz: f64, duration_s: f64) -> Case {
    assert_eq!(tx.secondary().len(), 1, "{signal} has a secondary code");
    Case {
        signal,
        rx: tx.clone(),
        tx,
        secondary: Vec::new(),
        fs_hz,
        duration_s,
        expected_cn0_dbhz: CN0_DBHZ,
    }
}

/// GPS L2C: the receiver uses the CM code alone, on the 1.023 Mchip/s multiplex grid with the
/// CL slots zeroed (one CM period, 20 ms).
fn l2c_cm_case(prn: u16) -> Case {
    let tx = gps::l2c(prn).unwrap();
    let cm = gps::l2c_cm(prn).unwrap();
    let mut chips = Vec::with_capacity(2 * cm.len_chips());
    for k in 0..cm.len_chips() as i64 {
        chips.push(cm.chip(k) as i8);
        chips.push(0);
    }
    // The multiplex carries CM in the even slots (tests/iq_signals.rs pins the layout).
    for k in [0i64, 1, 5_000, 10_229] {
        assert_eq!(tx.chip(2 * k), cm.chip(k));
    }
    let rx = SignalCode::new(
        format!("GPS L2 CM PRN {prn} (CL slots zeroed)"),
        tx.chip_rate_hz(),
        tx.carrier_hz(),
        chips,
        Vec::new(),
        Modulation::Bpsk,
    );
    Case {
        signal: "gps-l2c",
        tx,
        rx,
        secondary: Vec::new(),
        fs_hz: 2.5e6,
        duration_s: 2.0,
        expected_cn0_dbhz: CN0_DBHZ - 10.0 * 2f64.log10(),
    }
}

/// What one run measured.
struct Outcome {
    acquired: bool,
    statistic: f64,
    threshold: f64,
    doppler_err_hz: f64,
    doppler_step_hz: f64,
    code_err_chips: f64,
    sample_chips: f64,
    pli_mean: f64,
    pli_frac_ok: f64,
    code_rms_chips: f64,
    doppler_mean_err_hz: f64,
    cn0_m2m4_dbhz: f64,
    cn0_nwpr_dbhz: Option<f64>,
    secondary_agreement: Option<f64>,
    scored_epochs: usize,
}

impl std::fmt::Display for Outcome {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "acq {} (stat {:.1} / thr {:.1}), dDoppler {:+.1} Hz (step {:.1}), dcode {:+.3} chip \
             (1 sample {:.3}); over {} epochs: PLI mean {:.3}, >=0.5 on {:.1} %, code RMS {:.4} \
             chip, Doppler {:+.2} Hz, C/N0 M2M4 {:.2} dB-Hz, NWPR {}, secondary {}",
            self.acquired,
            self.statistic,
            self.threshold,
            self.doppler_err_hz,
            self.doppler_step_hz,
            self.code_err_chips,
            self.sample_chips,
            self.scored_epochs,
            self.pli_mean,
            100.0 * self.pli_frac_ok,
            self.code_rms_chips,
            self.doppler_mean_err_hz,
            self.cn0_m2m4_dbhz,
            self.cn0_nwpr_dbhz
                .map_or("n/a".into(), |c| format!("{c:.2} dB-Hz")),
            self.secondary_agreement
                .map_or("n/a".into(), |a| format!("{:.2} %", 100.0 * a)),
        )
    }
}

/// Signed difference `a − b` wrapped into `(−len/2, len/2]`.
fn wrap_diff(a: f64, b: f64, len: f64) -> f64 {
    let d = (a - b).rem_euclid(len);
    if d > len / 2.0 {
        d - len
    } else {
        d
    }
}

/// Truth code phase (chips of the transmitted code) at stream time `t_s`, from the nearest
/// truth record carried forward at the Doppler-scaled chip rate.
fn truth_phase(truth: &[TruthRecord], code: &SignalCode, t_s: f64) -> f64 {
    let r = truth
        .iter()
        .min_by(|a, b| (a.t_s - t_s).abs().total_cmp(&(b.t_s - t_s).abs()))
        .unwrap();
    let rate = code.chip_rate_hz() * (1.0 + r.doppler_hz / code.carrier_hz());
    r.code_phase_chips + rate * (t_s - r.t_s)
}

/// The M2M4 C/N0 (dB-Hz) of complex prompts of integration `t_s`.
fn m2m4_cn0_dbhz(prompts: &[Cf64], t_s: f64) -> f64 {
    let n = prompts.len() as f64;
    let m2 = prompts.iter().map(|p| p.re * p.re + p.im * p.im).sum::<f64>() / n;
    let m4 = prompts.iter().map(|p| (p.re * p.re + p.im * p.im).powi(2)).sum::<f64>() / n;
    let ps = (2.0 * m2 * m2 - m4).max(0.0).sqrt();
    let pn = m2 - ps;
    10.0 * (ps / pn / t_s).log10()
}

/// Best agreement of the prompt signs with the secondary code over every cyclic shift, up to
/// a global sign.
fn secondary_agreement(epochs: &[EpochOutput], secondary: &[i8]) -> f64 {
    let n = secondary.len();
    let signs: Vec<i8> = epochs
        .iter()
        .map(|e| if e.prompt.re >= 0.0 { 1 } else { -1 })
        .collect();
    (0..n)
        .map(|shift| {
            let same = signs
                .iter()
                .enumerate()
                .filter(|(k, &s)| s == secondary[(k + shift) % n])
                .count() as f64
                / signs.len() as f64;
            same.max(1.0 - same)
        })
        .fold(0.0, f64::max)
}

fn run(case: &Case) -> Outcome {
    let spec = SampleSpec {
        fs_hz: case.fs_hz,
        center_hz: case.tx.carrier_hz(),
        if_hz: 0.0,
    };
    let mut cfg = SceneConfig::new(spec, case.duration_s);
    cfg.seed = SEED;
    cfg.threads = 2;
    let mut scene = Scene::new(cfg).unwrap();
    let lambda = C_M_PER_S / case.tx.carrier_hz();
    scene.add_satellite(SceneSatellite {
        id: 1,
        code: Box::new(case.tx.clone()),
        geometry: SatGeometry::Profile(RangeProfile {
            range_m: 2.1e7,
            range_rate_mps: -DOPPLER_HZ * lambda,
            range_accel_mps2: 0.0,
            elevation_deg: 45.0,
            azimuth_deg: 0.0,
        }),
        cn0_dbhz: Some(CN0_DBHZ),
        nav: NavData::None,
    });
    let mut sink = VecSink::default();
    let mut truth: Vec<TruthRecord> = Vec::new();
    scene.generate(&mut sink, &mut truth).unwrap();
    let samples = sink.samples;

    // Acquisition over the first replica period.
    let period = case.rx.period_s();
    let step = 2.0 / (3.0 * period);
    let acq_cfg = AcqConfig {
        coherent_periods: 1,
        noncoherent: 1,
        doppler_max_hz: 2000.0,
        doppler_step_hz: step,
        pfa: 1e-3,
    };
    let grid = acquire(&samples, &spec, &case.rx, &acq_cfg).unwrap();
    let r = grid.result.clone();
    let rx_len = case.rx.len_chips() as f64;
    let t0 = truth.iter().find(|t| t.t_s == 0.0).unwrap();
    let doppler_err_hz = r.doppler_hz - t0.doppler_hz;
    let code_err_chips = wrap_diff(r.code_phase_chips, t0.code_phase_chips, rx_len);

    // Tracking over the whole scene.
    let rx: Arc<dyn SpreadingCode + Send + Sync> = Arc::new(case.rx.clone());
    let init = ChannelInit::from_acquisition(rx, &r, &spec, 0, None);
    let loop_cfg = LoopConfig {
        label: case.signal.into(),
        cn0_window_periods: 5,
        cn0_windows: 10,
        ..LoopConfig::default()
    };
    let mut src = VecSource::new(spec, samples);
    let out = replay(&mut src, &[init], &[loop_cfg], None).unwrap();
    let epochs = &out[0].channels[0];

    let first = (epochs.len() / 2).max(
        epochs
            .iter()
            .position(|e| e.sample_index as f64 / case.fs_hz >= 0.3)
            .unwrap_or(epochs.len()),
    );
    let scored = &epochs[first..];
    let n = scored.len() as f64;
    let pli: Vec<f64> = scored
        .iter()
        .map(|e| {
            let (i2, q2) = (e.prompt.re.powi(2), e.prompt.im.powi(2));
            (i2 - q2) / (i2 + q2)
        })
        .collect();
    let code_rms_chips = (scored
        .iter()
        .map(|e| {
            let t = e.sample_index as f64 / case.fs_hz;
            wrap_diff(e.code_phase_chips, truth_phase(&truth, &case.tx, t), rx_len).powi(2)
        })
        .sum::<f64>()
        / n)
        .sqrt();
    let prompts: Vec<Cf64> = scored.iter().map(|e| e.prompt).collect();
    Outcome {
        acquired: r.acquired,
        statistic: r.statistic,
        threshold: r.threshold,
        doppler_err_hz,
        doppler_step_hz: step,
        code_err_chips,
        sample_chips: case.rx.chip_rate_hz() / case.fs_hz,
        pli_mean: pli.iter().sum::<f64>() / n,
        pli_frac_ok: pli.iter().filter(|&&p| p >= 0.5).count() as f64 / n,
        code_rms_chips,
        doppler_mean_err_hz: scored.iter().map(|e| e.doppler_hz).sum::<f64>() / n
            - t0.doppler_hz,
        cn0_m2m4_dbhz: m2m4_cn0_dbhz(&prompts, scored[0].t_coh_s),
        cn0_nwpr_dbhz: scored.last().and_then(|e| e.cn0_nwpr_dbhz),
        secondary_agreement: (!case.secondary.is_empty())
            .then(|| secondary_agreement(scored, &case.secondary)),
        scored_epochs: scored.len(),
    }
}

/// Run `case` and check every pre-registered bar, failing with every number on a miss.
fn check(case: Case) {
    let o = run(&case);
    let msg = format!("{} ({}): {o}", case.signal, case.rx.name());
    eprintln!("{msg}");
    let band = |c: f64| (c - case.expected_cn0_dbhz).abs() <= 1.5;
    let mut fails = Vec::new();
    if !o.acquired {
        fails.push("A1");
    }
    if o.doppler_err_hz.abs() > o.doppler_step_hz / 2.0 + 1.0 {
        fails.push("A2");
    }
    if o.code_err_chips.abs() > o.sample_chips {
        fails.push("A3");
    }
    if o.pli_mean < 0.8 || o.pli_frac_ok < 0.95 {
        fails.push("T1");
    }
    if o.code_rms_chips > 0.1 {
        fails.push("T2");
    }
    if o.doppler_mean_err_hz.abs() > 2.0 {
        fails.push("T3");
    }
    if !band(o.cn0_m2m4_dbhz) {
        fails.push("T4");
    }
    if case.secondary.is_empty() && !o.cn0_nwpr_dbhz.is_some_and(band) {
        fails.push("T5");
    }
    if o.secondary_agreement.is_some_and(|a| a < 0.99) {
        fails.push("T6");
    }
    assert!(fails.is_empty(), "bars {fails:?} missed: {msg}");
}

#[test]
fn gps_l1ca() {
    check(plain("gps-l1ca", gps::l1ca(3).unwrap(), 2.5e6, 1.0));
}

#[test]
fn gps_l5i() {
    check(tiered("gps-l5i", gps::l5_i5(3).unwrap(), 25e6, 0.6));
}

#[test]
fn gps_l5q() {
    check(tiered("gps-l5q", gps::l5_q5(3).unwrap(), 25e6, 0.6));
}

#[test]
fn gps_l2c() {
    check(l2c_cm_case(3));
}

#[test]
fn galileo_e1b() {
    check(plain("galileo-e1b", galileo::e1b(3).unwrap(), 5e6, 1.0));
}

#[test]
fn galileo_e1c() {
    check(tiered("galileo-e1c", galileo::e1c(3).unwrap(), 5e6, 1.0));
}

#[test]
fn galileo_e5a_i() {
    check(tiered("galileo-e5a-i", galileo::e5a_i(3).unwrap(), 25e6, 0.6));
}

#[test]
fn galileo_e5a_q() {
    check(tiered("galileo-e5a-q", galileo::e5a_q(3).unwrap(), 25e6, 0.6));
}

#[test]
fn beidou_b1i() {
    check(plain("beidou-b1i", beidou::b1i(3).unwrap(), 5e6, 1.0));
}

#[test]
fn beidou_b1c() {
    check(plain("beidou-b1c", beidou::b1c_data(3).unwrap(), 5e6, 1.5));
}

#[test]
fn glonass_l1of() {
    check(plain("glonass-l1of", glonass::l1of(-3).unwrap(), 1.25e6, 1.0));
}
