// SPDX-License-Identifier: AGPL-3.0-only
//! Reference oracle for the Augmented Forward Signal (AFS) spreading codes of the LunaNet
//! Signal-In-Space Recommended Standard (LSIS) V1.0, 29 January 2025, Volume A.
//!
//! Pre-registration (package D6, written 2026-10-02 before any Kshana code for the codes
//! existed, before the fixture below was cut from the standard and before any comparison was
//! run). The criterion, inputs and tolerance in this header are fixed by this commit.
//!
//! ## Quantity
//!
//! The logic-level chips (0 or 1, LSIS-150) of every code the standard defines, generated by
//! `kshana::lunar_afs::codes` from the algorithms the standard states, not from any table:
//!
//! 1. the data channel (AFS-I) primary code, a 2047-chip Gold code short-cycled to 2046 chips
//!    (LSIS-221, Appendix C), from the two 11-stage shift registers
//!    `g1(x) = x^11 + x^2 + 1` and `g2(x) = x^11 + x^8 + x^5 + x^2 + 1` of Figure C-1, both
//!    initialised to all ones, with the per-PRN G2 delay of Tables C-1 to C-5;
//! 2. the length-10223 Legendre sequence of Appendix D (`L(0) = 0`, `L(t) = 1` when `t` is a
//!    quadratic residue modulo 10223);
//! 3. the pilot channel (AFS-Q) primary code, the length-10230 Weil code of Appendix D
//!    (`W(t; k) = L(t) xor L((t + k) mod 10223)`, the seven-chip expansion `0110100`
//!    inserted before the `p`-th Weil chip) with the per-PRN Weil index `k` and insertion
//!    index `p` of Tables D-2 to D-6;
//! 4. the length-1499 Legendre sequence of Appendix E;
//! 5. the 1500-chip AFS-Q tertiary code of Appendix E (the length-1499 Weil code with the
//!    per-PRN index `k` of Tables E-2 to E-6, a `0` appended).
//!
//! PRNs 1 to 210 for every code.
//!
//! ## Oracle (kind: Reference)
//!
//! The values the standard itself prints so that implementations can be checked:
//!
//! - Tables C-1 to C-5: the G2 initialisation (hexadecimal) and the first and last 24 chips
//!   (hexadecimal) of every AFS-I PRN;
//! - Table D-1: the length-10223 Legendre sequence in hexadecimal;
//! - Tables D-2 to D-6: the first and last 24 chips of every AFS-Q primary PRN;
//! - Table E-1: the length-1499 Legendre sequence in hexadecimal;
//! - Tables E-2 to E-6: the first and last 24 chips of every tertiary PRN;
//! - [Annex3], the electronic attachments of the same standard: `006_GoldCode2046hex210prns.txt`
//!   (all 2046 chips of every AFS-I PRN), `007_l1cp_hex210prns.txt` (all 10230 chips of every
//!   AFS-Q primary PRN) and `008_Weil1500hex210prns.txt` (all 1500 chips of every tertiary
//!   PRN), each with the padding the Annex 3 README states.
//!
//! Source: LunaNet Signal-In-Space Recommended Standard - Augmented Forward Signal, Volume A,
//! LSIS V1.0, 29 January 2025 (NASA, ESA and JAXA; ESC-CCR-0690 initial release), retrieved
//! 2026-10-02 from
//! `https://www.nasa.gov/wp-content/uploads/2025/02/lunanet-signal-in-space-recommended-standard-augmented-forward-signal-vol-a.pdf`
//! (SHA-256 `986e07959f527d24280d87b5477298424ffdf754c4625f08041b5749592e61b6`); the Annex 3
//! files are embedded in that PDF. A public agency standard published for implementers; the
//! fixture carries only the printed hexadecimal values and their provenance in its NOTICE.md.
//!
//! The per-PRN parameters (G2 delay, Weil index, insertion index, tertiary Weil index) are
//! inputs transcribed from the same tables; comparing them with the tables proves nothing and
//! is not part of the claim. The claim is the generated chips.
//!
//! ## Tolerance
//!
//! Zero mismatching chips, over every PRN and every chip listed above, and zero mismatches in
//! the 11-bit G2 initialisation states. Source of the tolerance: the codes are defined exactly
//! by LSIS-221, LSIS-222 and LSIS-224; any single differing chip is a different code.
//!
//! ## Stated assumptions (ambiguities in the standard, fixed here before the comparison)
//!
//! - A1. Shift-register convention: the IS-GPS-200 convention the standard cites for its
//!   tables (footnote 5): stage `i` feeds stage `i + 1`, the output is stage 11, the feedback
//!   into stage 1 is the modulo-2 sum of the stages named by the polynomial's terms (stages 2
//!   and 11 for `g1`; 2, 5, 8 and 11 for `g2`).
//! - A2. The G2 delay `D` delays the G2 sequence: chip `t` of PRN `i` is
//!   `G1(t) xor G2((t - D) mod 2047)`, and both registers restart every 2046 chips. The printed
//!   G2 initialisation is then the G2 register content at chip 0, `I11` (stage 11) the most
//!   significant bit.
//! - A3. Hexadecimal chip strings are read most significant bit first, first chip first; the
//!   leading padding bits are dropped as the standard says (one bit of Table D-1, one bit of
//!   Table E-1, two bits of each Annex 3 AFS-I and AFS-Q primary line).
//! - A4. Appendix E gives no formula for its length-1499 Legendre sequence; it is taken to be
//!   the same quadratic-residue definition as Appendix D (`L(0) = 0`).
//! - A5. The Table D-1 caption says "10233"; the text and the code length say 10223, which is
//!   used. Table D-2 prints PRN 38 as "3"; the row position fixes it as 38.
//!
//! ## Disclosures
//!
//! The standard was downloaded and read before this commit, because it is the specification
//! being implemented; while reading, the printed G2 initialisation of PRN 1 was checked by hand
//! against its printed first 24 chips (two values of the standard, no Kshana output). No Kshana
//! code for these codes existed when this header was committed.
//!
//! D3 (licence, after the run). The standard carries no reuse terms, so its printed values
//! and Annex 3 files are no longer committed: this test reads them from the verified local
//! cache that `xval/lunar-afs/fetch_lsis.sh` fills from the NASA-hosted PDF
//! (`kshana::lunar_afs::lsis`), and skips with a notice when the cache is absent. The
//! comparison is unchanged: the same generated chips against the same printed and Annex 3
//! values, the same count and the same single finding. The per-PRN G2 delay and tertiary Weil
//! index are taken from the printed tables in the cache, as before; the AFS-Q indices are the
//! identical IS-GPS-800J values now committed in `src/lunar_afs/params.rs`.
//! [`afs_codes_finding_one_misprinted_table_cell`] pins the finding without the cache, from
//! four numbers cited from Table E-5 and the Annex 3 file.
//!
//! D2 (added after the first run, before any chip comparison completed). The first run stopped
//! on the harness's own length check: Table E-4 prints the last 24 tertiary chips of PRNs 127,
//! 132 and 134 as `37936`, `9394` and `99982`, five or four hexadecimal digits, evidently with
//! their leading zeros dropped. Those fields are left-padded to six digits. No tolerance,
//! criterion or engine code changed; the re-run is the first run that compared chips.

use kshana::lunar_afs::codes::{
    afs_i_from_delay, afs_q_primary, g2_initial_state, legendre_sequence, weil_tertiary, LsisCodes,
};
use kshana::lunar_afs::lsis;

/// A file the fetch script extracted from the standard's text into the cache.
fn printed(name: &str) -> String {
    let p = lsis::cache_dir().join("printed").join(name);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
}

/// Bits of a hexadecimal string, most significant first, with the first `drop` bits removed
/// (assumption A3).
fn hex_bits(hex: &str, drop: usize) -> Vec<u8> {
    let bits: Vec<u8> = hex
        .trim()
        .chars()
        .flat_map(|c| {
            let v = c.to_digit(16).expect("hex digit") as u8;
            (0..4).rev().map(move |k| (v >> k) & 1)
        })
        .collect();
    bits[drop..].to_vec()
}

/// The 24 bits of a printed "first/last 24 chips" field. Table E-5 prints three of them
/// with their leading zeros dropped (PRN 127 `37936`, PRN 132 `9394`, PRN 134 `99982`), so a
/// shorter field is left-padded to six digits (disclosure D2 in the header).
fn bits24(field: &str) -> Vec<u8> {
    hex_bits(&format!("{:0>6}", field.trim()), 0)
}

/// Count the mismatching chips of `got` against `want`.
fn mismatches(got: &[u8], want: &[u8]) -> usize {
    assert_eq!(got.len(), want.len(), "length");
    got.iter().zip(want).filter(|(a, b)| a != b).count()
}

/// Run the whole pre-registered comparison on the cached standard: the number of chips and
/// bits compared and the list of mismatching items.
fn compare_all() -> (usize, Vec<String>) {
    let mut failures: Vec<String> = Vec::new();
    let mut compared = 0usize;
    for (n, file, drop) in [
        (10223usize, "legendre_10223.hex", 1usize),
        (1499, "legendre_1499.hex", 1),
    ] {
        let l = legendre_sequence(n);
        let m = mismatches(&l, &hex_bits(&printed(file), drop));
        compared += n;
        if m != 0 {
            failures.push(format!("Legendre {n}: {m} bits differ"));
        }
    }
    let ai = lsis::annex3_hex_lines(
        &lsis::read_verified_text("006_GoldCode2046hex210prns.txt").unwrap(),
        500,
    );
    let aq = lsis::annex3_hex_lines(
        &lsis::read_verified_text("007_l1cp_hex210prns.txt").unwrap(),
        2500,
    );
    let at = lsis::annex3_hex_lines(
        &lsis::read_verified_text("008_Weil1500hex210prns.txt").unwrap(),
        370,
    );
    assert_eq!(
        (ai.len(), aq.len(), at.len()),
        (210, 210, 210),
        "Annex 3 PRN count"
    );
    let checks_text = printed("printed_checks.tsv");
    let params_text = printed("params.tsv");
    let rows: Vec<Vec<&str>> = checks_text
        .lines()
        .skip(1)
        .map(|l| l.split('\t').collect())
        .collect();
    let params: Vec<Vec<&str>> = params_text
        .lines()
        .skip(1)
        .map(|l| l.split('\t').collect())
        .collect();
    assert_eq!((rows.len(), params.len()), (210, 210));
    for (idx, (r, pr)) in rows.iter().zip(&params).enumerate() {
        let prn = (idx + 1) as u16;
        assert_eq!(r[0].parse::<u16>().unwrap(), prn);
        let delay: usize = pr[1].parse().unwrap();
        let tertiary_k: usize = pr[4].parse().unwrap();
        let ci = afs_i_from_delay(delay);
        let cq = afs_q_primary(prn).unwrap();
        let ct = weil_tertiary(tertiary_k);
        let checks: [(&str, &[u8], Vec<u8>); 9] = [
            ("AFS-I annex", &ci, hex_bits(&ai[idx], 2)),
            ("AFS-I first 24", &ci[..24], bits24(r[2])),
            ("AFS-I last 24", &ci[ci.len() - 24..], bits24(r[3])),
            ("AFS-Q annex", &cq, hex_bits(&aq[idx], 2)),
            ("AFS-Q first 24", &cq[..24], bits24(r[4])),
            ("AFS-Q last 24", &cq[cq.len() - 24..], bits24(r[5])),
            ("tertiary annex", &ct, hex_bits(&at[idx], 0)),
            ("tertiary first 24", &ct[..24], bits24(r[6])),
            ("tertiary last 24", &ct[ct.len() - 24..], bits24(r[7])),
        ];
        for (what, got, want) in checks.iter() {
            compared += got.len();
            let n = mismatches(got, want);
            if n != 0 {
                failures.push(format!("PRN {prn} {what}: {n} chips differ"));
            }
        }
        let init = g2_initial_state(delay);
        let printed_init = u16::from_str_radix(r[1], 16).unwrap() & 0x7FF;
        compared += 11;
        if init != printed_init {
            failures.push(format!(
                "PRN {prn} G2 initialisation {init:03X} vs printed {printed_init:03X}"
            ));
        }
    }
    (compared, failures)
}

/// The pre-registered comparison: every generated chip of every code and PRN equals the
/// standard's printed and electronic values (data-gated on the LSIS cache).
///
/// Result of the first full run (2026-10-02): 2 937 232 chips and bits compared, ONE item
/// differs: the "last 24 chips" printed for tertiary PRN 147 in Table E-5. The criterion
/// (zero mismatches) is therefore not met and the test stays ignored; see
/// [`afs_codes_finding_one_misprinted_table_cell`].
#[test]
#[ignore = "pre-registered criterion missed on the first run: 1 of 2 937 232 compared items differs \
            (Table E-5 PRN 147 'last 24 chips' prints A14850, a duplicate of the PRN 151 cell; the \
            generated code and the Annex 3 file both end 5677E8); finding pinned by \
            afs_codes_finding_one_misprinted_table_cell"]
fn afs_codes_match_lsis_v1_tables_and_annex3_bit_exact() {
    assert!(lsis::cache_present(), "{}", lsis::fetch_hint());
    let (compared, failures) = compare_all();
    eprintln!(
        "compared {compared} chips and bits; {} failures",
        failures.len()
    );
    assert!(
        failures.is_empty(),
        "{} mismatching items, first: {:?}",
        failures.len(),
        &failures[..failures.len().min(12)]
    );
}

/// The finding of the pre-registered comparison, pinned so that any change shows. Exactly one
/// compared item differs, and it is a misprint in the standard rather than in the generator:
///
/// - Table E-5 (LSIS V1.0 page 61) prints the same "last 24 chips", `A14850`, for PRN 147
///   (Weil index 607) and PRN 151 (Weil index 612);
/// - the generated PRN 151 code matches that value, the generated PRN 147 code does not;
/// - the standard's own Annex 3 file `008_Weil1500hex210prns.txt` gives PRN 147 ending in
///   `5677E8`, and the generated PRN 147 code ends the same way.
///
/// Without the cache this test checks the finding from those four cited numbers alone; with
/// it, the whole comparison must give exactly that one item over 2 937 232.
#[test]
fn afs_codes_finding_one_misprinted_table_cell() {
    let last24 = |k: usize| {
        let c = weil_tertiary(k);
        c[c.len() - 24..].to_vec()
    };
    assert_eq!(
        last24(612),
        bits24("A14850"),
        "PRN 151 (k = 612) matches its printed cell"
    );
    assert_eq!(
        last24(607),
        bits24("5677E8"),
        "PRN 147 (k = 607) matches the Annex 3 file"
    );
    assert_ne!(
        last24(607),
        bits24("A14850"),
        "PRN 147 differs from its printed cell"
    );
    if !lsis::cache_present() {
        eprintln!("SKIP (full comparison): {}", lsis::fetch_hint());
        return;
    }
    let (compared, failures) = compare_all();
    assert_eq!(compared, 2_937_232);
    assert_eq!(
        failures,
        vec!["PRN 147 tertiary last 24: 17 chips differ".to_string()]
    );
    // The loader recovers the same G2 delays from the Annex 3 Gold file as Tables C print.
    let loaded = LsisCodes::load().unwrap();
    let params_text = printed("params.tsv");
    for (i, l) in params_text.lines().skip(1).enumerate() {
        let d: u16 = l.split('\t').nth(1).unwrap().parse().unwrap();
        assert_eq!(loaded.g2_delay[i], d, "PRN {}", i + 1);
    }
}
