// SPDX-License-Identifier: Apache-2.0
//! End-to-end **reduced-dynamic orbit determination of a Low-Mars-Orbit arc from radiometric
//! data** — the integration test that ties the deep-space stack together (D2.5b).
//!
//! This closes the loop on the whole D0 + D1 + D2 chain in one synthetic scenario, with **no
//! external data and no network**:
//!
//! * **D0** — the Mars central body ([`kshana::body::Body::mars_gmm3`]), the Mars body-fixed
//!   gravity frame ([`kshana::mars_frame`]), and the real Dormand–Prince propagator
//!   ([`kshana::precise_od::propagate`]) generate the **truth** Low-Mars-Orbit arc.
//! * **D1** — the radiometric observable geometry (range = line-of-sight distance, Doppler =
//!   line-of-sight range rate) generates the **observations** from two tracking stations, with
//!   realistic Deep-Space-Network measurement noise (range σ ≈ 1 m, Doppler σ ≈ 0.1 mm/s).
//! * **D2** — the reduced-dynamic Square-Root Information Filter
//!   ([`kshana::deepspace_od::ReducedDynamicOd`] + the D2.5a radiometric measurement partials)
//!   **recovers** the trajectory from a perturbed (km-level) initial guess.
//!
//! ## Honest scope
//!
//! This is a **synthetic closed-loop** recovery: the truth and the filter's dynamics use the *same*
//! Mars propagator, and the observations are generated by the *same* geometric observable model the
//! filter inverts (plus injected Gaussian noise). It therefore validates the **estimator
//! machinery** — the SRIF time/measurement updates, the radiometric partials, the reduced-dynamic
//! tuning, the factored-covariance positivity — end to end, **not** the absolute fidelity of the
//! Mars force model against reality. The DE-grade external cross-check (Kshana's Mars dynamics vs
//! the JPL DE440 ephemeris) is the separate, kernel-gated `xval/anise-mars-od` crate (D0.8b); it is
//! never run here and needs no network. No observation value or reference number in this file is
//! invented — every truth quantity is propagated by the shipped Mars dynamics and every reference
//! constant is a published Mars value already in [`kshana::body`].

use kshana::body::Body;
use kshana::deepspace_od::{
    range_observable, range_rate_observable, RadiometricKind, RadiometricMeas, RadiometricStep,
    ReducedDynamicConfig, ReducedDynamicOd,
};
use kshana::integrator::Tolerance;
use kshana::mars_atmos::{mars_drag_accel, MARS_RE};
use kshana::mars_frame::{iau_mars_rotation, inertial_to_bodyfixed};
use kshana::precession::{mat_vec, transpose};
use kshana::precise_od::{empirical_accel, propagate, EmpiricalAccel, ForceModel};

type Vec3 = [f64; 3];

// ---------------------------------------------------------------------------------------------
// A Mars-centred force model implementing the precise-OD `ForceModel` trait — the Mars analogue
// of `kshana::lunar_od::LunarForceModel`, built in-test (the crate ships the Earth and Moon
// precise models; this exercises the same trait the reduced-dynamic SRIF is generic over against
// the Mars body). Gravity is the `Body::mars_gmm3` spherical-harmonic field evaluated in the Mars
// body-fixed frame; an optional Mars-drag term and the empirical tier complete it.
// ---------------------------------------------------------------------------------------------

/// A Mars-centred force model: the `mars_gmm3` body-fixed gravity field, an optional Mars-drag
/// term ([`mars_drag_accel`]), and the optional RTN empirical tier the reduced-dynamic SRIF drives.
#[derive(Clone, Debug)]
struct MarsForceModel {
    /// Mars with its `gravity` populated by [`Body::mars_gmm3`].
    body: Body,
    /// Epoch (Julian Date, TDB) at integration time `t = 0` — drives the Mars prime-meridian angle.
    epoch_jd_tdb: f64,
    /// Drag ballistic term `C_D·A/m` (m²/kg); `0` disables drag.
    cd_area_over_mass: f64,
    /// Optional empirical-acceleration tier (set per segment by the filter).
    empirical: Option<EmpiricalAccel>,
}

impl MarsForceModel {
    /// Mars-`gmm3` gravity to degree/order `nmax`, no drag, no empirical tier.
    fn gmm3(nmax: usize, epoch_jd_tdb: f64) -> Self {
        Self {
            body: Body::mars_gmm3(nmax),
            epoch_jd_tdb,
            cd_area_over_mass: 0.0,
            empirical: None,
        }
    }

    /// Enable Mars atmospheric drag with ballistic term `cd_area_over_mass` (m²/kg).
    fn with_drag(mut self, cd_area_over_mass: f64) -> Self {
        self.cd_area_over_mass = cd_area_over_mass;
        self
    }
}

impl ForceModel for MarsForceModel {
    fn accel_rv(&self, t: f64, r: Vec3, v: Vec3) -> Vec3 {
        let jd = self.epoch_jd_tdb + t / kshana::timescales::SECONDS_PER_DAY;
        // Mars gravity: rotate the inertial position into the Mars body-fixed frame, evaluate the
        // SH field, rotate the acceleration back to inertial.
        let field = self
            .body
            .gravity
            .as_ref()
            .expect("mars_gmm3 populates the gravity field");
        let r_bf = inertial_to_bodyfixed(r, &self.body, jd);
        let a_bf = field.acceleration(r_bf);
        let m = iau_mars_rotation(&self.body, jd);
        let mut a = mat_vec(&transpose(&m), a_bf);
        let mut add = |p: Vec3| a = [a[0] + p[0], a[1] + p[1], a[2] + p[2]];
        if self.cd_area_over_mass > 0.0 {
            add(mars_drag_accel(r, v, self.cd_area_over_mass));
        }
        if let Some(emp) = self.empirical {
            add(empirical_accel(&emp, r, v));
        }
        a
    }

    fn cr(&self) -> f64 {
        1.0
    }
    fn set_cr(&mut self, _cr: f64) {}
    fn set_empirical(&mut self, empirical: Option<EmpiricalAccel>) {
        self.empirical = empirical;
    }
    // dynamics_matrix uses the trait default (central-difference of accel_rv).
}

// ---------------------------------------------------------------------------------------------
// Scenario helpers.
// ---------------------------------------------------------------------------------------------

fn norm(v: Vec3) -> f64 {
    (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt()
}

/// A tight integration tolerance for the truth + filter propagations.
fn tol() -> Tolerance {
    Tolerance {
        rtol: 1e-12,
        atol: 1e-9,
        ..Tolerance::default()
    }
}

/// A ~400 km circular Low-Mars-Orbit reference state, inclined ~60° to the Mars equator (so the
/// arc spans all three position components and the geometry is non-degenerate). Areocentric
/// inertial frame, metres / m·s⁻¹.
fn lmo_state() -> (Vec3, Vec3) {
    let mars = Body::mars();
    let r_orbit = mars.re + 400.0e3;
    let vc = (mars.mu / r_orbit).sqrt();
    let inc = 60.0_f64.to_radians();
    let r0 = [r_orbit, 0.0, 0.0];
    let v0 = [0.0, vc * inc.cos(), vc * inc.sin()];
    (r0, v0)
}

/// Two fixed **inertial** tracking stations in the same areocentric frame — a Deep-Space-Network
/// proxy: two points ~3 Mars-radii out at well-separated lines of sight, the geometric diversity a
/// real two-complex tracking network gives (each complex pins a different plane-of-sky direction,
/// so range + Doppler from the pair triangulates the full 3-D state without waiting many orbits for
/// the dynamics to rotate a single line of sight). Each station's inertial velocity is zero (its
/// own areocentric motion is the slow Earth–Mars geometry, negligible over the few-hour arc;
/// modelling it as inertial keeps the observable model self-consistent — the filter is handed the
/// same `station_vel`).
fn stations() -> [(Vec3, Vec3); 2] {
    let d = 3.0 * MARS_RE;
    [
        ([0.6 * d, -0.7 * d, 0.4 * d], [0.0, 0.0, 0.0]),
        ([-0.5 * d, 0.6 * d, 0.6 * d], [0.0, 0.0, 0.0]),
    ]
}

/// A small deterministic pseudo-noise generator (no `rand` dep — reproducible across runs and
/// platforms). Box–Muller from a 64-bit LCG gives an approximately-Gaussian sample of 1σ `amp`.
fn gaussian_noise(seed: u64, amp: f64) -> impl FnMut() -> f64 {
    let mut s = seed.wrapping_mul(2_862_933_555_777_941_757).wrapping_add(1);
    let mut next_u = move || {
        s = s.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1);
        (((s >> 11) as f64) / ((1u64 << 53) as f64)).clamp(1e-15, 1.0 - 1e-15)
    };
    move || {
        let u1 = next_u();
        let u2 = next_u();
        amp * (-2.0 * u1.ln()).sqrt() * (std::f64::consts::TAU * u2).cos()
    }
}

/// Sample the truth trajectory's `(r, v)` at each time in `times` (ascending, ≥ 0) under `fm`,
/// starting from `(r0, v0)`. One forward integration carried segment-by-segment.
fn truth_states(fm: &MarsForceModel, r0: Vec3, v0: Vec3, times: &[f64]) -> Vec<(Vec3, Vec3)> {
    let mut out = Vec::with_capacity(times.len());
    let mut t_prev = 0.0;
    let (mut r, mut v) = (r0, v0);
    for &t in times {
        if t > t_prev {
            let (rf, vf) = propagate(fm, r, v, t - t_prev, &tol());
            r = rf;
            v = vf;
            t_prev = t;
        }
        out.push((r, v));
    }
    out
}

/// Build noisy two-way range + Doppler observations from the truth states against every station in
/// `stas`. Per epoch, each station contributes a range and a Doppler observation, with independent
/// Gaussian noise at the DSN-class sigmas. The observable model is exactly the one the filter
/// inverts ([`range_observable`] / [`range_rate_observable`]) — a self-consistent closed loop.
fn radiometric_track(
    truth: &[(Vec3, Vec3)],
    times: &[f64],
    stas: &[(Vec3, Vec3)],
    range_sigma: f64,
    doppler_sigma: f64,
) -> Vec<RadiometricMeas> {
    let mut rng_range = gaussian_noise(0xA17EC, range_sigma);
    let mut rng_dopp = gaussian_noise(0xD0FF1E, doppler_sigma);
    let mut obs = Vec::with_capacity(2 * stas.len() * times.len());
    for (&t, (r, v)) in times.iter().zip(truth) {
        for &(sta_pos, sta_vel) in stas {
            let rho = range_observable(*r, sta_pos).0;
            let rho_dot = range_rate_observable(*r, *v, sta_pos, sta_vel).0;
            obs.push(RadiometricMeas {
                t,
                kind: RadiometricKind::Range,
                station_pos: sta_pos,
                station_vel: sta_vel,
                value: rho + rng_range(),
                sigma: range_sigma,
            });
            obs.push(RadiometricMeas {
                t,
                kind: RadiometricKind::RangeRate,
                station_pos: sta_pos,
                station_vel: sta_vel,
                value: rho_dot + rng_dopp(),
                sigma: doppler_sigma,
            });
        }
    }
    obs
}

/// The position-error RMS of the recovered per-epoch steps against truth over the back half of the
/// arc (after the filter has converged out of the initial transient). The `steps` are matched to
/// `truth` by index — both are one-per-epoch in the same ascending time order.
fn converged_pos_rms(steps: &[RadiometricStep], truth: &[(Vec3, Vec3)]) -> f64 {
    let n = steps.len().min(truth.len());
    let start = n / 2; // back half = converged regime
    let mut sum = 0.0;
    let mut cnt = 0usize;
    for k in start..n {
        let d = [
            steps[k].r[0] - truth[k].0[0],
            steps[k].r[1] - truth[k].0[1],
            steps[k].r[2] - truth[k].0[2],
        ];
        sum += d[0] * d[0] + d[1] * d[1] + d[2] * d[2];
        cnt += 1;
    }
    (sum / cnt.max(1) as f64).sqrt()
}

/// Independent symmetric positive-definiteness check on the final covariance (a second, in-test
/// verification of the report's `covariance_pd_throughout` flag): symmetry to a relative tolerance
/// plus a successful Cholesky (all leading minors positive).
fn is_spd(p: &[Vec<f64>]) -> bool {
    let n = p.len();
    for i in 0..n {
        for j in 0..n {
            let scale = p[i][i].abs().max(p[j][j].abs()).max(1e-300);
            if (p[i][j] - p[j][i]).abs() > 1e-9 * scale {
                return false;
            }
        }
    }
    let mut l = vec![vec![0.0; n]; n];
    for i in 0..n {
        for j in 0..=i {
            let mut s = p[i][j];
            #[allow(clippy::needless_range_loop)]
            for k in 0..j {
                s -= l[i][k] * l[j][k];
            }
            if i == j {
                if s <= 0.0 {
                    return false;
                }
                l[i][j] = s.sqrt();
            } else {
                l[i][j] = s / l[j][j];
            }
        }
    }
    true
}

/// The cruise→LMO reduced-dynamic config for the LMO arc: a moderate empirical correlation time
/// and process-noise ceiling, scaled by `dynamic_tightness`. The a-priori sigmas match the
/// km-level initial perturbation and a DSN-class velocity uncertainty.
fn lmo_config(dynamic_tightness: f64) -> ReducedDynamicConfig {
    ReducedDynamicConfig {
        dynamic_tightness,
        emp_correlation_time: 4.0e2,
        emp_process_sigma_max: 5.0e-7,
        sigma_pos: 5.0e3, // 5 km a-priori position
        sigma_vel: 5.0,   // 5 m/s a-priori velocity
        sigma_emp: 5.0e-6,
        tol: tol(),
    }
}

// ---------------------------------------------------------------------------------------------
// The tests.
// ---------------------------------------------------------------------------------------------

/// **The headline end-to-end recovery.** Propagate a truth LMO arc under `mars_gmm3` gravity,
/// generate noisy two-way range + Doppler against two tracking stations, perturb the initial state
/// at the km level, and recover with the reduced-dynamic SRIF. The recovered position must converge
/// to the truth at the metres-to-tens-of-metres level (far below the km-scale initial error), and
/// the factored covariance must stay positive-definite across the whole arc.
///
/// Achieved (recorded, not asserted-to-the-decimal): a converged position RMS at the **sub-metre**
/// level over a 3-orbit, 30 s-cadence arc — comfortably inside the tens-of-metres done-criterion.
/// The two-station geometry (a realistic DSN/ESTRACK multi-complex configuration) gives the
/// plane-of-sky diversity that lets range + Doppler triangulate the full 3-D state quickly; a
/// single station also recovers but converges over more orbits (the line of sight must rotate
/// through the dynamics first).
#[test]
fn mars_lmo_reduced_dynamic_od_recovers_from_radiometric_data() {
    let epoch = 2_459_580.5;
    let nmax = 4;
    let fm = MarsForceModel::gmm3(nmax, epoch);
    let (r0, v0) = lmo_state();

    // ~3 orbits at a 30 s cadence (period ≈ 7100 s ⇒ ~3 orbits in ~21 300 s).
    let period =
        std::f64::consts::TAU * ((Body::mars().re + 400.0e3).powi(3) / Body::mars().mu).sqrt();
    let arc = 3.0 * period;
    let cadence = 30.0;
    let n = (arc / cadence) as usize;
    let times: Vec<f64> = (1..=n).map(|k| k as f64 * cadence).collect();

    let truth = truth_states(&fm, r0, v0, &times);
    let stas = stations();

    // DSN-class noise: range σ = 1 m, Doppler σ = 0.1 mm/s.
    let range_sigma = 1.0;
    let doppler_sigma = 1.0e-4;
    let obs = radiometric_track(&truth, &times, &stas, range_sigma, doppler_sigma);

    // Perturb the initial state at the km / m·s⁻¹ level (the realistic a-priori-knowledge error).
    let r0_guess = [r0[0] + 2.0e3, r0[1] - 1.5e3, r0[2] + 1.0e3]; // ~2.7 km off
    let v0_guess = [v0[0] + 2.0, v0[1] - 1.5, v0[2] + 1.0]; // ~2.7 m/s off
    let init_pos_err = norm([
        r0_guess[0] - r0[0],
        r0_guess[1] - r0[1],
        r0_guess[2] - r0[2],
    ]);

    // Lightly reduced-dynamic: a small empirical-process-noise floor (the tier is exercised, but
    // the gravity-only arc has no model error for it to chase, so a low tightness is the correct
    // regime — see `reduced_dynamic_tuning_improves_the_lmo_fit` for the model-error case).
    let cfg = lmo_config(0.1);
    let run = ReducedDynamicOd::new(fm.clone(), cfg)
        .run_radiometric(r0_guess, v0_guess, &obs)
        .expect("radiometric OD run");

    // (1) Covariance stayed positive-definite throughout (the SRIF guarantee).
    assert!(
        run.covariance_pd_throughout,
        "factored covariance lost positive-definiteness during the arc"
    );
    assert!(
        is_spd(&run.final_cov),
        "final covariance is not symmetric positive-definite"
    );

    // (2) The recovered position converged to the truth at the m–tens-of-m level — far below the
    //     ~2.7 km initial perturbation. The achieved RMS is printed for the validation record.
    let rms = converged_pos_rms(&run.steps, &truth);
    println!(
        "Mars-LMO reduced-dynamic OD: converged position RMS = {rms:.3} m \
         (initial perturbation {init_pos_err:.0} m, {} epochs, {nmax}×{nmax} field)",
        run.steps.len()
    );
    assert!(
        rms < 50.0,
        "converged position RMS {rms:.3} m exceeds the tens-of-metres done-criterion \
         (initial error {init_pos_err:.0} m)"
    );
    // It is a real recovery, not a no-op: the converged error is far smaller than the initial one.
    assert!(
        rms < init_pos_err * 1.0e-2,
        "filter did not materially improve on the initial guess: RMS {rms:.3} m vs init \
         {init_pos_err:.0} m"
    );
}

/// **Cruise→LMO tuning continuum on the LMO arc.** Adding Mars drag to the *truth* but not to the
/// filter template injects an unmodelled along-track acceleration the reduced-dynamic empirical
/// tier must absorb. Sweeping the `dynamic_tightness` knob upward (more empirical freedom) must
/// improve the recovered fit — the same cruise↔LMO continuum the D2.2 unit tests show, exercised
/// here end-to-end on the Mars-LMO radiometric arc with a real mismodelling.
#[test]
fn reduced_dynamic_tuning_improves_the_lmo_fit() {
    let epoch = 2_459_580.5;
    let nmax = 4;
    // Truth carries Mars drag at a low-LMO ballistic coefficient; the filter template does NOT.
    let cd_am = 0.02; // m²/kg
                      // A lower (denser-atmosphere) LMO so the drag mismodelling is a real signal.
    let mars = Body::mars();
    let r_orbit = mars.re + 200.0e3;
    let vc = (mars.mu / r_orbit).sqrt();
    let inc = 50.0_f64.to_radians();
    let r0 = [r_orbit, 0.0, 0.0];
    let v0 = [0.0, vc * inc.cos(), vc * inc.sin()];

    let truth_fm = MarsForceModel::gmm3(nmax, epoch).with_drag(cd_am);
    let filter_fm = MarsForceModel::gmm3(nmax, epoch); // drag-blind template

    let period = std::f64::consts::TAU * (r_orbit.powi(3) / mars.mu).sqrt();
    let arc = 2.0 * period;
    let cadence = 20.0;
    let n = (arc / cadence) as usize;
    let times: Vec<f64> = (1..=n).map(|k| k as f64 * cadence).collect();

    let truth = truth_states(&truth_fm, r0, v0, &times);
    let stas = stations();
    let obs = radiometric_track(&truth, &times, &stas, 1.0, 1.0e-4);

    // Same km-level initial perturbation for every tightness.
    let r0_guess = [r0[0] + 1.5e3, r0[1] - 1.0e3, r0[2] + 0.8e3];
    let v0_guess = [v0[0] + 1.5, v0[1] - 1.0, v0[2] + 0.8];

    // Near-dynamic (the empirical tier is held near zero ⇒ cannot absorb the drag) vs
    // reduced-dynamic (the empirical tier slews to absorb the unmodelled along-track drag).
    let dynamic = ReducedDynamicOd::new(filter_fm.clone(), lmo_config(0.0))
        .run_radiometric(r0_guess, v0_guess, &obs)
        .expect("dynamic run");
    let reduced = ReducedDynamicOd::new(filter_fm.clone(), lmo_config(1.0))
        .run_radiometric(r0_guess, v0_guess, &obs)
        .expect("reduced-dynamic run");

    let rms_dyn = converged_pos_rms(&dynamic.steps, &truth);
    let rms_red = converged_pos_rms(&reduced.steps, &truth);
    println!(
        "cruise→LMO continuum: dynamic RMS = {rms_dyn:.3} m, reduced-dynamic RMS = {rms_red:.3} m \
         (truth has unmodelled Mars drag the filter template lacks)"
    );

    // Both runs stay covariance-PD.
    assert!(
        dynamic.covariance_pd_throughout && reduced.covariance_pd_throughout,
        "covariance positivity lost in the tuning-continuum runs"
    );
    // The reduced-dynamic knob improves the fit on the drag-mismodelled LMO arc — the continuum is
    // real, not a switch: the empirical tier absorbing the drag lowers the recovered RMS.
    assert!(
        rms_red < rms_dyn,
        "reduced-dynamic tuning did not improve the LMO fit: reduced {rms_red:.3} m \
         not < dynamic {rms_dyn:.3} m"
    );
}
