// SPDX-License-Identifier: AGPL-3.0-only
//! Moving-platform monitors on synthetic vessel logs (text generated by
//! `receiver_trust::synth`; no measurement, no radio signal).

use kshana::receiver_trust::ingest::read_nmea;
use kshana::receiver_trust::monitors::{
    run_monitors, Monitor, MonitorConfig, TrustResult, TrustState,
};
use kshana::receiver_trust::platform::{PlatformCfg, PlatformKind};
use kshana::receiver_trust::synth::{synth_voyage, DragSpec, VoyageSpec};

fn vessel() -> MonitorConfig {
    MonitorConfig {
        platform: PlatformCfg {
            kind: PlatformKind::Vessel,
            antenna_height_m: Some(18.0),
            heading_sensor: true,
            ..Default::default()
        },
        ..MonitorConfig::default()
    }
}

fn run_text(text: &str, cfg: &MonitorConfig) -> TrustResult {
    run_monitors(&read_nmea(text).unwrap(), None, cfg).unwrap()
}

fn drag(onset_s: f64) -> DragSpec {
    DragSpec {
        onset_s,
        accel_mps2: 0.02,
        speed_mps: 3.0,
        bearing_rel_deg: 90.0,
        cn0_common_dbhz: None,
        cn0_ramp_s: 60.0,
    }
}

fn first_alarm(r: &TrustResult, m: Monitor) -> Option<f64> {
    r.runs
        .iter()
        .filter(|x| x.monitor == m)
        .map(|x| x.start_s)
        .min_by(f64::total_cmp)
}

fn voyage(duration_s: f64, drag: Option<DragSpec>) -> String {
    synth_voyage(&VoyageSpec {
        duration_s,
        drag,
        ..Default::default()
    })
}

#[test]
fn a_clean_voyage_raises_no_alarm_and_runs_every_moving_platform_monitor() {
    let r = run_text(&voyage(1500.0, None), &vessel());
    assert!(r.runs.is_empty(), "{:?}", r.runs);
    assert_eq!(r.first_alarm_s, None);
    for m in [
        Monitor::Kinematic,
        Monitor::HeadingCourse,
        Monitor::SpeedLog,
        Monitor::SeaLevel,
        Monitor::Cn0Spread,
        Monitor::Cn0Rise,
        Monitor::TimeConsistency,
    ] {
        assert!(r.monitors_run.contains(&m), "{m:?}");
    }
    // The static monitor that assumes a fixed antenna does not run on a ship.
    assert!(!r.monitors_run.contains(&Monitor::PositionJump));
    // Not run: needs the receiver's security reports or an OSNMA status.
    assert!(!r.monitors_run.contains(&Monitor::SecSpoof));
}

#[test]
fn the_same_voyage_as_a_static_platform_trips_the_static_position_jump() {
    // The reason the platform has to be declared: a ship under way leaves the calibration
    // mean, which the static monitor reads as a jump.
    let r = run_text(&voyage(1500.0, None), &MonitorConfig::default());
    assert!(first_alarm(&r, Monitor::PositionJump).is_some());
}

#[test]
fn a_self_consistent_drag_off_is_caught_by_the_gyro_and_never_before_onset() {
    let r = run_text(&voyage(1500.0, Some(drag(600.0))), &vessel());
    let t = first_alarm(&r, Monitor::HeadingCourse).expect("heading alarm");
    assert!((600.0..=720.0).contains(&t), "{t}");
    assert!(r.runs.iter().all(|x| x.start_s >= 600.0), "{:?}", r.runs);
}

#[test]
fn a_drag_along_the_track_shows_against_the_speed_log() {
    let mut d = drag(600.0);
    d.bearing_rel_deg = 0.0;
    let r = run_text(&voyage(1500.0, Some(d)), &vessel());
    let t = first_alarm(&r, Monitor::SpeedLog).expect("speed-log alarm");
    assert!((600.0..=800.0).contains(&t), "{t}");
}

#[test]
fn counterfeit_signals_of_equal_power_collapse_the_c_n0_spread() {
    let mut d = drag(600.0);
    d.cn0_common_dbhz = Some(46.0);
    let r = run_text(&voyage(1500.0, Some(d)), &vessel());
    let t = first_alarm(&r, Monitor::Cn0Spread).expect("spread alarm");
    assert!((600.0..=700.0).contains(&t), "{t}");
}

fn edited(duration_s: f64, f: impl Fn(&mut kshana::receiver_trust::LogEpoch)) -> TrustResult {
    let mut tl = read_nmea(&voyage(duration_s, None)).unwrap();
    for e in tl.epochs.iter_mut() {
        f(e);
    }
    run_monitors(&tl, None, &vessel()).unwrap()
}

#[test]
fn every_satellite_rising_together_is_caught_but_one_satellite_is_not() {
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            for c in e.cn0.iter_mut() {
                c.cn0_dbhz += 5.0;
            }
        }
    });
    let t = first_alarm(&r, Monitor::Cn0Rise).expect("rise alarm");
    assert!((700.0..=710.0).contains(&t), "{t}");
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            if let Some(c) = e.cn0.first_mut() {
                c.cn0_dbhz += 15.0;
            }
        }
    });
    assert_eq!(first_alarm(&r, Monitor::Cn0Rise), None);
}

#[test]
fn receiver_security_reports_and_a_failed_osnma_status_are_extra_monitors() {
    use kshana::receiver_trust::OsnmaStatus;
    let r = edited(900.0, |e| {
        let m = e.marine.as_mut().unwrap();
        // Spoofing indicated from 500 s, jamming at warning from 600 s, OSNMA failure
        // from 700 s; before that the receiver reports all clear.
        m.sec_spoof_state = Some(if e.t_s >= 500.0 { 2 } else { 1 });
        m.sec_jam_state = Some(if e.t_s >= 600.0 { 2 } else { 1 });
        m.osnma = Some(if e.t_s >= 700.0 {
            OsnmaStatus::Failed
        } else {
            OsnmaStatus::Authenticated
        });
    });
    assert_eq!(first_alarm(&r, Monitor::SecSpoof), Some(500.0));
    assert_eq!(first_alarm(&r, Monitor::SecJam), Some(600.0));
    assert_eq!(first_alarm(&r, Monitor::Osnma), Some(700.0));
    // Not reporting at all is not an alarm and the monitors are then not run.
    let r = edited(900.0, |_| {});
    assert!(!r.monitors_run.contains(&Monitor::Osnma));
}

#[test]
fn a_position_step_that_the_reported_velocity_does_not_explain_is_kinematic() {
    // 600 m north from 700 s on, with the speed and course left as they were.
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            if let Some(f) = e.fix.as_mut() {
                f.lat_deg += 0.0054;
            }
        }
    });
    let t = first_alarm(&r, Monitor::Kinematic).expect("kinematic alarm");
    assert!((700.0..=702.0).contains(&t), "{t}");
}

#[test]
fn an_impossible_implied_speed_is_kinematic_even_without_a_reported_velocity() {
    let r = edited(1200.0, |e| {
        if let Some(m) = e.marine.as_mut() {
            m.sog_kn = None;
            m.cog_deg = None;
        }
        if e.t_s >= 700.0 {
            if let Some(f) = e.fix.as_mut() {
                f.lat_deg += 0.0054;
            }
        }
    });
    assert!(first_alarm(&r, Monitor::Kinematic).is_some());
}

#[test]
fn a_climbing_antenna_fails_the_sea_level_check() {
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            if let Some(m) = e.marine.as_mut() {
                m.alt_msl_m = m.alt_msl_m.map(|a| a + 40.0);
            }
        }
    });
    let t = first_alarm(&r, Monitor::SeaLevel).expect("sea-level alarm");
    assert!((700.0..=710.0).contains(&t), "{t}");
}

#[test]
fn time_running_backwards_or_jumping_fails_time_consistency() {
    for step in [-3.0, 9.0] {
        let r = edited(900.0, |e| {
            if e.t_s == 500.0 {
                e.marine.as_mut().unwrap().time_step_s = Some(step);
            }
        });
        assert_eq!(first_alarm(&r, Monitor::TimeConsistency), Some(500.0));
    }
    // A single dropped epoch (a 2 s step at 1 Hz) is a dropout, not a fault.
    let r = edited(900.0, |e| {
        if e.t_s == 500.0 {
            e.marine.as_mut().unwrap().time_step_s = Some(2.0);
        }
    });
    assert_eq!(first_alarm(&r, Monitor::TimeConsistency), None);
}

#[test]
fn the_receiver_clock_departing_from_the_host_clock_is_caught() {
    let r = edited(900.0, |e| {
        let skew = if e.t_s >= 500.0 { 4.0 } else { 0.0 };
        e.marine.as_mut().unwrap().arrival_s = Some(e.t_s + 0.05 + skew);
    });
    let t = first_alarm(&r, Monitor::TimeConsistency).expect("time alarm");
    assert!((500.0..=506.0).contains(&t), "{t}");
}

#[test]
fn a_declared_heading_sensor_that_is_not_in_the_log_is_an_error() {
    let text: String = voyage(300.0, None)
        .lines()
        .filter(|l| !l.contains("HDT") && !l.contains("VHW"))
        .map(|l| format!("{l}\n"))
        .collect();
    let e = run_monitors(&read_nmea(&text).unwrap(), None, &vessel()).unwrap_err();
    assert!(e.contains("heading_sensor"), "{e}");
    // Not declared: the heading check simply does not run.
    let mut cfg = vessel();
    cfg.platform.heading_sensor = false;
    let r = run_monitors(&read_nmea(&text).unwrap(), None, &cfg).unwrap();
    assert!(!r.monitors_run.contains(&Monitor::HeadingCourse));
}

#[test]
fn decisions_are_causal_truncating_a_log_never_changes_earlier_epochs() {
    let text = voyage(1500.0, Some(drag(600.0)));
    let full = run_text(&text, &vessel());
    let tl = read_nmea(&text).unwrap();
    for cut in [650usize, 900, 1200] {
        let mut part = tl.clone();
        part.epochs.truncate(cut);
        let r = run_monitors(&part, None, &vessel()).unwrap();
        assert_eq!(r.epochs.len(), cut);
        assert_eq!(r.epochs[..], full.epochs[..cut], "cut at {cut}");
    }
}

fn scores(r: &TrustResult) -> Vec<(f64, f64, TrustState)> {
    r.epochs
        .iter()
        .filter_map(|e| e.score.as_ref().map(|s| (e.t_s, s.score, s.band)))
        .collect()
}

#[test]
fn a_clean_voyage_scores_in_the_top_band_at_every_epoch() {
    let r = run_text(&voyage(1500.0, None), &vessel());
    let sc = scores(&r);
    assert_eq!(sc.len(), 1441, "every epoch after the 60 s calibration");
    for (t, s, band) in sc {
        assert_eq!((s, band), (100.0, TrustState::Nominal), "t = {t}");
    }
    assert!(r
        .epochs
        .iter()
        .all(|e| e.score.as_ref().is_none_or(|s| s.deductions.is_empty())));
}

#[test]
fn a_drag_off_that_the_receiver_calls_valid_takes_the_score_down_through_the_bands() {
    let mut d = drag(600.0);
    d.cn0_common_dbhz = Some(46.0);
    let r = run_text(&voyage(1500.0, Some(d)), &vessel());
    let sc = scores(&r);
    // Nothing deducted before the onset; nominal until the first deduction, then degraded,
    // then untrusted, in that order.
    assert!(sc
        .iter()
        .filter(|(t, ..)| *t < 600.0)
        .all(|(_, s, b)| *s == 100.0 && *b == TrustState::Nominal));
    let first = |band: TrustState| sc.iter().find(|(_, _, b)| *b == band).map(|x| x.0);
    let (deg, unt) = (
        first(TrustState::Degraded).unwrap(),
        first(TrustState::Untrusted).unwrap(),
    );
    assert!(600.0 < deg && deg < unt, "{deg} {unt}");
    assert!(unt < 700.0, "{unt}");
    // There is no hysteresis, so the score can touch the edge as it crosses; half a minute
    // on it stays below the degraded edge for the rest of the log.
    assert!(sc
        .iter()
        .filter(|(t, ..)| *t >= unt + 30.0)
        .all(|(_, s, _)| *s < 55.0));
    // The receiver never said the fix was bad.
    assert!(read_nmea(&voyage(1500.0, Some(drag(600.0))))
        .unwrap()
        .epochs
        .iter()
        .all(|e| e.marine.as_ref().unwrap().fix_valid == Some(true)));
}

#[test]
fn every_score_is_explained_by_its_deductions() {
    let mut d = drag(600.0);
    d.cn0_common_dbhz = Some(46.0);
    let r = run_text(&voyage(1500.0, Some(d)), &vessel());
    let cfg = &vessel().score;
    let mut saw_reasons = false;
    for e in &r.epochs {
        let Some(sc) = &e.score else { continue };
        let total: f64 = sc.deductions.iter().map(|d| d.points).sum();
        assert!(
            (sc.score - ((100.0 - total).clamp(0.0, 100.0) * 10.0).round() / 10.0).abs() < 1e-9
        );
        assert_eq!(sc.band, cfg.band(sc.score));
        assert_eq!(e.state, sc.band, "a vessel's state is its score's band");
        // Largest first, and every deducting monitor has a ratio of at least the onset.
        assert!(sc.deductions.windows(2).all(|w| w[0].points >= w[1].points));
        assert!(sc
            .deductions
            .iter()
            .all(|d| d.points > 0.0 && d.ratio > cfg.onset_ratio));
        assert_eq!(sc.score < 100.0, !sc.deductions.is_empty());
        saw_reasons |= !sc.deductions.is_empty();
    }
    assert!(saw_reasons);
}

#[test]
fn static_epochs_carry_no_score() {
    let r = run_text(&voyage(300.0, None), &MonitorConfig::default());
    assert!(r
        .epochs
        .iter()
        .all(|e| e.score.is_none() && e.marine.is_none()));
}

#[test]
fn the_scenario_result_records_the_score_model_and_the_csv_the_reasons() {
    let text = voyage(400.0, None);
    let toml = format!(
        "kind = \"receiver-trust\"\n[log]\nformat = \"nmea\"\ntext = {text:?}\n\
         [platform]\nkind = \"vessel\"\nantenna_height_m = 18.0\nheading_sensor = true\n\
         [score]\nnominal_min = 92.0\n[score.weights]\nsea-level = 10.0\n"
    );
    let out = kshana::receiver_trust::scenario::run_toml(&toml).unwrap();
    let v: serde_json::Value = serde_json::from_str(&out.json).unwrap();
    let m = &v["score_model"];
    assert_eq!(m["nominal_min"], 92.0);
    assert_eq!(m["degraded_min"], 55.0);
    assert_eq!(m["evidence_hold_s"], 10.0);
    assert_eq!(m["weights"]["sea-level"], 10.0);
    assert_eq!(m["weights"]["kinematic"], 60.0);
    assert!(v["verdict"]
        .as_str()
        .unwrap()
        .contains("trust score lowest 100.0, final 100.0"));
    assert!(v["log"]["observables"]
        .as_array()
        .unwrap()
        .iter()
        .any(|o| o == "marine"));
    let header = out.csv.lines().next().unwrap();
    assert!(header.ends_with(",alarms,score,score_reasons"), "{header}");
    assert!(out.csv.lines().nth(100).unwrap().contains(",100.0,"));
}

#[test]
fn a_slow_source_holds_its_statistic_for_the_stated_time_and_no_longer() {
    // C/N0 arrives every 5 s on the synthetic bus; the collapsed spread must count at the
    // epochs between, up to the hold, so the score does not blink back up.
    let mut d = drag(600.0);
    d.cn0_common_dbhz = Some(46.0);
    d.speed_mps = 0.0; // only the C/N0 changes: no other monitor can cover the gaps
    let text = voyage(1000.0, Some(d));
    let r = run_text(&text, &vessel());
    for e in r.epochs.iter().filter(|e| e.t_s >= 680.0) {
        let sc = e.score.as_ref().unwrap();
        assert!(
            sc.deductions
                .iter()
                .any(|d| d.monitor == Monitor::Cn0Spread),
            "t = {}",
            e.t_s
        );
        assert!(e.alarms.contains(&Monitor::Cn0Spread), "t = {}", e.t_s);
    }
    // With no hold the same evidence blinks.
    let mut cfg = vessel();
    cfg.score.evidence_hold_s = 0.0;
    let r0 = run_text(&text, &cfg);
    assert!(r0
        .epochs
        .iter()
        .filter(|e| e.t_s >= 680.0)
        .any(|e| !e.alarms.contains(&Monitor::Cn0Spread)));
}

#[test]
fn a_per_satellite_authentication_failure_alarms_the_osnma_monitor() {
    use kshana::receiver_trust::OsnmaStatus;
    let r = edited(900.0, |e| {
        let m = e.marine.as_mut().unwrap();
        m.sat_auth = vec![
            ("E11".into(), OsnmaStatus::Authenticated),
            (
                "E19".into(),
                if e.t_s >= 600.0 {
                    OsnmaStatus::Failed
                } else {
                    OsnmaStatus::Authenticated
                },
            ),
        ];
    });
    assert_eq!(first_alarm(&r, Monitor::Osnma), Some(600.0));
}
