// SPDX-License-Identifier: AGPL-3.0-only
//! Moving-platform monitors on synthetic vessel logs (text generated by
//! `receiver_trust::synth`; no measurement, no radio signal).

use kshana::receiver_trust::ingest::read_nmea;
use kshana::receiver_trust::monitors::{run_monitors, Monitor, MonitorConfig, TrustResult};
use kshana::receiver_trust::platform::{PlatformCfg, PlatformKind};
use kshana::receiver_trust::synth::{synth_voyage, DragSpec, VoyageSpec};

fn vessel() -> MonitorConfig {
    MonitorConfig {
        platform: PlatformCfg {
            kind: PlatformKind::Vessel,
            antenna_height_m: Some(18.0),
            heading_sensor: true,
            ..Default::default()
        },
        ..MonitorConfig::default()
    }
}

fn run_text(text: &str, cfg: &MonitorConfig) -> TrustResult {
    run_monitors(&read_nmea(text).unwrap(), None, cfg).unwrap()
}

fn drag(onset_s: f64) -> DragSpec {
    DragSpec {
        onset_s,
        accel_mps2: 0.02,
        speed_mps: 3.0,
        bearing_rel_deg: 90.0,
        cn0_common_dbhz: None,
        cn0_ramp_s: 60.0,
    }
}

fn first_alarm(r: &TrustResult, m: Monitor) -> Option<f64> {
    r.runs
        .iter()
        .filter(|x| x.monitor == m)
        .map(|x| x.start_s)
        .min_by(f64::total_cmp)
}

fn voyage(duration_s: f64, drag: Option<DragSpec>) -> String {
    synth_voyage(&VoyageSpec {
        duration_s,
        drag,
        ..Default::default()
    })
}

#[test]
fn a_clean_voyage_raises_no_alarm_and_runs_every_moving_platform_monitor() {
    let r = run_text(&voyage(1500.0, None), &vessel());
    assert!(r.runs.is_empty(), "{:?}", r.runs);
    assert_eq!(r.first_alarm_s, None);
    for m in [
        Monitor::Kinematic,
        Monitor::HeadingCourse,
        Monitor::SpeedLog,
        Monitor::SeaLevel,
        Monitor::Cn0Spread,
        Monitor::Cn0Rise,
        Monitor::TimeConsistency,
    ] {
        assert!(r.monitors_run.contains(&m), "{m:?}");
    }
    // The static monitor that assumes a fixed antenna does not run on a ship.
    assert!(!r.monitors_run.contains(&Monitor::PositionJump));
    // Not run: needs the receiver's security reports or an OSNMA status.
    assert!(!r.monitors_run.contains(&Monitor::SecSpoof));
}

#[test]
fn the_same_voyage_as_a_static_platform_trips_the_static_position_jump() {
    // The reason the platform has to be declared: a ship under way leaves the calibration
    // mean, which the static monitor reads as a jump.
    let r = run_text(&voyage(1500.0, None), &MonitorConfig::default());
    assert!(first_alarm(&r, Monitor::PositionJump).is_some());
}

#[test]
fn a_self_consistent_drag_off_is_caught_by_the_gyro_and_never_before_onset() {
    let r = run_text(&voyage(1500.0, Some(drag(600.0))), &vessel());
    let t = first_alarm(&r, Monitor::HeadingCourse).expect("heading alarm");
    assert!((600.0..=720.0).contains(&t), "{t}");
    assert!(r.runs.iter().all(|x| x.start_s >= 600.0), "{:?}", r.runs);
}

#[test]
fn a_drag_along_the_track_shows_against_the_speed_log() {
    let mut d = drag(600.0);
    d.bearing_rel_deg = 0.0;
    let r = run_text(&voyage(1500.0, Some(d)), &vessel());
    let t = first_alarm(&r, Monitor::SpeedLog).expect("speed-log alarm");
    assert!((600.0..=800.0).contains(&t), "{t}");
}

#[test]
fn counterfeit_signals_of_equal_power_collapse_the_c_n0_spread() {
    let mut d = drag(600.0);
    d.cn0_common_dbhz = Some(46.0);
    let r = run_text(&voyage(1500.0, Some(d)), &vessel());
    let t = first_alarm(&r, Monitor::Cn0Spread).expect("spread alarm");
    assert!((600.0..=700.0).contains(&t), "{t}");
}

fn edited(duration_s: f64, f: impl Fn(&mut kshana::receiver_trust::LogEpoch)) -> TrustResult {
    let mut tl = read_nmea(&voyage(duration_s, None)).unwrap();
    for e in tl.epochs.iter_mut() {
        f(e);
    }
    run_monitors(&tl, None, &vessel()).unwrap()
}

#[test]
fn every_satellite_rising_together_is_caught_but_one_satellite_is_not() {
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            for c in e.cn0.iter_mut() {
                c.cn0_dbhz += 5.0;
            }
        }
    });
    let t = first_alarm(&r, Monitor::Cn0Rise).expect("rise alarm");
    assert!((700.0..=710.0).contains(&t), "{t}");
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            if let Some(c) = e.cn0.first_mut() {
                c.cn0_dbhz += 15.0;
            }
        }
    });
    assert_eq!(first_alarm(&r, Monitor::Cn0Rise), None);
}

#[test]
fn receiver_security_reports_and_a_failed_osnma_status_are_extra_monitors() {
    use kshana::receiver_trust::OsnmaStatus;
    let r = edited(900.0, |e| {
        let m = e.marine.as_mut().unwrap();
        // Spoofing indicated from 500 s, jamming at warning from 600 s, OSNMA failure
        // from 700 s; before that the receiver reports all clear.
        m.sec_spoof_state = Some(if e.t_s >= 500.0 { 2 } else { 1 });
        m.sec_jam_state = Some(if e.t_s >= 600.0 { 2 } else { 1 });
        m.osnma = Some(if e.t_s >= 700.0 {
            OsnmaStatus::Failed
        } else {
            OsnmaStatus::Authenticated
        });
    });
    assert_eq!(first_alarm(&r, Monitor::SecSpoof), Some(500.0));
    assert_eq!(first_alarm(&r, Monitor::SecJam), Some(600.0));
    assert_eq!(first_alarm(&r, Monitor::Osnma), Some(700.0));
    // Not reporting at all is not an alarm and the monitors are then not run.
    let r = edited(900.0, |_| {});
    assert!(!r.monitors_run.contains(&Monitor::Osnma));
}

#[test]
fn a_position_step_that_the_reported_velocity_does_not_explain_is_kinematic() {
    // 600 m north from 700 s on, with the speed and course left as they were.
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            if let Some(f) = e.fix.as_mut() {
                f.lat_deg += 0.0054;
            }
        }
    });
    let t = first_alarm(&r, Monitor::Kinematic).expect("kinematic alarm");
    assert!((700.0..=702.0).contains(&t), "{t}");
}

#[test]
fn an_impossible_implied_speed_is_kinematic_even_without_a_reported_velocity() {
    let r = edited(1200.0, |e| {
        if let Some(m) = e.marine.as_mut() {
            m.sog_kn = None;
            m.cog_deg = None;
        }
        if e.t_s >= 700.0 {
            if let Some(f) = e.fix.as_mut() {
                f.lat_deg += 0.0054;
            }
        }
    });
    assert!(first_alarm(&r, Monitor::Kinematic).is_some());
}

#[test]
fn a_climbing_antenna_fails_the_sea_level_check() {
    let r = edited(1200.0, |e| {
        if e.t_s >= 700.0 {
            if let Some(m) = e.marine.as_mut() {
                m.alt_msl_m = m.alt_msl_m.map(|a| a + 40.0);
            }
        }
    });
    let t = first_alarm(&r, Monitor::SeaLevel).expect("sea-level alarm");
    assert!((700.0..=710.0).contains(&t), "{t}");
}

#[test]
fn time_running_backwards_or_jumping_fails_time_consistency() {
    for step in [-3.0, 9.0] {
        let r = edited(900.0, |e| {
            if e.t_s == 500.0 {
                e.marine.as_mut().unwrap().time_step_s = Some(step);
            }
        });
        assert_eq!(first_alarm(&r, Monitor::TimeConsistency), Some(500.0));
    }
    // A single dropped epoch (a 2 s step at 1 Hz) is a dropout, not a fault.
    let r = edited(900.0, |e| {
        if e.t_s == 500.0 {
            e.marine.as_mut().unwrap().time_step_s = Some(2.0);
        }
    });
    assert_eq!(first_alarm(&r, Monitor::TimeConsistency), None);
}

#[test]
fn the_receiver_clock_departing_from_the_host_clock_is_caught() {
    let r = edited(900.0, |e| {
        let skew = if e.t_s >= 500.0 { 4.0 } else { 0.0 };
        e.marine.as_mut().unwrap().arrival_s = Some(e.t_s + 0.05 + skew);
    });
    let t = first_alarm(&r, Monitor::TimeConsistency).expect("time alarm");
    assert!((500.0..=506.0).contains(&t), "{t}");
}

#[test]
fn a_declared_heading_sensor_that_is_not_in_the_log_is_an_error() {
    let text: String = voyage(300.0, None)
        .lines()
        .filter(|l| !l.contains("HDT") && !l.contains("VHW"))
        .map(|l| format!("{l}\n"))
        .collect();
    let e = run_monitors(&read_nmea(&text).unwrap(), None, &vessel()).unwrap_err();
    assert!(e.contains("heading_sensor"), "{e}");
    // Not declared: the heading check simply does not run.
    let mut cfg = vessel();
    cfg.platform.heading_sensor = false;
    let r = run_monitors(&read_nmea(&text).unwrap(), None, &cfg).unwrap();
    assert!(!r.monitors_run.contains(&Monitor::HeadingCourse));
}

#[test]
fn decisions_are_causal_truncating_a_log_never_changes_earlier_epochs() {
    let text = voyage(1500.0, Some(drag(600.0)));
    let full = run_text(&text, &vessel());
    let tl = read_nmea(&text).unwrap();
    for cut in [650usize, 900, 1200] {
        let mut part = tl.clone();
        part.epochs.truncate(cut);
        let r = run_monitors(&part, None, &vessel()).unwrap();
        assert_eq!(r.epochs.len(), cut);
        assert_eq!(r.epochs[..], full.epochs[..cut], "cut at {cut}");
    }
}
