// SPDX-License-Identifier: AGPL-3.0-only
//! Live mode on synthetic vessel streams (text generated by `receiver_trust::synth`):
//! the same scores as a file, and what the gate does.

use kshana::receiver_trust::ingest::read_nmea;
use kshana::receiver_trust::live::{
    parse_live_scenario, EpochReport, GateAction, LiveEngine, LiveOut,
};
use kshana::receiver_trust::monitors::{run_monitors, TrustState};
use kshana::receiver_trust::synth::{synth_voyage, DragSpec, VoyageSpec};

const SESSION: &str = "kind = \"receiver-trust\"\n\
    [platform]\nkind = \"vessel\"\nantenna_height_m = 18.0\nheading_sensor = true\n";

fn voyage(duration_s: f64, drag: Option<DragSpec>) -> String {
    synth_voyage(&VoyageSpec {
        duration_s,
        drag,
        ..Default::default()
    })
}

fn drag(onset_s: f64) -> DragSpec {
    DragSpec {
        onset_s,
        accel_mps2: 0.02,
        speed_mps: 3.0,
        bearing_rel_deg: 90.0,
        cn0_common_dbhz: Some(46.0),
        cn0_ramp_s: 60.0,
    }
}

/// Feed a text line by line, one second of arrival time per GGA, and collect everything.
fn stream(engine: &mut LiveEngine, text: &str) -> LiveOut {
    let mut all = LiveOut::default();
    let mut second = -1.0_f64;
    let mut n = 0u32;
    for line in text.lines() {
        if line.contains("GGA") {
            second += 1.0;
            n = 0;
        }
        n += 1;
        let out = engine.feed_line(
            format!("{line}\r\n").as_bytes(),
            second + 0.01 * f64::from(n),
        );
        all.forward.extend(out.forward);
        all.reports.extend(out.reports);
    }
    let out = engine.finish();
    all.forward.extend(out.forward);
    all.reports.extend(out.reports);
    all
}

#[test]
fn live_scores_equal_the_scores_of_the_same_text_read_as_a_log() {
    let text = voyage(1500.0, Some(drag(600.0)));
    let scn = parse_live_scenario(SESSION).unwrap();
    let mut engine = LiveEngine::new(&scn, false).unwrap();
    let live = stream(&mut engine, &text);
    let batch = run_monitors(&read_nmea(&text).unwrap(), None, &scn.monitors).unwrap();
    assert_eq!(live.reports.len(), batch.epochs.len());
    assert!(live.forward.is_empty(), "the gate is off");
    let mut compared = 0;
    for (l, b) in live.reports.iter().zip(&batch.epochs) {
        assert_eq!(l.t_s, b.t_s);
        assert_eq!(l.state, b.state, "t = {}", b.t_s);
        assert_eq!(l.alarms, b.alarms, "t = {}", b.t_s);
        if let Some(s) = &b.score {
            assert_eq!(l.score, Some(s.score), "t = {}", b.t_s);
            assert_eq!(l.deductions, s.deductions, "t = {}", b.t_s);
            compared += 1;
        } else {
            assert_eq!(l.state, TrustState::Calibrating);
        }
    }
    assert_eq!(compared, 1441);
    assert!(live.reports.iter().all(|r| r.gate == GateAction::Off));
}

#[test]
fn a_cycle_is_complete_when_the_stream_goes_quiet_and_not_before() {
    let scn = parse_live_scenario(SESSION).unwrap();
    let mut engine = LiveEngine::new(&scn, true).unwrap();
    let text = voyage(5.0, None);
    let first_cycle: Vec<&str> = {
        let mut it = text.lines();
        let mut v = vec![it.next().unwrap()];
        v.extend(it.take_while(|l| !l.contains("GGA")));
        v
    };
    for (i, l) in first_cycle.iter().enumerate() {
        let out = engine.feed_line(format!("{l}\r\n").as_bytes(), 10.0 + 0.01 * i as f64);
        assert!(out.reports.is_empty() && out.forward.is_empty());
    }
    let last = 10.0 + 0.01 * (first_cycle.len() - 1) as f64;
    // A cycle is cut short only by a stall, not by the pause before a slower instrument's
    // sentence (a gyro a few tenths of a second behind the receiver).
    assert_eq!(engine.idle(last + 0.8), LiveOut::default(), "not yet quiet");
    let out = engine.idle(last + 1.6);
    assert_eq!(out.reports.len(), 1);
    // Calibrating: forwarded unchanged, then the $PKSHT for the epoch.
    assert_eq!(out.forward.len(), first_cycle.len() + 1);
    for (f, l) in out.forward.iter().zip(&first_cycle) {
        assert_eq!(f, format!("{l}\r\n").as_bytes());
    }
    let tail = String::from_utf8(out.forward.last().unwrap().clone()).unwrap();
    assert!(tail.starts_with("$PKSHT,1,080000.00,,C,P,*"), "{tail}");
    assert!(tail.ends_with("\r\n"));
    // Nothing left to complete.
    assert_eq!(engine.idle(last + 5.0), LiveOut::default());
}

/// Replace the latitude of the GGA and RMC of epochs `from..to` by one 11 km away.
fn with_glitch(text: &str, from: u32, to: u32) -> String {
    let mut epoch = -1i64;
    let mut out = String::new();
    for line in text.lines() {
        if line.contains("GGA") {
            epoch += 1;
        }
        let in_glitch = (from as i64..to as i64).contains(&epoch);
        if in_glitch && (line.contains("GGA") || line.contains("RMC")) {
            let body = &line[1..line.find('*').unwrap()];
            let mut f: Vec<String> = body.split(',').map(str::to_string).collect();
            let lat_at = if line.contains("GGA") { 2 } else { 3 };
            f[lat_at] = "5440.00000".into();
            let b = f.join(",");
            let ck = b.bytes().fold(0u8, |a, c| a ^ c);
            out.push_str(&format!("${b}*{ck:02X}\n"));
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

#[test]
fn the_gate_withholds_an_untrusted_fix_and_releases_it_after_the_stated_time() {
    let scn = parse_live_scenario(&format!("{SESSION}[live]\ngate_release_s = 20.0\n")).unwrap();
    let text = with_glitch(&voyage(1000.0, None), 700, 720);
    let mut engine = LiveEngine::new(&scn, true).unwrap();
    let out = stream(&mut engine, &text);

    let by_t = |t: f64| -> &EpochReport { out.reports.iter().find(|r| r.t_s == t).unwrap() };
    assert_eq!(by_t(650.0).gate, GateAction::Passed);
    assert_eq!(by_t(650.0).state, TrustState::Nominal);
    // Untrusted from the glitch on, withheld at once.
    assert_eq!(by_t(701.0).state, TrustState::Untrusted);
    assert_eq!(by_t(701.0).gate, GateAction::Withheld);
    assert!(by_t(701.0).deductions.iter().any(|d| d.points > 0.0));
    // Released only after 20 s out of the untrusted band, and then for good.
    let last_untrusted = out
        .reports
        .iter()
        .filter(|r| r.state == TrustState::Untrusted)
        .map(|r| r.t_s)
        .fold(0.0, f64::max);
    let released = out
        .reports
        .iter()
        .find(|r| r.t_s > last_untrusted && r.gate == GateAction::Passed)
        .unwrap()
        .t_s;
    assert!(
        released - last_untrusted >= 20.0,
        "{released} {last_untrusted}"
    );
    assert!(
        released - last_untrusted <= 22.0,
        "{released} {last_untrusted}"
    );
    assert!(out
        .reports
        .iter()
        .filter(|r| r.t_s >= released)
        .all(|r| r.gate == GateAction::Passed));

    // The forwarded stream: every line of a trusted cycle is the input line, every fix of a
    // withheld cycle is marked invalid, and each epoch has its $PKSHT.
    let forwarded: String = out
        .forward
        .iter()
        .map(|l| String::from_utf8(l.clone()).unwrap())
        .collect();
    let tl = read_nmea(&forwarded).unwrap();
    assert_eq!(tl.skipped_records, 0, "every sentence has a valid checksum");
    let invalid: Vec<f64> = tl
        .epochs
        .iter()
        .filter(|e| e.marine.as_ref().and_then(|m| m.fix_valid) == Some(false))
        .map(|e| e.t_s)
        .collect();
    let withheld: Vec<f64> = out
        .reports
        .iter()
        .filter(|r| r.gate == GateAction::Withheld)
        .map(|r| r.t_s)
        .collect();
    assert_eq!(invalid, withheld);
    assert!(forwarded.matches("$PKSHT,").count() == out.reports.len());
    let input_lines: std::collections::HashSet<&str> = text.lines().collect();
    for l in forwarded.lines().filter(|l| !l.starts_with("$PKSHT")) {
        let is_input = input_lines.contains(l);
        let is_marked = l.contains("GGA,") && l.split(',').nth(6) == Some("0")
            || l.contains("RMC,") && l.split(',').nth(2) == Some("V")
            || l.contains("VTG,") && l.contains(",N*");
        assert!(is_input || is_marked, "{l}");
    }
}

#[test]
fn with_the_gate_off_nothing_is_forwarded_and_with_it_on_a_clean_stream_passes_unchanged() {
    let scn = parse_live_scenario(SESSION).unwrap();
    let text = voyage(300.0, None);
    let mut on = LiveEngine::new(&scn, true).unwrap();
    let out = stream(&mut on, &text);
    let forwarded: Vec<String> = out
        .forward
        .iter()
        .map(|l| String::from_utf8(l.clone()).unwrap())
        .filter(|l| !l.starts_with("$PKSHT"))
        .map(|l| l.trim_end().to_string())
        .collect();
    let input: Vec<String> = text.lines().map(str::to_string).collect();
    assert_eq!(forwarded, input);
    assert!(out.reports.iter().all(|r| r.gate == GateAction::Passed));
}

#[test]
fn live_needs_a_vessel() {
    let scn = parse_live_scenario("kind = \"receiver-trust\"\n").unwrap();
    assert!(LiveEngine::new(&scn, false)
        .err()
        .unwrap()
        .contains("vessel"));
}

#[test]
fn json_lines_carry_the_score_the_reasons_and_the_gate() {
    let scn = parse_live_scenario(SESSION).unwrap();
    let mut engine = LiveEngine::new(&scn, false).unwrap();
    let out = stream(&mut engine, &voyage(100.0, None));
    let v: serde_json::Value = serde_json::from_str(&out.reports[80].to_json_line()).unwrap();
    assert_eq!(v["seq"], 81);
    assert_eq!(v["state"], "nominal");
    assert_eq!(v["score"], 100.0);
    assert_eq!(v["gate"], "off");
    assert!(v["note"].is_null());
    // Schema 1.1: the receiver-reported position, appended after `note`.
    let line = out.reports[80].to_json_line();
    assert!(line.find("\"note\"").unwrap() < line.find("\"position\"").unwrap());
    assert!(line.find("\"position\"").unwrap() < line.find("\"advisory\"").unwrap());
    assert!(line.contains("not type-approved navigation equipment"));
    assert!(v["advisory"].as_str().unwrap().contains("IEC 61108"));
    assert!((v["position"]["lat_deg"].as_f64().unwrap() - 54.6).abs() < 0.1);
    assert!(v["position"]["lon_deg"].is_number() && v["position"]["height_m"].is_number());
    assert!(v["deductions"].as_array().unwrap().is_empty());
    let c: serde_json::Value = serde_json::from_str(&out.reports[3].to_json_line()).unwrap();
    assert_eq!(c["state"], "calibrating");
    assert!(c["score"].is_null());
    assert!(
        c["position"]["lat_deg"].is_number(),
        "calibrating epochs carry it too"
    );
}

fn stream_with_arrival(engine: &mut LiveEngine, text: &str, from_second: f64) -> LiveOut {
    // Like `stream`, but the arrival clock starts at `from_second` (a continuing stream).
    let mut all = LiveOut::default();
    let mut second = from_second - 1.0;
    let mut n = 0u32;
    for line in text.lines() {
        if line.contains("GGA") {
            second += 1.0;
            n = 0;
        }
        n += 1;
        let out = engine.feed_line(
            format!("{line}\r\n").as_bytes(),
            second + 0.01 * f64::from(n),
        );
        all.forward.extend(out.forward);
        all.reports.extend(out.reports);
    }
    all
}

const SHORT_CAL: &str = "kind = \"receiver-trust\"\n[monitors]\ncalibration_s = 20.0\n\
    [platform]\nkind = \"vessel\"\nantenna_height_m = 18.0\nheading_sensor = true\n";

#[test]
fn a_replay_of_receiver_time_into_the_calibration_window_is_never_calibration() {
    let scn = parse_live_scenario(SHORT_CAL).unwrap();
    let mut engine = LiveEngine::new(&scn, true).unwrap();
    let first = voyage(60.0, None);
    let mut all = stream(&mut engine, &first);
    // The first 20 s are sent again: the receiver's time has gone back into the window.
    let replay = voyage(20.0, None);
    let more = stream_with_arrival(&mut engine, &replay, 70.0);
    all.reports.extend(more.reports);
    let tail = engine.finish();
    all.reports.extend(tail.reports);
    let replayed: Vec<&EpochReport> = all.reports.iter().skip(61).collect();
    assert!(replayed.len() >= 20, "{}", replayed.len());
    // Epochs the replay reopened are flagged, scored and withheld, never calibrating or passed.
    let flagged: Vec<&&EpochReport> = replayed
        .iter()
        .filter(|r| {
            r.alarms
                .contains(&kshana::receiver_trust::monitors::Monitor::TimeConsistency)
        })
        .collect();
    assert!(!flagged.is_empty());
    assert!(replayed.iter().all(|r| r.state != TrustState::Calibrating));
    assert!(replayed.iter().all(|r| r.state == TrustState::Untrusted));
    assert!(replayed.iter().all(|r| r.gate == GateAction::Withheld));
    assert!(flagged[0].note.as_deref().unwrap().contains("backwards"));
}

#[test]
fn a_monitor_error_after_calibration_fails_closed_and_the_gate_withholds() {
    // A declared heading sensor that the stream never sends.
    let scn = parse_live_scenario(SHORT_CAL).unwrap();
    let mut engine = LiveEngine::new(&scn, true).unwrap();
    let text: String = voyage(60.0, None)
        .lines()
        .filter(|l| !l.contains("HDT") && !l.contains("VHW"))
        .map(|l| format!("{l}\n"))
        .collect();
    let out = stream(&mut engine, &text);
    let after: Vec<&EpochReport> = out.reports.iter().filter(|r| r.t_s >= 20.0).collect();
    assert!(!after.is_empty());
    for r in &after {
        assert_eq!(r.state, TrustState::Untrusted, "t = {}", r.t_s);
        assert_eq!(r.gate, GateAction::Withheld);
        assert_eq!(r.score, None);
        assert!(r.note.as_deref().unwrap().contains("heading_sensor"));
    }
    let fwd = String::from_utf8(out.forward.concat()).unwrap();
    assert!(
        fwd.contains("$PKSHT,1,080040.00,,U,W,*"),
        "band U, no score"
    );
}

#[test]
fn the_pksht_time_is_right_whether_or_not_the_stream_gave_a_date() {
    // GGA only: the label has no date and reads "... UTC (date not in log)".
    let scn = parse_live_scenario(SESSION).unwrap();
    let mut engine = LiveEngine::new(&scn, true).unwrap();
    let gga = |t: &str| {
        let body = format!("GPGGA,{t},5430.0000,N,01830.0000,E,1,10,0.9,18.4,M,26.5,M,,");
        let ck = body.bytes().fold(0u8, |a, b| a ^ b);
        format!("${body}*{ck:02X}\r\n")
    };
    engine.feed_line(gga("123519.00").as_bytes(), 0.0);
    let out = engine.feed_line(gga("123520.00").as_bytes(), 1.0);
    let fwd = String::from_utf8(out.forward.concat()).unwrap();
    assert!(fwd.contains("$PKSHT,1,123519.00,,C,P,*"), "{fwd}");
}

#[test]
fn a_flood_of_lines_with_no_timed_sentence_cannot_grow_the_engine_without_bound() {
    let scn = parse_live_scenario(SESSION).unwrap();
    let mut engine = LiveEngine::new(&scn, true).unwrap();
    let mut forwarded = 0usize;
    for i in 0..12_000u32 {
        let l = format!("$GPGSV,1,1,01,03,62,040,45*{:02X}\r\n", i % 256);
        forwarded += engine.feed_line(l.as_bytes(), 0.0).forward.len();
    }
    // Cycles of at most 5,000 lines are completed and forwarded as they fill.
    assert!(forwarded >= 10_000, "{forwarded}");
}
