#!/usr/bin/env python3
"""History base for the LS+AR Earth-orientation predictor oracle (M073, round 2).

For every date from 1 900 days before the first archived issue's MJD0 to the last MJD0,
writes the value a user would have had from the archived IERS Bulletin A issues: the value
printed in the most recent issue whose "COMBINED EARTH ORIENTATION PARAMETERS" table
tabulates that date, or, for dates no archived issue tabulates (before 2022-12-29), the
Bulletin B final of the frozen 2026-09-30 finals2000A.all.

The test takes from this file only dates at least 21 days before an issue's MJD0 (the last
21 days come from that issue's own as-issued rows). The script asserts that, for every
issue, every base value it would use from a Bulletin A table was printed by an issue with
an earlier MJD0 than that issue, so no value is from the future.

Inputs: $KSHANA_ORACLES/data/iers/bulletinA/ (Vol. XXXVI-XXXIX) and finals2000A.all, as in
tests/fixtures/eop_bulletin_a_vintages_oracle/ (whose generate.py parsers are reused).

    source ~/Code/kshana-oracles/env.sh
    "$ORACLE_PY" tests/fixtures/operational_eop_ls_ar_oracle/generate.py
"""

import glob
import hashlib
import importlib.util
import os

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location(
    "v", os.path.join(HERE, "..", "eop_bulletin_a_vintages_oracle", "generate.py")
)
V = importlib.util.module_from_spec(spec)
spec.loader.exec_module(V)


def main():
    issues = sorted(
        (V.parse_issue(p) for p in glob.glob(os.path.join(V.BULL_DIR, "bulletina-*.txt"))),
        key=lambda d: d["mjd0"],
    )
    finals = V.parse_finals_b(V.FINALS)
    latest = {}  # mjd -> (issuing mjd0, value)
    for iss in issues:
        for m, v in iss["combined"].items():
            latest[m] = (iss["mjd0"], v)
    vint = [l.split(",") for l in open(os.path.join(HERE, "..", "eop_bulletin_a_vintages_oracle", "vintages.csv"))
            if l[0].isdigit()]
    scored = sorted({int(r[1]) for r in vint})
    lo = scored[0] - 1900
    hi = scored[-1]
    out = ["mjd,x_arcsec,y_arcsec,ut1_utc_s,source,printed_by_mjd0"]
    for m in range(lo, hi + 1):
        if m in latest:
            src_mjd0, v = latest[m]
            out.append(f"{m},{v[0]},{v[1]},{v[2]},A,{src_mjd0}")
        else:
            xb, yb, ub = finals[m]
            out.append(f"{m},{xb},{yb},{ub},B,")
    # No look-ahead: for each scored issue, every A value older than MJD0-20 was printed
    # by an issue with an earlier MJD0.
    for m0 in scored:
        for m in range(lo, m0 - 20):
            if m in latest:
                assert latest[m][0] < m0, (m0, m, latest[m][0])
    finals_sha = hashlib.sha256(open(V.FINALS, "rb").read()).hexdigest()
    with open(os.path.join(HERE, "history_base.csv"), "w") as f:
        f.write(f"# Generated by generate.py; finals2000A.all sha256 {finals_sha}\n")
        f.write("\n".join(out) + "\n")
    nb = sum(1 for r in out[1:] if r.split(",")[4] == "B")
    print(f"dates {lo}..{hi}: {len(out) - 1} rows, {nb} from Bulletin B; scored issues {len(scored)}")


if __name__ == "__main__":
    main()
