#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Fixture for tests/jd2_sofa_time_oracle.rs.

Step 1 writes instants.csv from the fixed rules of the pre-registration (every leap second
1972-2016 with six instants around it, two fixed instants, 60 seeded random instants).
Step 2 runs the oracle, pyerfa (ERFA, the BSD-licensed release of the SOFA routines):
erfa.dtf2d("UTC", ...), erfa.utctai and erfa.taiutc, and writes erfa.csv.

Run from the repository root:
    ~/Code/kshana-oracles/.venv13/bin/python tests/fixtures/jd2_sofa_time_oracle/generate_jd2_sofa_time_oracle.py
"""
import csv
import random
import sys
from pathlib import Path

import erfa

DIR = Path(__file__).resolve().parent

# Days that ended in a leap second (IERS Bulletin C), 1972-06-30 to 2016-12-31.
LEAP_DAYS = [
    (1972, 6, 30), (1972, 12, 31), (1973, 12, 31), (1974, 12, 31), (1975, 12, 31),
    (1976, 12, 31), (1977, 12, 31), (1978, 12, 31), (1979, 12, 31), (1981, 6, 30),
    (1982, 6, 30), (1983, 6, 30), (1985, 6, 30), (1987, 12, 31), (1989, 12, 31),
    (1990, 12, 31), (1992, 6, 30), (1993, 6, 30), (1994, 6, 30), (1995, 12, 31),
    (1997, 6, 30), (1998, 12, 31), (2005, 12, 31), (2008, 12, 31), (2012, 6, 30),
    (2015, 6, 30), (2016, 12, 31),
]
assert len(LEAP_DAYS) == 27


def next_day(y, m, d):
    jd1, jd2 = erfa.cal2jd(y, m, d)
    y2, m2, d2, _ = erfa.jd2cal(jd1 + 1.0, jd2)
    return int(y2), int(m2), int(d2)


def instants():
    rows = []
    for (y, m, d) in LEAP_DAYS:
        for s in ("59.000000", "59.999999", "60.000000", "60.500000", "60.999999"):
            rows.append((y, m, d, 23, 59, s, "leap"))
        y2, m2, d2 = next_day(y, m, d)
        rows.append((y2, m2, d2, 0, 0, "0.000001", "leap"))
    rows.append((1972, 1, 1, 0, 0, "0.000000", "fixed"))
    rows.append((2026, 10, 2, 12, 34, "56.789012", "fixed"))
    rng = random.Random(20261002)
    lo1, lo2 = erfa.cal2jd(1972, 1, 1)  # 2400000.5, MJD of 00:00 on 1972-01-01
    hi1, hi2 = erfa.cal2jd(2026, 12, 31)
    for _ in range(60):
        k = rng.randint(0, int(round((hi1 + hi2) - (lo1 + lo2))))
        y, m, d, _ = erfa.jd2cal(lo1, lo2 + k)
        h = rng.randint(0, 23)
        mi = rng.randint(0, 59)
        us = rng.randint(0, 59_999_999)
        rows.append((int(y), int(m), int(d), h, mi, f"{us // 1_000_000}.{us % 1_000_000:06d}", "random"))
    return rows


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--instants-only":
        step = 1
    else:
        step = 2
    rows = instants()
    with open(DIR / "instants.csv", "w", newline="") as f:
        f.write("# year,month,day,hour,minute,second,kind (generated by generate_jd2_sofa_time_oracle.py)\n")
        w = csv.writer(f, lineterminator="\n")
        for r in rows:
            w.writerow(r)
    if step == 1:
        return
    with open(DIR / "erfa.csv", "w", newline="") as f:
        f.write(f"# pyerfa {erfa.__version__} (liberfa {erfa.version.erfa_version}): "
                "dtf2d(UTC) u1,u2; utctai(u1,u2) a1,a2; taiutc(a1,a2) b1,b2\n")
        w = csv.writer(f, lineterminator="\n")
        for (y, m, d, h, mi, s, _) in rows:
            u1, u2 = erfa.dtf2d("UTC", y, m, d, h, mi, float(s))
            a1, a2 = erfa.utctai(u1, u2)
            b1, b2 = erfa.taiutc(a1, a2)
            w.writerow([repr(float(x)) for x in (u1, u2, a1, a2, b1, b2)])


if __name__ == "__main__":
    main()
