#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Reference for tests/lunar_gauge_classification_scipy_oracle.rs (policy P2).

Builds 9x9 positive semi-definite Fisher matrices with constructed null spaces in the coupled
datum layout (rows 0..7 spatial, 7..9 temporal) and classifies each null space by subspace
intersection with SciPy/NumPy singular value decompositions. Kshana's rank formulas are not used.

Run: source ~/Code/kshana-oracles/env.sh; $ORACLE_PY gen_reference.py > cases.csv
"""
import sys

import numpy as np
import scipy
import scipy.linalg as sla

RCOND = 1e-8  # null-space threshold, relative to the largest singular value (pre-registered)
MIN_GAP = 1e6  # required ratio between the smallest kept and the largest null singular value
SEED = 20261001
VARIANTS = 4
NS, NT = 7, 2
rng = np.random.default_rng(SEED)


def unit(v):
    return v / np.linalg.norm(v)


def spatial():
    v = np.zeros(9)
    v[:NS] = rng.standard_normal(NS)
    return unit(v)


def temporal():
    v = np.zeros(9)
    v[NS:] = rng.standard_normal(NT)
    return unit(v)


def coupled():
    """A direction with spatial and temporal parts each of norm >= 0.1 (here 0.3 to 0.95)."""
    a = rng.uniform(0.3, 1.27)  # angle: cos and sin both >= ~0.3
    v = np.zeros(9)
    v[:NS] = np.cos(a) * unit(rng.standard_normal(NS))
    v[NS:] = np.sin(a) * unit(rng.standard_normal(NT))
    return v


def generic(d):
    return [unit(rng.standard_normal(9)) for _ in range(d)]


def axis(i):
    v = np.zeros(9)
    v[i] = 1.0
    return v


# name -> generator of null-space spanning vectors (re-drawn per subspace, fixed across variants)
SPECS = [
    ("full_rank", lambda: []),
    ("one_spatial", lambda: [spatial()]),
    ("one_temporal", lambda: [temporal()]),
    ("two_temporal_axes", lambda: [axis(7), axis(8)]),
    ("spatial_axis_plus_rate_axis", lambda: [axis(0), axis(8)]),
    ("direct_sum_1s_1t", lambda: [spatial(), temporal()]),
    ("direct_sum_2s_1t", lambda: [spatial(), spatial(), temporal()]),
    ("direct_sum_3s_2t", lambda: [spatial(), spatial(), spatial(), temporal(), temporal()]),
    ("one_coupled", lambda: [coupled()]),
    ("two_coupled", lambda: [coupled(), coupled()]),
    ("generic_3", lambda: generic(3)),
    ("generic_4", lambda: generic(4)),
    ("generic_7", lambda: generic(7)),
    ("generic_8", lambda: generic(8)),
    ("spatial_plus_coupled", lambda: [spatial(), coupled()]),
    ("temporal_plus_coupled", lambda: [temporal(), coupled()]),
    ("1s_1t_1c", lambda: [spatial(), temporal(), coupled()]),
    ("2s_1c", lambda: [spatial(), spatial(), coupled()]),
]


def null_dim(mat):
    """dim null(mat) by SVD at RCOND, with the spectral-gap precondition asserted."""
    s = np.linalg.svd(mat, compute_uv=False)
    smax = s[0]
    n_cols = mat.shape[1]
    full = np.zeros(n_cols)
    full[: len(s)] = s
    kept = full[full > RCOND * smax]
    nulls = full[full <= RCOND * smax]
    if len(kept) and len(nulls):
        assert kept.min() / max(nulls.max(), 1e-300) >= MIN_GAP, (kept.min(), nulls.max())
    ns = sla.null_space(mat, rcond=RCOND)
    assert ns.shape[1] == len(nulls), (ns.shape, len(nulls))
    return ns.shape[1]


def classify(F):
    d = null_dim(F)
    e_t = np.zeros((NT, 9))
    e_t[:, NS:] = np.eye(NT)
    e_s = np.zeros((NS, 9))
    e_s[:, :NS] = np.eye(NS)
    dim_spatial = null_dim(np.vstack([F, e_t]))  # N(F) with temporal coordinates zero
    dim_temporal = null_dim(np.vstack([F, e_s]))  # N(F) with spatial coordinates zero
    coupled_dim = d - dim_spatial - dim_temporal
    assert coupled_dim >= 0
    _, s, vt = np.linalg.svd(F)
    v = vt[s <= RCOND * s[0]].T  # 9 x d
    p = v @ v.T
    p_st = np.linalg.norm(p[:NS, NS:], "fro")
    return d, dim_spatial, dim_temporal, coupled_dim, p_st


def build(null_vecs):
    d = len(null_vecs)
    if d:
        n = sla.orth(np.array(null_vecs).T)  # orthonormal basis of the null space, 9 x d
        assert n.shape[1] == d
    else:
        n = np.zeros((9, 0))
    comp = sla.null_space(n.T) if d else np.eye(9)  # orthonormal complement, 9 x (9-d)
    out = []
    for _ in range(VARIANTS):
        q_r = sla.qr(rng.standard_normal((9 - d, 9 - d)))[0] if d < 9 else None
        w = comp @ q_r
        lam = 10.0 ** rng.uniform(-3.0, 0.0, 9 - d)
        lam[0] = 1.0
        F = w @ np.diag(lam) @ w.T
        if d:
            q_n = sla.qr(rng.standard_normal((d, d)))[0]  # random orthonormal re-basis
            nb = n @ q_n
            mu = 10.0 ** rng.uniform(-15.0, -13.0, d)
            F = F + nb @ np.diag(mu) @ nb.T
        F = 0.5 * (F + F.T)
        out.append(F)
    return out


def main():
    w = sys.stdout.write
    w("# Reference for tests/lunar_gauge_classification_scipy_oracle.rs, generated by gen_reference.py\n")
    w(f"# NumPy {np.__version__}, SciPy {scipy.__version__} (BSD-3-Clause); seed {SEED}; rcond {RCOND}\n")
    w("# Matrix entries are written with 17 significant digits; the oracle classifies the parsed values.\n")
    cols = ["case", "subspace"] + [f"f{i}{j}" for i in range(9) for j in range(9)]
    cols += ["defect", "dim_spatial", "dim_temporal", "coupled_dim", "p_st_norm"]
    w(",".join(cols) + "\n")
    k = 0
    for name, gen in SPECS:
        for F in build(gen()):
            txt = [f"{x:.17e}" for x in F.ravel()]
            Fp = np.array([float(t) for t in txt]).reshape(9, 9)  # classify exactly what is committed
            d, sp, tp, cd, pst = classify(Fp)
            w(",".join([str(k), name] + txt + [str(d), str(sp), str(tp), str(cd), f"{pst:.17e}"]) + "\n")
            k += 1


if __name__ == "__main__":
    main()
