#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Writes the synthetic input files for the interference-map examples.

Everything here is made up: coordinates sit in the open mid-Atlantic, identifiers are
labels like SYN-A-003, and the "island" is a rectangle. No real aircraft, vessel or
observation is represented. The output is a pure function of this script (no random
numbers), so the committed inputs can be regenerated byte for byte:

    python3 examples/interference-map/generate_inputs.py
"""
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
IN = os.path.join(HERE, "input")
os.makedirs(IN, exist_ok=True)


def adsb():
    rows = ["timestamp,aircraft_id,lat,lon,alt_baro_ft,nic,nacp,source_type"]
    # Far-away cells where each aircraft sends its "good" reports (the equipment baseline).
    far = [(20.1, -60.1), (22.1, -60.1), (24.1, -60.1)]

    def aircraft(label, lat, lon, hit, idx):
        flat, flon = far[idx % 3]
        for k in range(6):
            rows.append(f"2026-03-01T09:{k:02d}:00Z,{label},{flat},{flon},33000,10,11,adsb_icao")
        nic, nacp = (0, 0) if hit else (9, 10)
        for k in range(4):
            rows.append(f"2026-03-01T10:{k:02d}:00Z,{label},{lat},{lon},33000,{nic},{nacp},adsb_icao")

    # Seven cells of 12 aircraft in a row along 30.2 N; the third has 7 affected aircraft.
    n = 0
    for cell in range(7):
        for a in range(12):
            aircraft(f"SYN-A-{cell}{a:02d}", 30.2, -50.3 + 0.5 * cell, cell == 2 and a < 7, n)
            n += 1
    # A cell with 7 aircraft observed, none with a baseline: published but unassessed.
    for a in range(7):
        label = f"SYN-B-{a:02d}"
        for k in range(4):
            rows.append(f"2026-03-01T10:{k:02d}:00Z,{label},31.2,-50.3,33000,0,0,adsb_icao")
    # A cell with 3 aircraft: below the publication minimum, so not in the output at all.
    for a in range(3):
        label = f"SYN-C-{a:02d}"
        for k in range(4):
            rows.append(f"2026-03-01T10:{k:02d}:00Z,{label},32.2,-50.3,33000,9,10,adsb_icao")
    with open(os.path.join(IN, "adsb.csv"), "w") as f:
        f.write("\n".join(rows) + "\n")


def ais():
    rows = ["timestamp,vessel_id,lat,lon,sog_kn"]

    def t(sec):
        return f"2026-03-01T{sec // 3600:02d}:{sec % 3600 // 60:02d}:{sec % 60:02d}Z"

    def traffic(prefix, lat0, lon0, n):
        for v in range(n):
            for k in range(6):
                rows.append(f"{t(36000 + k * 120)},{prefix}-{v:03d},{lat0 + 0.02 * v:.4f},{lon0 + 0.01 * k:.4f},12")

    # Four cells of ordinary traffic.
    traffic("SYN-T1", 30.1, -40.4, 8)
    traffic("SYN-T2", 30.6, -40.4, 8)
    traffic("SYN-T3", 31.1, -40.4, 8)
    traffic("SYN-T4", 31.6, -40.4, 8)
    # A cell where 6 vessels circle at 2 km radius (24 reports, about 1.2 turns).
    for v in range(6):
        for k in range(24):
            th = math.radians(20 * k)
            lat = 30.2 + 0.02 * v + 2000 * math.sin(th) / 111195.0
            lon = -39.7 + 2000 * math.cos(th) / (111195.0 * math.cos(math.radians(30.2)))
            rows.append(f"{t(40000 + k * 60)},SYN-C-{v:03d},{lat:.5f},{lon:.5f},9")
    # A cell inside the synthetic island: 6 vessels with positions on land.
    for v in range(6):
        for k in range(4):
            rows.append(f"{t(30000 + k * 600 + v * 7)},SYN-L-{v:03d},{31.2 + 0.02 * v:.4f},-39.7,5")
    # A cell with 3 vessels: below the publication minimum.
    for v in range(3):
        for k in range(3):
            rows.append(f"{t(20000 + k * 300)},SYN-F-{v:03d},{32.3 + 0.02 * v:.4f},-40.4,10")
    # A cell with 6 vessels of which 2 report 99 knots: flagged count of 2 is withheld.
    traffic("SYN-S", 32.1, -39.7, 4)
    for v in range(2):
        for k in range(4):
            rows.append(f"{t(50000 + k * 60)},SYN-X-{v:03d},{32.4 + 0.02 * v:.4f},-39.7,99")
    with open(os.path.join(IN, "ais.csv"), "w") as f:
        f.write("\n".join(rows) + "\n")
    # A synthetic island: one rectangle covering the cell at 31.0 to 31.5 N, 39.9 to 39.5 W.
    with open(os.path.join(IN, "land.geojson"), "w") as f:
        f.write('{"type":"Polygon","coordinates":[[[-39.95,31.05],[-39.45,31.05],[-39.45,31.45],[-39.95,31.45],[-39.95,31.05]]]}\n')


adsb()
ais()
