#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""SPICE reference for tests/body_orientation_spice_oracle.rs.

For each of the eighteen bodies of Kshana's solar-system catalogue and each of 41 epochs,
writes the rotation matrix from the J2000 frame to the body's IAU body-fixed frame as the
NAIF SPICE Toolkit computes it (spiceypy `pxform('J2000', 'IAU_<BODY>', et)`), from the NAIF
generic kernel pck00011.tpc, plus the body's GM (`bodvcd`, gm_de440.tpc) and RADII[0]
(`bodvcd`, pck00011.tpc). Calls no Kshana code.

Epochs (fixed in the pre-registration): et_k = (k - 20) * 70 000 000.5 s past J2000 TDB,
k = 0..40 (about 1955-08 to 2044-05).

Output: spice_orientation.csv beside this script, one row per (body, epoch):
    body,naif_id,et_s,r00,r01,r02,r10,r11,r12,r20,r21,r22
and spice_constants.csv: body,naif_id,gm_km3_s2,radii0_km (NA where the kernels carry none).

    source "$KSHANA_ORACLES/env.sh"
    $ORACLE_PY tests/fixtures/body_orientation_spice_oracle/generate_body_orientation_spice_oracle.py
"""

import hashlib
import os
import pathlib

import spiceypy as sp

HERE = pathlib.Path(__file__).resolve().parent
NAIF = pathlib.Path(os.environ["KSHANA_ORACLES"]) / "data" / "naif"
KERNELS = ["pck00011.tpc", "gm_de440.tpc"]
BODIES = [
    ("Sun", 10), ("Mercury", 199), ("Venus", 299), ("Earth", 399), ("Moon", 301), ("Mars", 499),
    ("Phobos", 401), ("Deimos", 402), ("Jupiter", 599), ("Io", 501), ("Europa", 502),
    ("Ganymede", 503), ("Callisto", 504), ("Saturn", 699), ("Titan", 606), ("Uranus", 799),
    ("Neptune", 899), ("Pluto", 999),
]
EPOCHS = [(k - 20) * 70_000_000.5 for k in range(41)]


def header():
    lines = ["# SPICE Toolkit %s through spiceypy %s; generated by %s"
             % (sp.tkvrsn("TOOLKIT"), sp.__version__, pathlib.Path(__file__).name)]
    for k in KERNELS:
        p = NAIF / k
        lines.append("# kernel %s sha256 %s" % (k, hashlib.sha256(p.read_bytes()).hexdigest()))
    return lines


def main():
    for k in KERNELS:
        sp.furnsh(str(NAIF / k))
    rows = header() + ["# body,naif_id,et_s,r00,r01,r02,r10,r11,r12,r20,r21,r22 (J2000 -> IAU_<BODY>)"]
    for name, code in BODIES:
        frame = "IAU_" + name.upper()
        for et in EPOCHS:
            m = sp.pxform("J2000", frame, et)
            vals = [repr(float(m[i][j])) for i in range(3) for j in range(3)]
            rows.append("%s,%d,%s,%s" % (name, code, repr(float(et)), ",".join(vals)))
    (HERE / "spice_orientation.csv").write_text("\n".join(rows) + "\n")

    consts = header() + ["# body,naif_id,gm_km3_s2,radii0_km"]
    for name, code in BODIES:
        gm = sp.bodvcd(code, "GM", 1)[1][0] if sp.bodfnd(code, "GM") else None
        r0 = sp.bodvcd(code, "RADII", 3)[1][0] if sp.bodfnd(code, "RADII") else None
        consts.append("%s,%d,%s,%s" % (name, code, "NA" if gm is None else repr(float(gm)),
                                       "NA" if r0 is None else repr(float(r0))))
    (HERE / "spice_constants.csv").write_text("\n".join(consts) + "\n")
    print("wrote", HERE / "spice_orientation.csv", "and", HERE / "spice_constants.csv")


if __name__ == "__main__":
    main()
