#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Enforce that every distribution surface versions in LOCKSTEP with the engine.
#
# The root Cargo.toml [package] version is the single source of truth. Every surface
# that carries its own version string must equal it, so a release can never ship one
# surface (crate / wheel / npm / JetBrains plugin / MCP image) at a different version
# than the others.
#
# Surfaces that genuinely need no check, because the version is read out of Cargo.toml at
# build time and is never written down anywhere a human can get it wrong:
#   - PyPI  : pyproject.toml `dynamic = ["version"]` -> maturin reads Cargo.toml
#   - crates: cargo publish reads Cargo.toml
#   - npm   : web/pkg/package.json is generated by wasm-pack from Cargo.toml at build
#             (gitignored — never committed, so it cannot drift)
#   - CITATION.cff / codemeta.json / .zenodo.json: pinned to the manifest by
#     tests/citation_metadata_doc_sync.rs
#
# release.yml, mcp-publish.yml and jetbrains-plugin.yml were listed there too, as
# "derive from the git tag". That was wrong, and it is the hole check 7 closes: deriving
# from the tag is not the same as needing no check, because the tag is a THIRD version
# string, typed by hand at release time, and nothing compared it to Cargo.toml. Those
# three publish the TAG's version (jetbrains-plugin.yml takes `refs/tags/vX.Y.Z` over
# gradle.properties; mcp-publish.yml stamps server.json and the ghcr image tag from it)
# while crates.io, PyPI and npm publish the MANIFEST's, so a single mis-cut tag ships
# crates.io / PyPI / npm at one version and the JetBrains Marketplace / ghcr / the MCP
# registry at another, under one release name.
set -euo pipefail

ver="$(grep -m1 '^version' Cargo.toml | sed -E 's/.*"([^"]+)".*/\1/')"
if [ -z "$ver" ]; then
  echo "FAIL: could not read [package] version from Cargo.toml" >&2
  exit 1
fi
majmin="$(printf '%s' "$ver" | cut -d. -f1,2)"

fail=0
note() { printf '  %s\n' "$1" >&2; }

# 1. README status badge (the documented version users see first).
if ! grep -q "Status: v${ver}" README.md; then
  echo "FAIL: README status badge does not match Cargo.toml version v${ver}." >&2
  grep -n '\*\*Status:' README.md >&2 || note "(no status badge found)"
  fail=1
fi

# 2. MCP companion crate — its own version, in lockstep.
mcp_ver="$(grep -m1 '^version' mcp/kshana-mcp/Cargo.toml | sed -E 's/.*"([^"]+)".*/\1/')"
if [ "$mcp_ver" != "$ver" ]; then
  echo "FAIL: mcp/kshana-mcp/Cargo.toml version ($mcp_ver) != engine ($ver)." >&2
  fail=1
fi

# 3. MCP crate's dependency on the published kshana crate — its major.minor requirement
#    must track the engine, or `cargo publish` of kshana-mcp cannot resolve the crate.
mcp_dep="$(grep -E '^kshana = ' mcp/kshana-mcp/Cargo.toml | sed -E 's/.*version = "([^"]+)".*/\1/')"
if [ "$mcp_dep" != "$majmin" ] && [ "$mcp_dep" != "$ver" ]; then
  echo "FAIL: mcp/kshana-mcp/Cargo.toml kshana dependency ($mcp_dep) does not track engine $majmin." >&2
  fail=1
fi

# 4. JetBrains plugin — pluginVersion, in lockstep (the publish workflow prefers the tag,
#    but the on-disk default must still match so local builds and non-tag dispatch agree).
jb_ver="$(grep -E '^pluginVersion' ide/jetbrains/gradle.properties | sed -E 's/.*= *//' | tr -d ' ')"
if [ "$jb_ver" != "$ver" ]; then
  echo "FAIL: ide/jetbrains/gradle.properties pluginVersion ($jb_ver) != engine ($ver)." >&2
  fail=1
fi

# 5. Web landing page (kshana.dev, web/index.html) — hand-authored HTML, not derived
#    from Cargo.toml, so its version strings drift silently every release unless checked
#    here. Enforce the JSON-LD softwareVersion (what crawlers read), the visible version
#    chip fallback (what a no-JS visitor sees), and the asset cache-busters in lockstep.
web="web/index.html"
for needle in \
  "\"softwareVersion\": \"${ver}\"" \
  ">v${ver}<" \
  "favicon.svg?v=${ver}" \
  "style.css?v=${ver}" \
  "app.js?v=${ver}"; do
  if ! grep -qF -- "$needle" "$web"; then
    echo "FAIL: $web is missing the v${ver} string: ${needle}" >&2
    fail=1
  fi
done

# 6. Registry front pages — README.crates.md / README.npm.md / README.pypi.md, and the
#    root README's own release badge. One hand-authored page per registry, generated by
#    nothing, so the release badge drifts silently. Measured from the tags: README.crates.md
#    shipped a v0.26.0 badge at v0.27.0, v0.27.1 AND v0.27.2 — three tagged releases —
#    and was corrected only by a hand-edit, because check 1 above reads one line of the
#    root README and this script never opened the other three files at all.
#    Both halves of the badge are checked. The shields URL is what renders; the alt text
#    is what a screen reader reads, and what a reader with images blocked sees. They are
#    two separate strings a hand-edit can move independently, and a half-corrected badge
#    is still a wrong badge.
for rdm in README.md README.crates.md README.npm.md README.pypi.md; do
  for needle in \
    "badge/release-v${ver}-" \
    "alt=\"Release v${ver}\""; do
    if ! grep -qF -- "$needle" "$rdm"; then
      echo "FAIL: $rdm release badge is not at v${ver} — missing: ${needle}" >&2
      grep -n 'badge/release-v' "$rdm" >&2 || note "(no release badge in this file)"
      fail=1
    fi
  done
done

# 8. JetBrains Marketplace change-notes — the listing text shipped with each version.
#
#    Checks 4 keeps the plugin's VERSION in lockstep, but the notes shown beside it on the
#    Marketplace are hand-written in plugin.xml and nothing read them: seven published
#    versions (0.23.0 through 0.27.2) served the byte-identical 0.22.0 notes. The newest
#    entry — the first <b>x.y.z</b> inside <change-notes> — must name the version being
#    shipped. When the plugin itself did not change, a one-line entry saying so is the
#    honest note ("the plugin is unchanged since 0.22.0; republished to track the engine"),
#    and it is still better than a listing that describes a release from months ago.
#    Plain HTML only: <change-notes> renders as HTML, so Markdown from the changelog
#    extractor would show literal ### and ** on the Marketplace.
PLUGIN_XML="ide/jetbrains/src/main/resources/META-INF/plugin.xml"
notes_ver="$(awk '/<change-notes>/{f=1} f' "$PLUGIN_XML" \
  | grep -oE '<b>[0-9]+\.[0-9]+\.[0-9]+</b>' | head -1 | sed -E 's#</?b>##g')"
if [ "$notes_ver" != "$ver" ]; then
  echo "FAIL: JetBrains change-notes' newest entry is ${notes_ver:-<none>}, but the plugin ships as v${ver}." >&2
  note "add a <b>${ver}</b> entry at the top of <change-notes> in ${PLUGIN_XML} — one line"
  note "stating the plugin is unchanged is fine when it is — so the Marketplace listing for"
  note "v${ver} does not describe an older release."
  fail=1
fi

# 7. The release TAG against the manifest.
#
#    Checks 1-6 compare files in the tree to each other, so a tree that is internally
#    consistent at 0.27.2 passes every one of them even while it is being released as
#    v0.28.0. Nothing anywhere made that comparison: a v0.28.0 tag cut on a 0.27.2 tree
#    would publish 0.27.2 to crates.io and PyPI under a 0.28.0 release name, and 0.28.0
#    to the JetBrains Marketplace and ghcr, and every gate would stay green.
#
#    This script already runs on the tag push, in release.yml `verify` and publish.yml
#    `gates`, both of them ahead of anything irreversible — so the comparison costs
#    nothing and fails the release in seconds rather than after the crate is public.
#
#    Asserted only when the ref is a release tag. GITHUB_REF_TYPE is "tag" or "branch" on
#    GitHub; when it says branch this is not a release however the ref is named. When it
#    is unset (a local run) the vX.Y.Z name shape alone decides, which is what lets this
#    be exercised by hand: GITHUB_REF_NAME=v9.9.9 scripts/check-version-sync.sh
#
#    Two refs deliberately fall through it: a PR (GITHUB_REF_NAME is "<n>/merge") and
#    release.yml's workflow_dispatch retry, where github.ref is the branch and the tag
#    lives in an input. The dispatch path is a re-run of a tag that was already checked
#    when it was pushed, so it is not a new hole; a tag pushed for the first time always
#    goes through the `push: tags` trigger and is checked here.
tag_checked="no release tag on this ref"
ref_name="${GITHUB_REF_NAME:-}"
if [ "${GITHUB_REF_TYPE:-tag}" = "tag" ] \
  && printf '%s' "$ref_name" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+'; then
  tag_ver="${ref_name#v}"
  if [ "$tag_ver" != "$ver" ]; then
    echo "FAIL: release tag ${ref_name} does not match Cargo.toml version v${ver}." >&2
    note "the tag and the manifest are two different version strings and this is the only"
    note "place they meet. Either the tag was cut on the wrong commit — move it — or the"
    note "manifest bump is missing: bump Cargo.toml to ${tag_ver}, re-run every surface"
    note "above, and re-tag. Do NOT publish from this tree."
    fail=1
  else
    tag_checked="release tag ${ref_name} matches the manifest"
  fi
fi

if [ "$fail" -ne 0 ]; then
  echo "Version drift detected — bring every surface to v${ver}." >&2
  exit 1
fi

echo "OK: every surface this script checks is at v${ver} — root README \"Status:\" line \
and release badge; README.crates.md / README.npm.md / README.pypi.md release badges; \
mcp/kshana-mcp version and its kshana dependency requirement; JetBrains pluginVersion \
and the newest Marketplace change-notes entry; \
web/index.html JSON-LD, version chip and 3 cache-busters; ${tag_checked}."
echo "    Not checked here, and not drifting: crates.io / PyPI / npm read the version out \
of Cargo.toml at build time; CITATION.cff, codemeta.json and .zenodo.json are pinned to \
the manifest by tests/citation_metadata_doc_sync.rs."
