#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Enforce that every distribution surface versions in LOCKSTEP with the engine.
#
# The root Cargo.toml [package] version is the single source of truth. Every surface
# that carries its own version string must equal it, so a release can never ship one
# surface (crate / wheel / npm / JetBrains plugin / MCP image) at a different version
# than the others.
#
# Surfaces that genuinely need no check, because the version is read out of Cargo.toml at
# build time and is never written down anywhere a human can get it wrong:
#   - PyPI  : pyproject.toml `dynamic = ["version"]` -> maturin reads Cargo.toml
#   - crates: cargo publish reads Cargo.toml
#   - npm   : web/pkg/package.json is generated by wasm-pack from Cargo.toml at build
#             (gitignored — never committed, so it cannot drift)
#   - CITATION.cff / codemeta.json / .zenodo.json: pinned to the manifest by
#     tests/citation_metadata_doc_sync.rs
#
# release.yml, mcp-publish.yml and jetbrains-plugin.yml were listed there too, as
# "derive from the git tag". That was wrong, and it is the hole check 7 closes: deriving
# from the tag is not the same as needing no check, because the tag is a THIRD version
# string, typed by hand at release time, and nothing compared it to Cargo.toml. Those
# three publish the TAG's version (jetbrains-plugin.yml takes `refs/tags/vX.Y.Z` over
# gradle.properties; mcp-publish.yml stamps server.json and the ghcr image tag from it)
# while crates.io, PyPI and npm publish the MANIFEST's, so a single mis-cut tag ships
# crates.io / PyPI / npm at one version and the JetBrains Marketplace / ghcr / the MCP
# registry at another, under one release name.
set -euo pipefail

ver="$(grep -m1 '^version' Cargo.toml | sed -E 's/.*"([^"]+)".*/\1/')"
if [ -z "$ver" ]; then
  echo "FAIL: could not read [package] version from Cargo.toml" >&2
  exit 1
fi
majmin="$(printf '%s' "$ver" | cut -d. -f1,2)"

fail=0
note() { printf '  %s\n' "$1" >&2; }

# 1. README status badge (the documented version users see first).
if ! grep -q "Status: v${ver}" README.md; then
  echo "FAIL: README status badge does not match Cargo.toml version v${ver}." >&2
  grep -n '\*\*Status:' README.md >&2 || note "(no status badge found)"
  fail=1
fi

# 2. MCP companion crate — its own version, in lockstep.
mcp_ver="$(grep -m1 '^version' mcp/kshana-mcp/Cargo.toml | sed -E 's/.*"([^"]+)".*/\1/')"
if [ "$mcp_ver" != "$ver" ]; then
  echo "FAIL: mcp/kshana-mcp/Cargo.toml version ($mcp_ver) != engine ($ver)." >&2
  fail=1
fi

# 3. MCP crate's dependency on the published kshana crate — its major.minor requirement
#    must track the engine, or `cargo publish` of kshana-mcp cannot resolve the crate.
mcp_dep="$(grep -E '^kshana = ' mcp/kshana-mcp/Cargo.toml | sed -E 's/.*version = "([^"]+)".*/\1/')"
if [ "$mcp_dep" != "$majmin" ] && [ "$mcp_dep" != "$ver" ]; then
  echo "FAIL: mcp/kshana-mcp/Cargo.toml kshana dependency ($mcp_dep) does not track engine $majmin." >&2
  fail=1
fi

# 4. JetBrains plugin — pluginVersion, in lockstep (the publish workflow prefers the tag,
#    but the on-disk default must still match so local builds and non-tag dispatch agree).
jb_ver="$(grep -E '^pluginVersion' ide/jetbrains/gradle.properties | sed -E 's/.*= *//' | tr -d ' ')"
if [ "$jb_ver" != "$ver" ]; then
  echo "FAIL: ide/jetbrains/gradle.properties pluginVersion ($jb_ver) != engine ($ver)." >&2
  fail=1
fi

# 5. The site (kshana.dev, web/) is ported in from a site build by web/tools/port_site.py,
#    not derived from Cargo.toml at release time, so its version strings drift silently
#    every release unless checked here. Enforce the home page's JSON-LD softwareVersion
#    (what crawlers read) and its visible version chip (what a visitor sees), the version
#    the Studio's install panel states (studio/channels.json), and the version the
#    port recorded in its manifest. A mismatch means: rebuild the site from this checkout
#    and rerun the port.
web="web/index.html"
for needle in \
  "\"softwareVersion\": \"${ver}\"" \
  ">v${ver}<"; do
  if ! grep -qF -- "$needle" "$web"; then
    echo "FAIL: $web is missing the v${ver} string: ${needle}" >&2
    fail=1
  fi
done
for f in web/studio/channels.json web/PORT-MANIFEST.json; do
  if ! grep -qE "^ *\"version\": \"${ver}\"" "$f"; then
    echo "FAIL: $f does not state version ${ver}; rebuild the site and rerun web/tools/port_site.py." >&2
    fail=1
  fi
done

# 6. Registry front pages — README.crates.md / README.npm.md / README.pypi.md, and the
#    root README's own release badge. One hand-authored page per registry, generated by
#    nothing, so the release badge drifts silently. Measured from the tags: README.crates.md
#    shipped a v0.26.0 badge at v0.27.0, v0.27.1 AND v0.27.2 — three tagged releases —
#    and was corrected only by a hand-edit, because check 1 above reads one line of the
#    root README and this script never opened the other three files at all.
#    Both halves of the badge are checked. The shields URL is what renders; the alt text
#    is what a screen reader reads, and what a reader with images blocked sees. They are
#    two separate strings a hand-edit can move independently, and a half-corrected badge
#    is still a wrong badge.
for rdm in README.md README.crates.md README.npm.md README.pypi.md; do
  for needle in \
    "badge/release-v${ver}-" \
    "alt=\"Release v${ver}\""; do
    if ! grep -qF -- "$needle" "$rdm"; then
      echo "FAIL: $rdm release badge is not at v${ver} — missing: ${needle}" >&2
      grep -n 'badge/release-v' "$rdm" >&2 || note "(no release badge in this file)"
      fail=1
    fi
  done
done

# 8. JetBrains Marketplace change-notes — the listing text shipped with each version.
#
#    Checks 4 keeps the plugin's VERSION in lockstep, but the notes shown beside it on the
#    Marketplace are hand-written in plugin.xml and nothing read them: seven published
#    versions (0.23.0 through 0.27.2) served the byte-identical 0.22.0 notes. The newest
#    entry — the first <b>x.y.z</b> inside <change-notes> — must name the version being
#    shipped. When the plugin itself did not change, a one-line entry saying so is the
#    honest note ("the plugin is unchanged since 0.22.0; republished to track the engine"),
#    and it is still better than a listing that describes a release from months ago.
#    Plain HTML only: <change-notes> renders as HTML, so Markdown from the changelog
#    extractor would show literal ### and ** on the Marketplace.
PLUGIN_XML="ide/jetbrains/src/main/resources/META-INF/plugin.xml"
notes_ver="$(awk '/<change-notes>/{f=1} f' "$PLUGIN_XML" \
  | grep -oE '<b>[0-9]+\.[0-9]+\.[0-9]+</b>' | head -1 | sed -E 's#</?b>##g')"
if [ "$notes_ver" != "$ver" ]; then
  echo "FAIL: JetBrains change-notes' newest entry is ${notes_ver:-<none>}, but the plugin ships as v${ver}." >&2
  note "add a <b>${ver}</b> entry at the top of <change-notes> in ${PLUGIN_XML} — one line"
  note "stating the plugin is unchanged is fine when it is — so the Marketplace listing for"
  note "v${ver} does not describe an older release."
  fail=1
fi

# 9. The MCP registry manifest — mcp/kshana-mcp/server.json. mcp-publish.yml re-stamps its
#    version and image tag from the release tag before publishing, so a stale committed
#    copy never reached the registry; but the committed file is what a reader of the
#    repository, and anyone running mcp-publisher by hand, sees, and it sat at 0.31.0
#    while 0.32.0 shipped. Both strings must name the engine version.
SERVER_JSON="mcp/kshana-mcp/server.json"
for needle in \
  "\"version\": \"${ver}\"" \
  "\"identifier\": \"ghcr.io/ashfordeou/kshana-mcp:${ver}\""; do
  if ! grep -qF -- "$needle" "$SERVER_JSON"; then
    echo "FAIL: $SERVER_JSON is not at ${ver} — missing: ${needle}" >&2
    fail=1
  fi
done

# 10. The README's worked example prints `kshana.version()` (Python) and `version()`
#     (JavaScript) as the first token of its expected-output comment. Every version
#     token on those two lines must be the engine's; the holdover numbers beside them
#     are pinned separately by tests/golden.rs.
for pat in '^# [0-9]+\.[0-9]+\.[0-9]+ [0-9]' '^// [0-9]+\.[0-9]+\.[0-9]+ [0-9]'; do
  lines="$(grep -nE "$pat" README.md || true)"
  if [ -z "$lines" ]; then
    echo "FAIL: README.md has no example output line matching ${pat}" >&2
    fail=1
    continue
  fi
  bad="$(printf '%s\n' "$lines" | grep -vE "^[0-9]+:(#|//) ${ver//./\\.} " || true)"
  if [ -n "$bad" ]; then
    echo "FAIL: README.md example output does not print version ${ver}:" >&2
    printf '%s\n' "$bad" | sed 's/^/  /' >&2
    fail=1
  fi
done

# 11. The site's version on every page, its llms.txt and its changelog page.
#
#     Check 5 reads only the home page. Every other page carries the same version twice,
#     in the header brand chip (<small>vX.Y.Z</small>) and in the footer
#     ("Kshana vX.Y.Z · by Ashforde"), and at 0.32.0 sixty-seven of them still said
#     v0.31.0 while index.html said v0.32.0. web/llms.txt states "Version X.Y.Z" to every
#     crawler that reads it, and web/docs/changelog.html must hold the newest released
#     CHANGELOG.md heading (compared with CHANGELOG.md, not Cargo.toml, so it stays
#     meaningful between releases).
#
#     These pages are written by the site build and ported in by web/tools/port_site.py,
#     so the fix is a re-port, not a hand-edit. KSHANA_VERSION_SYNC_SITE selects how a
#     mismatch is reported: "warn" prints WARN lines and does not fail; "strict" fails.
#     The default is strict since 0.33.0, the release that re-ported the site at its bump
#     commit (docs/RELEASING.md). Set KSHANA_VERSION_SYNC_SITE=warn to see the issues
#     without failing, for example while preparing a bump before the re-port.
#
#     Not checked, deliberately: "engine vX" / "Engine vX" run-provenance stamps (an
#     accurate record of the engine a figure was drawn with) and alt text describing an
#     image.
SITE_VERSION_MODE="${KSHANA_VERSION_SYNC_SITE:-strict}"
case "$SITE_VERSION_MODE" in
  warn|strict) ;;
  *) echo "FAIL: KSHANA_VERSION_SYNC_SITE must be warn or strict, not '${SITE_VERSION_MODE}'." >&2; exit 1 ;;
esac
site_issues=0
site_issue() {
  site_issues=$((site_issues + 1))
  if [ "$SITE_VERSION_MODE" = strict ]; then
    echo "FAIL: $1" >&2
    fail=1
  else
    echo "WARN: $1" >&2
  fi
}
stale_chip=""
stale_foot=""
while IFS= read -r page; do
  chips="$(grep -oE '<small>v[0-9]+\.[0-9]+\.[0-9]+</small>' "$page" || true)"
  foots="$(grep -oE 'Kshana v[0-9]+\.[0-9]+\.[0-9]+ · by Ashforde' "$page" || true)"
  if [ -n "$chips" ] && printf '%s\n' "$chips" | grep -qvF "<small>v${ver}</small>"; then
    stale_chip="${stale_chip} ${page#web/}"
  fi
  if [ -n "$foots" ] && printf '%s\n' "$foots" | grep -qvF "Kshana v${ver} · by Ashforde"; then
    stale_foot="${stale_foot} ${page#web/}"
  fi
done < <(find web -name '*.html' -not -path 'web/assets/*' | LC_ALL=C sort)
if [ -n "$stale_chip" ]; then
  site_issue "web/ pages whose header version chip is not v${ver} ($(printf '%s' "$stale_chip" | wc -w | tr -d ' ')):${stale_chip}"
fi
if [ -n "$stale_foot" ]; then
  site_issue "web/ pages whose footer version is not v${ver} ($(printf '%s' "$stale_foot" | wc -w | tr -d ' ')):${stale_foot}"
fi
if ! grep -qF "Version ${ver}," web/llms.txt; then
  site_issue "web/llms.txt does not state 'Version ${ver},': $(grep -oE 'Version [0-9]+\.[0-9]+\.[0-9]+' web/llms.txt | head -1)"
fi
newest="$(grep -m1 -oE '^## \[[0-9]+\.[0-9]+\.[0-9]+\]' CHANGELOG.md | sed -E 's/^## \[(.*)\]$/\1/')"
if [ -z "$newest" ]; then
  echo "FAIL: CHANGELOG.md has no released '## [X.Y.Z]' heading" >&2
  fail=1
elif ! grep -qF "[${newest}]" web/docs/changelog.html; then
  site_issue "web/docs/changelog.html lacks the newest released CHANGELOG.md heading [${newest}]; newest there: $(grep -oE '\[[0-9]+\.[0-9]+\.[0-9]+\]' web/docs/changelog.html | head -1)"
fi
if [ "$site_issues" -gt 0 ] && [ "$SITE_VERSION_MODE" = warn ]; then
  echo "WARN: ${site_issues} site version issue(s) above are warnings (KSHANA_VERSION_SYNC_SITE=warn); re-port the site from this checkout to clear them." >&2
fi

# 12. The 0.35 channels: the Claude Code plugin manifests, the Signal K plugin, the OpenCPN
#     plugin and its relay, the reference-build image and the Studio's packaged wasm.
#
#     Each is a versioned artefact the release ships (release.yml: release-artefacts.yml,
#     reference-image.yml, signalk-publish.yml), and each carries its own version string that
#     nothing compared to the engine's. .claude-plugin/plugin.json sat at 0.30.0 and
#     marketplace.json at 0.26.0 through four releases. A file that does not exist is a
#     failure here too: a release that is meant to carry the artefact must not ship without it.
json_version() { # json_version <file> <python expression on d>
  python3 - "$1" "$2" <<'PY'
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
print(eval(sys.argv[2]))
PY
}
check_json_version() { # check_json_version <file> <python expression on d> <label>
  if [ ! -f "$1" ]; then
    echo "FAIL: $1 is missing ($3 must ship at v${ver})." >&2
    fail=1
    return
  fi
  got="$(json_version "$1" "$2")"
  if [ "$got" != "$ver" ]; then
    echo "FAIL: $1 $3 is ${got}, engine is ${ver}." >&2
    fail=1
  fi
}
check_json_version .claude-plugin/plugin.json 'd["version"]' version
check_json_version .claude-plugin/marketplace.json 'd["plugins"][0]["version"]' "plugins[0].version"
check_json_version integrations/signalk/package.json 'd["version"]' version
check_json_version integrations/opencpn/package.json 'd["version"]' version

cmake_file="integrations/opencpn/plugin/CMakeLists.txt"
if [ ! -f "$cmake_file" ]; then
  echo "FAIL: $cmake_file is missing (the OpenCPN plugin must ship at v${ver})." >&2
  fail=1
else
  pi_ver="$(grep -m1 -E '^project\(kshana_pi VERSION' "$cmake_file" | sed -E 's/.*VERSION ([0-9.]+).*/\1/')"
  if [ "$pi_ver" != "$ver" ]; then
    echo "FAIL: $cmake_file project VERSION (${pi_ver:-<none>}) != engine ($ver)." >&2
    fail=1
  fi
fi

# The reference-build image states its version in an OCI label in the Dockerfile; the release
# workflow stamps the same label from the tag at build time (reference-image.yml), so a
# committed label that disagrees would be overridden silently and read wrong in the source.
dockerfile="deploy/reference-build/Dockerfile"
if [ ! -f "$dockerfile" ]; then
  echo "FAIL: $dockerfile is missing (the reference-build image must ship at v${ver})." >&2
  fail=1
elif ! grep -qE "^LABEL +org\.opencontainers\.image\.version=\"?${ver//./\\.}\"?( |\$)" "$dockerfile"; then
  echo "FAIL: $dockerfile has no 'LABEL org.opencontainers.image.version=\"${ver}\"'." >&2
  grep -n 'org.opencontainers.image.version' "$dockerfile" >&2 || note "(no version label in the Dockerfile)"
  fail=1
fi

# The Studio's recorded runs carry the engine version that wrote them (the wasm's own
# version() when the recordings are made), the best runtime marker of which engine the
# Studio shows. web/studio/channels.json (install strings) is checked in section 5 above.
check_json_version web/studio/recorded/index.json 'd["engine_version"]' "engine_version (Studio recordings)"

# The Studio's packaged wasm (web/pkg, copied to web/studio/pkg by web/build.sh) is a build
# output, gitignored, and its package.json is generated from Cargo.toml by wasm-pack. It does
# not exist in a fresh checkout, so it is checked only where a build has produced it (a
# release or Pages job after build.sh, or a developer machine): a stale marker there is the
# Studio running an old engine under a new version chip.
for wasm_pkg in web/pkg/package.json web/studio/pkg/package.json; do
  if [ -f "$wasm_pkg" ]; then
    check_json_version "$wasm_pkg" 'd["version"]' "packaged wasm version"
  fi
done

# 7. The release TAG against the manifest.
#
#    Checks 1-6 compare files in the tree to each other, so a tree that is internally
#    consistent at 0.27.2 passes every one of them even while it is being released as
#    v0.28.0. Nothing anywhere made that comparison: a v0.28.0 tag cut on a 0.27.2 tree
#    would publish 0.27.2 to crates.io and PyPI under a 0.28.0 release name, and 0.28.0
#    to the JetBrains Marketplace and ghcr, and every gate would stay green.
#
#    This script already runs on the tag push, in release.yml `verify` and publish.yml
#    `gates`, both of them ahead of anything irreversible — so the comparison costs
#    nothing and fails the release in seconds rather than after the crate is public.
#
#    Asserted only when the ref is a release tag. GITHUB_REF_TYPE is "tag" or "branch" on
#    GitHub; when it says branch this is not a release however the ref is named. When it
#    is unset (a local run) the vX.Y.Z name shape alone decides, which is what lets this
#    be exercised by hand: GITHUB_REF_NAME=v9.9.9 scripts/check-version-sync.sh
#
#    Two refs deliberately fall through it: a PR (GITHUB_REF_NAME is "<n>/merge") and
#    release.yml's workflow_dispatch retry, where github.ref is the branch and the tag
#    lives in an input. The dispatch path is a re-run of a tag that was already checked
#    when it was pushed, so it is not a new hole; a tag pushed for the first time always
#    goes through the `push: tags` trigger and is checked here.
tag_checked="no release tag on this ref"
ref_name="${GITHUB_REF_NAME:-}"
if [ "${GITHUB_REF_TYPE:-tag}" = "tag" ] \
  && printf '%s' "$ref_name" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+'; then
  tag_ver="${ref_name#v}"
  if [ "$tag_ver" != "$ver" ]; then
    echo "FAIL: release tag ${ref_name} does not match Cargo.toml version v${ver}." >&2
    note "the tag and the manifest are two different version strings and this is the only"
    note "place they meet. Either the tag was cut on the wrong commit — move it — or the"
    note "manifest bump is missing: bump Cargo.toml to ${tag_ver}, re-run every surface"
    note "above, and re-tag. Do NOT publish from this tree."
    fail=1
  else
    tag_checked="release tag ${ref_name} matches the manifest"
  fi
fi

if [ "$fail" -ne 0 ]; then
  echo "Version drift detected — bring every surface to v${ver}." >&2
  exit 1
fi

echo "OK: every surface this script checks is at v${ver} — root README \"Status:\" line \
and release badge; README.crates.md / README.npm.md / README.pypi.md release badges; \
mcp/kshana-mcp version and its kshana dependency requirement; JetBrains pluginVersion \
and the newest Marketplace change-notes entry; \
web/index.html JSON-LD and version chip, the Studio's channels.json and the port manifest; \
mcp/kshana-mcp/server.json version and image tag; the README example output; \
the Claude Code plugin manifests, the Signal K and OpenCPN plugin versions, the \
reference-build image label and, where built, the Studio's packaged wasm; \
site chips, footers, llms.txt and changelog page (${SITE_VERSION_MODE}, ${site_issues} issue(s)); ${tag_checked}."
echo "    Not checked here, and not drifting: crates.io / PyPI / npm read the version out \
of Cargo.toml at build time; CITATION.cff, codemeta.json and .zenodo.json are pinned to \
the manifest by tests/citation_metadata_doc_sync.rs."
