#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate the Homebrew formula, the Scoop manifest and the winget manifests for kshana-mcp from a SHA256SUMS file.

    scripts/gen_pkg_manifests.py <version> <SHA256SUMS> <out-dir>

The release's SHA256SUMS lists the checksum of every release asset, so a formula or manifest is never typed by
hand and never names a checksum the release does not have. Writes, under <out-dir>:

  homebrew/Formula/kshana-mcp.rb                              ashfordeOU/homebrew-tap
  scoop/bucket/kshana-mcp.json                                ashfordeOU/scoop-bucket
  winget/manifests/a/AshfordeOU/KshanaMcp/<version>/*.yaml    a pull request to microsoft/winget-pkgs

The checks (scripts/test_gen_pkg_manifests.py) parse each output and compare every URL and checksum with SHA256SUMS.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = "ashfordeOU/kshana"
DESC = "Kshana PNT-resilience simulator as an MCP server (advisory, not type-approved navigation equipment)"
LONG = ("Run the validated Kshana PNT-resilience simulator from an MCP client: orbits, GNSS availability, receiver trust, "
        "interference maps and more. Advisory, not type-approved navigation equipment: the operator remains responsible for navigation.")

# (formula section, asset)
BREW = {
    ("macos", "arm"): "kshana-mcp-aarch64-apple-darwin",
    ("macos", "intel"): "kshana-mcp-x86_64-apple-darwin",
    ("linux", "arm"): "kshana-mcp-aarch64-unknown-linux-gnu",
    ("linux", "intel"): "kshana-mcp",
}
WIN = "kshana-mcp-x86_64-pc-windows-msvc.exe"


def parse_sums(text: str) -> dict[str, str]:
    out = {}
    for line in text.splitlines():
        m = re.match(r"^([0-9a-fA-F]{64})\s+\*?(.+)$", line.strip())
        if m:
            out[m.group(2)] = m.group(1).lower()
    return out


def url(ver: str, asset: str) -> str:
    return f"https://github.com/{REPO}/releases/download/v{ver}/{asset}"


def formula(ver: str, sums: dict[str, str]) -> str:
    body = []
    for os_name in ("macos", "linux"):
        body.append(f"  on_{os_name} do")
        for arch in ("arm", "intel"):
            a = BREW[(os_name, arch)]
            body += [f"    on_{arch} do", f'      url "{url(ver, a)}"', f'      sha256 "{sums[a]}"', "    end"]
        body.append("  end")
    return "\n".join([
        "# Generated by scripts/gen_pkg_manifests.py from the release's SHA256SUMS. Do not edit by hand.",
        "class KshanaMcp < Formula",
        f'  desc "{DESC}"',
        '  homepage "https://kshana.dev"',
        f'  version "{ver}"',
        '  license "AGPL-3.0-only"',
        "",
        *body,
        "",
        "  def install",
        '    bin.install Dir["kshana-mcp*"].first => "kshana-mcp"',
        "  end",
        "",
        "  test do",
        "    init = '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"2025-03-26\",\"capabilities\":{},\"clientInfo\":{\"name\":\"brew\",\"version\":\"0\"}}}'",
        '    assert_match "serverInfo", pipe_output("#{bin}/kshana-mcp", "#{init}\\n")',
        "  end",
        "end",
        "",
    ])


def scoop(ver: str, sums: dict[str, str]) -> str:
    doc = {
        "version": ver,
        "description": DESC,
        "homepage": "https://kshana.dev",
        "license": "AGPL-3.0-only",
        "architecture": {"64bit": {"url": url(ver, WIN) + "#/kshana-mcp.exe", "hash": sums[WIN]}},
        "bin": "kshana-mcp.exe",
        "checkver": {"github": f"https://github.com/{REPO}"},
        "autoupdate": {"architecture": {"64bit": {
            "url": f"https://github.com/{REPO}/releases/download/v$version/{WIN}#/kshana-mcp.exe"}}},
    }
    return json.dumps(doc, indent=4, ensure_ascii=False) + "\n"


def winget(ver: str, sums: dict[str, str]) -> dict[str, str]:
    ident = "AshfordeOU.KshanaMcp"
    head = "# Generated by scripts/gen_pkg_manifests.py from the release's SHA256SUMS.\n"
    return {
        f"{ident}.yaml": head + "\n".join([
            "# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json",
            f"PackageIdentifier: {ident}", f"PackageVersion: {ver}", "DefaultLocale: en-US",
            "ManifestType: version", "ManifestVersion: 1.6.0", ""]),
        f"{ident}.installer.yaml": head + "\n".join([
            "# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json",
            f"PackageIdentifier: {ident}", f"PackageVersion: {ver}", "InstallerType: portable",
            "Commands:", "- kshana-mcp", "Installers:", "- Architecture: x64",
            f"  InstallerUrl: {url(ver, WIN)}", f"  InstallerSha256: {sums[WIN].upper()}",
            "ManifestType: installer", "ManifestVersion: 1.6.0", ""]),
        f"{ident}.locale.en-US.yaml": head + "\n".join([
            "# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json",
            f"PackageIdentifier: {ident}", f"PackageVersion: {ver}", "PackageLocale: en-US",
            "Publisher: Ashforde OÜ", "PublisherUrl: https://ashforde.org",
            "PackageName: Kshana MCP server", "PackageUrl: https://kshana.dev", "License: AGPL-3.0-only",
            f"LicenseUrl: https://github.com/{REPO}/blob/v{ver}/LICENSE",
            f"ShortDescription: {json.dumps(DESC)}", f"Description: {json.dumps(LONG, ensure_ascii=False)}", "Moniker: kshana-mcp",
            "Tags:", "- mcp", "- gnss", "- pnt", "- navigation", "- simulation",
            "ManifestType: defaultLocale", "ManifestVersion: 1.6.0", ""]),
    }


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    ver, sums_path, out = argv[1], Path(argv[2]), Path(argv[3])
    sums = parse_sums(sums_path.read_text(encoding="utf-8"))
    need = sorted(set(BREW.values()) | {WIN})
    missing = [a for a in need if a not in sums]
    if missing:
        print(f"FAIL: SHA256SUMS does not list: {', '.join(missing)}", file=sys.stderr)
        return 1
    def put(rel: str, text: str) -> None:
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    put("homebrew/Formula/kshana-mcp.rb", formula(ver, sums))
    put("scoop/bucket/kshana-mcp.json", scoop(ver, sums))
    for name, text in winget(ver, sums).items():
        put(f"winget/manifests/a/AshfordeOU/KshanaMcp/{ver}/{name}", text)
    print(f"wrote the Homebrew formula, the Scoop manifest and the winget manifests for v{ver} under {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
