#!/usr/bin/env python3
"""Fixture generator for tests/bplane_heliocentric_oracle.rs.

1. Reads the 192 planetocentric hyperbolic states of ../bplane_gmat_oracle/states.txt and
   rebuilds the same grid from its elements (bplane_gmat_oracle/make_fixture.py), checking
   that the decimal strings agree.
2. Builds, in numpy, the arrival and departure asymptote directions of each hyperbola from its
   elements, places the encounter at a planet on a circular ecliptic orbit and writes the two
   Sun-centred states (before and after the assist) to helio_states.txt (17 significant
   digits), dropping states with an inclination below 1e-3 rad or above pi - 1e-3 rad
   (amendment 1; the pre-registration said 1e-2).
3. Writes helio_grid.script for the General Mission Analysis Tool (GMAT) R2026a and runs it
   headless: C3Energy and the asymptote directions of the planetocentric states, and SMA, ECC
   (origin Sun) and INC (axes MJ2000Ec) of the heliocentric states.
4. Runs sbpy 0.6.0 Orbit.tisserand on GMAT's SMA, ECC and INC (separate process).

Usage:
    source ~/Code/kshana-oracles/env.sh
    PYTHONPATH=<dir with sbpy 0.6.0> $ORACLE_PY tests/fixtures/bplane_heliocentric_oracle/make_fixture.py
"""
import importlib.util
import math
import os
import shutil
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PLANETO = os.path.join(HERE, "..", "bplane_gmat_oracle")
spec = importlib.util.spec_from_file_location("grid", os.path.join(PLANETO, "make_fixture.py"))
grid = importlib.util.module_from_spec(spec)
spec.loader.exec_module(grid)

MU_SUN = 132712440041.93938  # km^3/s^2 (DE440), set as Sun.Mu in the script
AU_KM = 149597870.7
PLANETS = [  # name, a_P (au)
    ("Mercury", 0.38709927),
    ("Venus", 0.72333566),
    ("Earth", 1.00000261),
    ("Mars", 1.52371034),
    ("Jupiter", 5.20288700),
]
GOLDEN_DEG = 137.507764
MIN_INC = 1e-3  # amendment 1 (was 1e-2)


def main():
    # 1. The planetocentric grid, identical to states.txt.
    params = []
    for v in grid.V_INF:
        for rp in grid.R_P:
            for (i, o, w) in grid.ORIENT:
                for f in grid.NU_FRAC:
                    params.append((v, rp, i, o, w, f))
    with open(os.path.join(PLANETO, "states.txt")) as fh:
        planeto = [l.split() for l in fh if l.strip() and not l.startswith("#")]
    assert len(planeto) == len(params) == 192
    for (v, rp, i, o, w, f), row in zip(params, planeto):
        assert ["%.17g" % x for x in grid.state(v, rp, i, o, w, f)] == row[1:], row[0]

    # 2. Heliocentric states.
    helio = []
    dropped = 0
    for k, (v, rp, i, o, w, f) in enumerate(params, 1):
        e = 1.0 + rp * v * v / grid.MU
        nu_inf = math.acos(-1.0 / e)
        p, q = grid.rot(math.radians(i), math.radians(o), math.radians(w))
        p, q = np.array(p), np.array(q)
        s_in = -math.cos(nu_inf) * p + math.sin(nu_inf) * q
        s_out = math.cos(nu_inf) * p + math.sin(nu_inf) * q
        cands = [(n, a) for (n, a) in PLANETS if v <= 0.27 * math.sqrt(MU_SUN / (a * AU_KM))]
        name, a_au = cands[k % len(cands)]
        a_p = a_au * AU_KM
        vc = math.sqrt(MU_SUN / a_p)
        lon = math.radians((k * GOLDEN_DEG) % 360.0)
        r_p = np.array([a_p * math.cos(lon), a_p * math.sin(lon), 0.0])
        v_p = np.array([-vc * math.sin(lon), vc * math.cos(lon), 0.0])
        for branch, s in ((0, s_in), (1, s_out)):
            vel = v_p + v * s
            h = np.cross(r_p, vel)
            inc = math.acos(h[2] / np.linalg.norm(h))
            if inc < MIN_INC or inc > math.pi - MIN_INC:
                dropped += 1
                continue
            helio.append((k, branch, PLANETS.index((name, a_au)), a_p, list(r_p) + list(vel)))
    print("heliocentric states: %d kept, %d dropped (inclination)" % (len(helio), dropped))
    with open(os.path.join(HERE, "helio_states.txt"), "w") as fh:
        fh.write("# id k branch(0 before, 1 after) planet(0 Mercury .. 4 Jupiter) a_P (km) "
                 "X Y Z (km) VX VY VZ (km/s), SunMJ2000Ec, generated by make_fixture.py\n")
        for n, (k, b, pl, a_p, sv) in enumerate(helio, 1):
            fh.write("%d %d %d %d %s %s\n" % (n, k, b, pl, "%.17g" % a_p,
                                             " ".join("%.17g" % x for x in sv)))
    # Re-read the decimal strings so GMAT gets exactly what the test reads.
    with open(os.path.join(HERE, "helio_states.txt")) as fh:
        hrows = [l.split() for l in fh if l.strip() and not l.startswith("#")]

    # 3. GMAT.
    work = os.path.join(HERE, "_gmat_run")
    os.makedirs(work, exist_ok=True)
    rep1 = os.path.join(work, "planeto.txt")
    rep2 = os.path.join(work, "helio.txt")
    L = ["Earth.Mu = 398600.4415;", "Sun.Mu = %.17g;" % MU_SUN,
         "Create CoordinateSystem SunEc;", "SunEc.Origin = Sun;", "SunEc.Axes = MJ2000Ec;"]
    for row in planeto:
        k = row[0]
        L += ["Create Spacecraft p%s;" % k, "p%s.CoordinateSystem = EarthMJ2000Eq;" % k,
              "p%s.DisplayStateType = Cartesian;" % k]
        L += ["p%s.%s = %s;" % (k, n, x) for n, x in zip(["X", "Y", "Z", "VX", "VY", "VZ"], row[1:])]
    for row in hrows:
        n = row[0]
        L += ["Create Spacecraft h%s;" % n, "h%s.CoordinateSystem = SunEc;" % n,
              "h%s.DisplayStateType = Cartesian;" % n]
        L += ["h%s.%s = %s;" % (n, c, x) for c, x in zip(["X", "Y", "Z", "VX", "VY", "VZ"], row[5:])]
    L += ["Create Variable id;"]
    for name, path in (("rf1", rep1), ("rf2", rep2)):
        L += ["Create ReportFile %s;" % name, "%s.Filename = '%s';" % (name, path),
              "%s.Precision = 16;" % name, "%s.WriteHeaders = false;" % name,
              "%s.LeftJustify = On;" % name, "%s.ZeroFill = Off;" % name,
              "%s.ColumnWidth = 26;" % name]
    L += ["BeginMissionSequence;"]
    for row in planeto:
        k = row[0]
        L += ["id = %s;" % k,
              "Report rf1 id p%s.Earth.C3Energy %s;" % (k, " ".join(
                  "p%s.EarthMJ2000Eq.%s" % (k, x)
                  for x in ["IncomingRHA", "IncomingDHA", "OutgoingRHA", "OutgoingDHA"]))]
    for row in hrows:
        n = row[0]
        L += ["id = %s;" % n, "Report rf2 id h%s.Sun.SMA h%s.Sun.ECC h%s.SunEc.INC;" % (n, n, n)]
    script = os.path.join(HERE, "helio_grid.script")
    with open(script, "w") as fh:
        fh.write("% Generated by make_fixture.py: GMAT heliocentric oracle (one statement per line)\n")
        fh.write("\n".join(L) + "\n")
    gmat = os.environ.get("KSHANA_GMAT")
    if not gmat:
        sys.exit("source ~/Code/kshana-oracles/env.sh first (KSHANA_GMAT)")
    for r in (rep1, rep2):
        if os.path.exists(r):
            os.remove(r)
    out = subprocess.run([gmat, "--run", script, "--exit"], cwd=os.path.dirname(gmat),
                         capture_output=True, text=True)
    with open(os.path.join(work, "gmat_console.log"), "w") as fh:
        fh.write(out.stdout + out.stderr)
    if not (os.path.exists(rep1) and os.path.exists(rep2)):
        sys.exit("GMAT wrote no report; see _gmat_run/gmat_console.log")
    with open(rep1) as src, open(os.path.join(HERE, "gmat_planetocentric_report.txt"), "w") as dst:
        dst.write("# GMAT R2026a GmatConsole report for helio_grid.script: id C3Energy (km^2/s^2) "
                  "IncomingRHA IncomingDHA OutgoingRHA OutgoingDHA (deg), EarthMJ2000Eq; "
                  "states from ../bplane_gmat_oracle/states.txt\n")
        dst.write(src.read())
    with open(rep2) as src, open(os.path.join(HERE, "gmat_helio_report.txt"), "w") as dst:
        dst.write("# GMAT R2026a GmatConsole report for helio_grid.script: id SMA (km) ECC "
                  "(origin Sun) INC (deg, SunMJ2000Ec)\n")
        dst.write(src.read())
    shutil.rmtree(work)

    # 4. sbpy Tisserand from GMAT's elements.
    code = r"""
import sys, warnings
warnings.simplefilter("ignore")
import numpy as np
import astropy.units as u
import sbpy
from sbpy.data import Orbit
h, g = sys.argv[1], sys.argv[2]
ap = [float(l.split()[4]) for l in open(h) if l.strip() and not l.startswith('#')]
ids, a, e, i = [], [], [], []
for l in open(g):
    if not l.strip() or l.startswith('#'):
        continue
    f = l.split()
    ids.append(int(f[0])); a.append(float(f[1])); e.append(float(f[2])); i.append(float(f[3]))
assert len(ap) == len(ids)
sc = Orbit.from_dict({'a': np.array(a) * u.km, 'e': np.array(e), 'i': np.array(i) * u.deg})
pl = Orbit.from_dict({'a': np.array(ap) * u.km})
t = np.atleast_1d(u.Quantity(sc.tisserand(pl)).to_value(u.dimensionless_unscaled))
print('# sbpy %s Orbit.tisserand on GMAT SMA, ECC, INC with planet a = a_P: id T' % sbpy.__version__)
for k, x in zip(ids, t):
    print('%d %.17g' % (k, x))
"""
    out = subprocess.run([sys.executable, "-c", code, os.path.join(HERE, "helio_states.txt"),
                          os.path.join(HERE, "gmat_helio_report.txt")],
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(out.stderr)
    with open(os.path.join(HERE, "sbpy_tisserand.txt"), "w") as fh:
        fh.write(out.stdout)


if __name__ == "__main__":
    main()
