// SPDX-License-Identifier: AGPL-3.0-only
//
// CwOrekitDriver: nonlinear two-body relative motion from Orekit 12.2 (Apache-2.0), expressed in
// the chief's Hill frame, as the oracle for the Clohessy-Wiltshire state-transition matrix.
//
// Chief: circular orbit, a = 6378137 + 500e3 m, i = 51.6 deg, RAAN 30 deg, argument of latitude 0
// at the epoch, EME2000, mu = 3.986004418e14 (the value Kshana uses). Deputy: the chief's state plus
// a relative state given in Orekit's LOFType.QSW frame (Q radial, S along-track, W orbit normal),
// mapped to inertial by the inverse of Orekit's QSW transform (which carries the frame rotation into
// the velocity). Chief and deputy are each propagated by an Orekit NumericalPropagator
// (DormandPrince853, Newtonian attraction only, position tolerance 1e-10 m), and the deputy is
// mapped back into the chief's QSW frame at every sample. As an oracle self-check the numerical
// chief is compared with Orekit's analytic KeplerianPropagator at every sample.
//
// Compile and run (writes the fixture to stdout):
//   source ~/Code/kshana-oracles/env.sh
//   javac -cp "$OREKIT_CP" -d /path/to/scratch CwOrekitDriver.java
//   java -cp "/path/to/scratch:$OREKIT_CP" CwOrekitDriver > cw_dynamics_orekit_oracle.txt

import java.io.File;
import java.util.Locale;

import org.hipparchus.geometry.euclidean.threed.Vector3D;
import org.hipparchus.ode.nonstiff.DormandPrince853Integrator;
import org.orekit.data.DataContext;
import org.orekit.data.DirectoryCrawler;
import org.orekit.forces.gravity.NewtonianAttraction;
import org.orekit.frames.Frame;
import org.orekit.frames.FramesFactory;
import org.orekit.frames.LOFType;
import org.orekit.frames.Transform;
import org.orekit.orbits.CartesianOrbit;
import org.orekit.orbits.KeplerianOrbit;
import org.orekit.orbits.Orbit;
import org.orekit.orbits.OrbitType;
import org.orekit.orbits.PositionAngleType;
import org.orekit.propagation.SpacecraftState;
import org.orekit.propagation.analytical.KeplerianPropagator;
import org.orekit.propagation.numerical.NumericalPropagator;
import org.orekit.time.AbsoluteDate;
import org.orekit.time.TimeScalesFactory;
import org.orekit.utils.PVCoordinates;

public class CwOrekitDriver {
    static final double MU = 3.986004418e14;
    static final double A = 6378137.0 + 500.0e3;

    static NumericalPropagator numerical(Orbit orbit) {
        double[][] tol = NumericalPropagator.tolerances(1e-10, orbit, OrbitType.CARTESIAN);
        DormandPrince853Integrator integ = new DormandPrince853Integrator(1e-3, 300.0, tol[0], tol[1]);
        NumericalPropagator p = new NumericalPropagator(integ);
        p.setOrbitType(OrbitType.CARTESIAN);
        p.addForceModel(new NewtonianAttraction(MU));
        p.setInitialState(new SpacecraftState(orbit));
        return p;
    }

    public static void main(String[] args) {
        String data = System.getenv("OREKIT_DATA");
        DataContext.getDefault().getDataProvidersManager().addProvider(new DirectoryCrawler(new File(data)));
        Locale.setDefault(Locale.ROOT);

        Frame eme = FramesFactory.getEME2000();
        AbsoluteDate t0 = new AbsoluteDate(2026, 1, 1, 0, 0, 0.0, TimeScalesFactory.getUTC());
        KeplerianOrbit chief0 = new KeplerianOrbit(A, 0.0, Math.toRadians(51.6), 0.0, Math.toRadians(30.0),
                0.0, PositionAngleType.TRUE, eme, t0, MU);
        double n = Math.sqrt(MU / (A * A * A));
        double period = 2.0 * Math.PI / n;
        double span = period / 3.0;
        double s = 100.0 / Math.sqrt(3.0);

        String[] ids = {"C1_radial_bounded", "C2_along_track", "C3_cross_track", "C4_mixed_bounded"};
        double[][] rel0 = {
            {100.0, 0.0, 0.0, 0.0, -2.0 * n * 100.0, 0.0},
            {0.0, 100.0, 0.0, 0.0, 0.0, 0.0},
            {0.0, 0.0, 100.0, 0.0, 0.0, 0.0},
            {s, s, s, 0.0, -2.0 * n * s, 0.0},
        };

        System.out.println("# Nonlinear two-body relative motion, Orekit 12.2 (Apache-2.0), chief Hill frame = LOFType.QSW.");
        System.out.println("# Generated by CwOrekitDriver.java; see its header and NOTICE.md.");
        System.out.printf("# mu = %.10e m^3/s^2, chief a = %.3f m (circular, i 51.6 deg, RAAN 30 deg), span = T/3 = %.6f s%n", MU, A, span);
        System.out.println("# CASE id | a_m | rho0 x y z (m) | rhodot0 x y z (m/s)");
        System.out.println("# S id | t_s | rho x y z (m) | rhodot x y z (m/s) | |chief numerical - Keplerian| (m)");

        for (int c = 0; c < ids.length; c++) {
            double[] r0 = rel0[c];
            Transform toLof = LOFType.QSW.transformFromInertial(t0, chief0.getPVCoordinates());
            PVCoordinates relPv = new PVCoordinates(new Vector3D(r0[0], r0[1], r0[2]), new Vector3D(r0[3], r0[4], r0[5]));
            PVCoordinates dep0 = toLof.getInverse().transformPVCoordinates(relPv);
            CartesianOrbit deputy0 = new CartesianOrbit(dep0, eme, t0, MU);
            CartesianOrbit chiefCart = new CartesianOrbit(chief0);

            NumericalPropagator pc = numerical(chiefCart);
            NumericalPropagator pd = numerical(deputy0);
            KeplerianPropagator kc = new KeplerianPropagator(chief0);

            System.out.printf("CASE %s | %.6f | %.17e %.17e %.17e | %.17e %.17e %.17e%n", ids[c], A,
                    r0[0], r0[1], r0[2], r0[3], r0[4], r0[5]);
            int nSteps = (int) Math.floor(span / 60.0);
            for (int k = 0; k <= nSteps + 1; k++) {
                double t = (k <= nSteps) ? 60.0 * k : span;
                if (k == nSteps + 1 && Math.abs(span - 60.0 * nSteps) < 1e-9) {
                    break;
                }
                AbsoluteDate d = t0.shiftedBy(t);
                PVCoordinates pvC = pc.propagate(d).getPVCoordinates(eme);
                PVCoordinates pvD = pd.propagate(d).getPVCoordinates(eme);
                PVCoordinates pvK = kc.propagate(d).getPVCoordinates(eme);
                Transform lof = LOFType.QSW.transformFromInertial(d, pvC);
                PVCoordinates rel = lof.transformPVCoordinates(pvD);
                double kepDiff = pvC.getPosition().subtract(pvK.getPosition()).getNorm();
                Vector3D p = rel.getPosition();
                Vector3D v = rel.getVelocity();
                System.out.printf("S %s | %.9f | %.17e %.17e %.17e | %.17e %.17e %.17e | %.3e%n", ids[c], t,
                        p.getX(), p.getY(), p.getZ(), v.getX(), v.getY(), v.getZ(), kepDiff);
            }
        }
    }
}
